# Task-specific distillation for BERT
Link:
- https://www.philschmid.de/knowledge-distillation-bert-transformers

This is end-to-end task-specific knowledge distilation Text-Classification example. Here we'll be using Transformers, PyTorch & Amazon SageMaker.

Distillation is the process of training a small "student" model to mimic a larger "teacher" model. 

In this example, we will use a [BERT-base](https://huggingface.co/textattack/bert-base-uncased-SST-2) as Teacher (~109 M) and [BERT-Tiny](https://huggingface.co/google/bert_uncased_L-2_H-128_A-2) (4.4 M) as Student. We will use [Text-Classification](https://huggingface.co/tasks/text-classification) as our task-specific knowledge distillation task and the [Stanford Sentiment Treebank v2 (SST-2)](https://huggingface.co/datasets/stanfordnlp/sst2) dataset for training.

They are two different types of knowledge distillation, the Task-agnostic knowledge distillation (right) and the Task-specific knowledge distillation (left). In this example we are going to use the Task-specific knowledge distillation.

In Task-specific knowledge distillation a "second step of distillation" is used to "fine-tune" the model on a given dataset. This idea comes from the [DistilBERT](https://huggingface.co/datasets/stanfordnlp/sst2) paper where it was shown that a student performed better than simply finetuning the distilled language model.

## Installation

In [2]:
%pip install transformers datasets tensorboard --upgrade
%pip install 'accelerate>=1.1.0'
# run in terminal:
# !sudo apt-get install git-lfs
# or
# brew install git-lfs
# git lfs install

Requirement already satisfied: transformers in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (5.20.2)
Requirement already satisfied: datasets in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (5.1.0)
Requirement already satisfied: tensorboard in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (2.21.0)
Requirement already satisfied: huggingface-hub<3.0,>=1.31.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from transformers) (2.3.0)
Requirement already satisfied: numpy>=1.17 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from transformers) (2.5.2)
Requirement already satisfied: packaging>=20.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from transformers) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from transformers) (2026.9.29)
Requirement already satisfied: tokenizers<0.24.0,>=0.23.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from transformers) (0.23.3)
Requirement already satisfied: typer in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from transformers) (0.27.3)
Requirement already satisfied: safetensors>=0.8.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from transformers) (4.70.1)
Requirement already satisfied: filelock in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from datasets) (4.2.4)
Requirement already satisfied: pyarrow>=24.0.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from datasets) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from datasets) (3.0.5)
Requirement already satisfied: xxhash in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from datasets) (4.0.2)
Requirement already satisfied: multiprocess<0.70.20 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.7.0,>=2023.1.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (2026.7.0)
Requirement already satisfied: absl-py>=0.4 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from tensorboard) (2.5.1)
Requirement already satisfied: grpcio<2.0,>=1.74.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from tensorboard) (1.84.1)
Requirement already satisfied: markdown>=2.6.8 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from tensorboard) (3.11.2)
Requirement already satisfied: pillow in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from tensorboard) (12.3.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from tensorboard) (7.36.2)
Requirement already satisfied: setuptools>=41.0.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from tensorboard) (84.2.1)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from tensorboard) (3.1.9)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (3.14.5)
Requirement already satisfied: typing-extensions~=4.12 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from grpcio<2.0,>=1.74.0->tensorboard) (4.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (1.7.0)
Requirement already satisfied: httpx2<3,>=2.0.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (2.16.0)
Requirement already satisfied: markupsafe>=2.1.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from pandas->datasets) (3.0.0)
Requirement already satisfied: shellingham>=1.3.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from typer->transformers) (0.0.5)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<8.0,>=4.5 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (7.1.0)
Requirement already satisfied: propcache>=0.2.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.25.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (1.25.1)
Requirement already satisfied: anyio>=4.10 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers) (4.15.1)
Requirement already satisfied: httpcore2==2.16.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers) (2.16.0)
Requirement already satisfied: idna>=3.18 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers) (3.20)
Requirement already satisfied: truststore>=0.10 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers) (0.10.5)
Requirement already satisfied: h11>=0.16 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from httpcore2==2.16.0->httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers) (0.16.0)
Requirement already satisfied: six>=1.6 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: tzdata in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (2026.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from rich>=13.8.0->typer->transformers) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: accelerate>=1.1.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (1.15.0)
Requirement already satisfied: numpy>=1.17 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from accelerate>=1.1.0) (2.5.2)
Requirement already satisfied: packaging>=20.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from accelerate>=1.1.0) (26.3)
Requirement already satisfied: psutil in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from accelerate>=1.1.0) (7.2.2)
Requirement already satisfied: pyyaml in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from accelerate>=1.1.0) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from accelerate>=1.1.0) (2.14.1)
Requirement already satisfied: huggingface_hub>=0.21.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from accelerate>=1.1.0) (2.3.0)
Requirement already satisfied: safetensors>=0.4.3 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from accelerate>=1.1.0) (0.8.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (4.2.4)
Requirement already satisfied: fsspec>=2023.5.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (2026.7.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (1.7.0)
Requirement already satisfied: httpx2<3,>=2.0.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (2.16.0)
Requirement already satisfied: tqdm>=4.42.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (4.70.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (4.16.0)
Requirement already satisfied: setuptools>=77.0.3 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (84.2.1)
Requirement already satisfied: sympy>=1.13.3 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (3.7)
Requirement already satisfied: jinja2 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (3.1.6)
Requirement already satisfied: cuda-toolkit==13.0.3 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.1.0) (13.0.3.0)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (13.4.4)
Requirement already satisfied: nvidia-cudnn-cu13==9.24.0.43 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (9.24.0.43)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (0.8.1)
Requirement already satisfied: nvidia-nccl-cu13==2.30.7 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (2.30.7)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (3.4.5)
Requirement already satisfied: triton~=3.8.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.1.0) (3.8.0)
Requirement already satisfied: nvidia-cublas==13.1.1.3.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.1.0) (13.1.1.3)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.1.0) (13.0.88)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.1.0) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.1.0) (12.0.0.61)
Requirement already satisfied: nvidia-nvjitlink<14,>=13.0.88 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.1.0) (13.4.92)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.1.0) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.1.0) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.1.0) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.1.0) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.1.0) (12.6.3.3)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.1.0) (13.0.85)
Requirement already satisfied: cuda-pathfinder>=1.4.2 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-bindings<14,>=13.0.3->torch>=2.0.0->accelerate>=1.1.0) (1.8.4)
Requirement already satisfied: anyio>=4.10 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from httpx2<3,>=2.0.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (4.15.1)
Requirement already satisfied: httpcore2==2.16.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from httpx2<3,>=2.0.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (2.16.0)
Requirement already satisfied: idna>=3.18 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from httpx2<3,>=2.0.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (3.20)
Requirement already satisfied: truststore>=0.10 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from httpx2<3,>=2.0.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (0.10.5)
Requirement already satisfied: h11>=0.16 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from httpcore2==2.16.0->httpx2<3,>=2.0.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate>=1.1.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from jinja2->torch>=2.0.0->accelerate>=1.1.0) (3.0.4)
Note: you may need to restart the kernel to use updated packages.

## Setup and configuration
In this example, we will use BERT-base as Teacher and BERT-Tiny as Student. Our Teacher is already fine-tuned on our dataset, which makes it easy for us to directly start the distillation training job rather than fine-tuning the teacher first to then distill it afterwards.

*IMPORTANT: This example will only work with a Teacher & Student combination where the Tokenizer is creating the same output.*

In [3]:
student_id = "google/bert_uncased_L-2_H-128_A-2"
teacher_id = "textattack/bert-base-uncased-SST-2"

In [4]:
from transformers import AutoTokenizer

/home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Here we check, that teacher and student divide identical text into the same tokens. Otherwise it won'r work.

In [5]:
# init tokenizer
teacher_tokenizer = AutoTokenizer.from_pretrained(teacher_id)
student_tokenizer = AutoTokenizer.from_pretrained(student_id)
 
# sample input
sample = "This is a basic example, with different words to test."
 
# assert results
assert teacher_tokenizer(sample) == student_tokenizer(sample), "Tokenizers haven't created the same output"

## Dataset and pre-processing

As Dataset we will use the [Stanford Sentiment Treebank v2 (SST-2)](https://huggingface.co/datasets/stanfordnlp/sst2) a text-classification for `sentiment-analysis`, which is included in the [GLUE benchmark](https://gluebenchmark.com/). The dataset is based on the dataset introduced by Pang and Lee (2005) and consists of 11,855 single sentences extracted from movie reviews. It was parsed with the Stanford parser and includes a total of 215,154 unique phrases from those parse trees, each annotated by 3 human judges. It uses the two-way (positive/negative) class split, with only sentence-level labels.

In [6]:
from datasets import load_dataset
from transformers import AutoTokenizer

In [7]:
dataset_id="nyu-mll/glue"
dataset_config="sst2"

In [8]:
dataset = load_dataset(dataset_id,dataset_config)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

### Pre-processing & Tokenization

To distill our model we need to convert our "Natural Language" to token IDs.

We are going to use the tokenizer of the Teacher, though we could also go with the Student tokenizer.

In [9]:

tokenizer = AutoTokenizer.from_pretrained(teacher_id)

Additionally we add the `truncation=True` and `max_length=512` to align the length and truncate texts that are bigger than the maximum size allowed by the model.

In [10]:
def process(examples):
    tokenized_inputs = tokenizer(
        examples["sentence"], truncation=True, max_length=512
    )
    return tokenized_inputs

In [11]:
tokenized_datasets = dataset.map(process, batched=True)
tokenized_datasets = tokenized_datasets.rename_column("label","labels")
 
tokenized_datasets["test"].features

{'sentence': Value('string'),
 'labels': ClassLabel(names=['negative', 'positive']),
 'idx': Value('int32'),
 'input_ids': List(Value('int32')),
 'token_type_ids': List(Value('int8')),
 'attention_mask': List(Value('int8'))}

`input_ids` -- stores tokenized sentences.

## Distilling the model using PyTorch and DistillationTrainer
Now that our `dataset` is processed, we can distill it. Normally, when fine-tuning a transformer model using PyTorch you should go with the `Trainer-API`. The [Trainer](https://huggingface.co/docs/transformers/v4.16.1/en/main_classes/trainer#transformers.Trainer) class provides an API for feature-complete training in PyTorch for most standard use cases.

In our example we cannot use the `Trainer` out-of-the-box, since we need to pass in two models, the `Teacher` and the `Student` and compute the loss for both. But we can subclass the `Trainer` to create a `DistillationTrainer` which will take care of it and only overwrite the [compute_loss](https://github.com/huggingface/transformers/blob/c4ad38e5ac69e6d96116f39df789a2369dd33c21/src/transformers/trainer.py#L1962) method as well as the `init` method. In addition to this we also need to subclass the `TrainingArguments` to include the our distillation hyperparameters.

In [12]:
from transformers import TrainingArguments, Trainer
import torch
import torch.nn as nn
import torch.nn.functional as F
from transformers import AutoModelForSequenceClassification, DataCollatorWithPadding

In [13]:
class DistillationTrainingArguments(TrainingArguments):
    def __init__(self, *args, alpha=0.5, temperature=2.0, **kwargs):
        super().__init__(*args, **kwargs)
 
        self.alpha = alpha # to include two losses equally: 
                            # real label of sst and how much 
                            # distributions of student and teacher differ
        self.temperature = temperature # 2.0 by default 
                                        # logits are dividet by this value
                                        # student studies how confident was the teacher
        # because TrainingArguments does not have those args

class DistillationTrainer(Trainer):
    def __init__(self, *args, teacher_model=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.teacher = teacher_model # adding teacher into the trainer
        # place teacher on same device as student
        self._move_model_to_device(self.teacher,self.model.device) # placing teacher on the same device 
                                                                    # so comparison of logits is valid
        self.teacher.eval() # turn on evaluation regime: no dropout, same logits for the same sentence;
                            # weights are not updated, it also does not get into the optimiser


    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
 
        # compute student output
        outputs_student = model(**inputs)
        student_loss=outputs_student.loss # cross-entropy loss
        # compute teacher output
        with torch.no_grad(): # weights are not being updated
          outputs_teacher = self.teacher(**inputs)
 
        # assert size
        assert outputs_student.logits.size() == outputs_teacher.logits.size()
 
        # Soften probabilities and compute distillation loss
        loss_function = nn.KLDivLoss(reduction="batchmean") 
        loss_logits = (loss_function(
            F.log_softmax(outputs_student.logits / self.args.temperature, dim=-1),
            F.softmax(outputs_teacher.logits / self.args.temperature, dim=-1)) * (self.args.temperature ** 2)) 
                                                                                # multiplication for scaling
        # Return weighted student loss
        loss = self.args.alpha * student_loss + (1. - self.args.alpha) * loss_logits
        return (loss, outputs_student) if return_outputs else loss

Kullback-Leibler loss (`KLDivLoss`):
- how much student's distributtion differs from teacher's
- teacher_p * log(teacher_p / student_p)

`reduction="batchmean"` averages those sums per batch:
$$\frac{1}{m}\sum^m_1(p_T(neg)\log(\frac{p_T(neg)}{p_S(neg)})+p_T(pos)\log(\frac{p_T(pos)}{p_S(pos)}))$$

### Hyperparameter Definition, Model Loading

In [14]:
# create label2id, id2label dicts for nice outputs for the model
labels = tokenized_datasets["train"].features["labels"].names
num_labels = len(labels)
label2id, id2label = dict(), dict()
for i, label in enumerate(labels):
    label2id[label] = str(i)
    id2label[str(i)] = label
 
output_dir = "../models/tiny-bert-sst2"

# define training args
training_args = DistillationTrainingArguments(
    output_dir=output_dir,
    num_train_epochs=7, # n of epoch for whole train-split
    per_device_train_batch_size=128, # how many sentences per step
    per_device_eval_batch_size=128,
    fp16=True, # True for GPU NVIDIA
    learning_rate=6e-5, # optimiser's step
    seed=33,

    # logging & evaluation strategies
    logging_strategy="epoch", # to get more information to TensorBoard
    eval_strategy="epoch", # accuracy for validation
    save_strategy="epoch", 
    save_total_limit=2, # n of last checkpoints
    load_best_model_at_end=True, 
    metric_for_best_model="accuracy",
    report_to="tensorboard",

    # distilation parameters
    alpha=0.5,
    temperature=4.0
    )
 
# define data_collator
data_collator = DataCollatorWithPadding(tokenizer=tokenizer) # padding fot too short sentences
 
# define model
teacher_model = AutoModelForSequenceClassification.from_pretrained(
    teacher_id,
    num_labels=num_labels,
    id2label=id2label,
    label2id=label2id,
)
 
# define student model
student_model = AutoModelForSequenceClassification.from_pretrained(
    student_id,
    num_labels=num_labels,
    id2label=id2label,
    label2id=label2id,
)

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 72545.83it/s]
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 17504.32it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [15]:
print(training_args.device)

cuda:0

In [ ]:
teacher_model.save_pretrained("../models/bert-base-sst2-teacher")
tokenizer.save_pretrained("../models/bert-base-sst2-teacher")

### Evaluation metric

In [16]:
import numpy as np

In [17]:
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    return {"accuracy": (predictions == labels).mean().item()}

### Training

In [18]:
trainer = DistillationTrainer(
    student_model,
    training_args,
    teacher_model=teacher_model,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    data_collator=data_collator,
    processing_class=tokenizer,
    compute_metrics=compute_metrics,
)

In [19]:
trainer.train()

Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 94.18it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 170.37it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 191.98it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 177.46it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 175.69it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 97.13it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 164.85it/s]

TrainOutput(global_step=3689, training_loss=0.7028158988756162, metrics={'train_runtime': 283.9612, 'train_samples_per_second': 1660.237, 'train_steps_per_second': 12.991, 'total_flos': 56628612372420.0, 'train_loss': 0.7028158988756162, 'epoch': 7.0})

Student is about 25 times smaller, and still accuracy fell from 93.5% to 83.1%, which is great

### Hyperparameter Search for Distillation parameter alpha & temperature with optuna
The parameter `alpha` & `temparature` in the `DistillationTrainer` can also be used when doing Hyperparamter search to maxizime our "knowledge extraction". As Hyperparamter Optimization framework are we using [Optuna](https://optuna.org/), which has an integration into the Trainer-API. Since the DistillationTrainer is a sublcass of the Trainer we can use the hyperparameter_search without any code changes.

In [20]:
%pip install optuna

Requirement already satisfied: optuna in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (5.0.0)
Requirement already satisfied: alembic>=1.5.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from optuna) (1.20.1)
Requirement already satisfied: colorlog in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from optuna) (6.12.0)
Requirement already satisfied: numpy in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from optuna) (2.5.2)
Requirement already satisfied: packaging>=20.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from optuna) (26.3)
Requirement already satisfied: sqlalchemy>=1.4.2 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from optuna) (2.1.6)
Requirement already satisfied: tqdm in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from optuna) (4.70.1)
Requirement already satisfied: PyYAML in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from alembic>=1.5.0->optuna) (1.4.3)
Requirement already satisfied: typing-extensions>=4.12 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from alembic>=1.5.0->optuna) (4.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.4)
Note: you may need to restart the kernel to use updated packages.

To do optimisation we need to define hyperparameter space.

In [21]:
def hp_space(trial):
    return {
        "num_train_epochs": trial.suggest_int("num_train_epochs", 2, 10),
        "learning_rate": trial.suggest_float("learning_rate", 1e-5, 1e-3 ,log=True),
        "alpha": trial.suggest_float("alpha", 0, 1),
        "temperature": trial.suggest_int("temperature", 2, 30),
        }

In [22]:
def student_init():
    return AutoModelForSequenceClassification.from_pretrained(
        student_id,
        num_labels=num_labels,
        id2label=id2label,
        label2id=label2id
    )

training_args.output_dir = "../models/tiny-bert-hpo"
training_args.save_strategy = "no"
training_args.load_best_model_at_end = False

trainer = DistillationTrainer(
    model_init=student_init,
    args=training_args,
    teacher_model=teacher_model,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    data_collator=data_collator,
    processing_class=tokenizer,
    compute_metrics=compute_metrics,
)
best_run = trainer.hyperparameter_search(
    n_trials=50,
    direction="maximize",
    hp_space=hp_space
)

print(best_run)

Loading weights: 100%|██████████| 39/39 [00:00<00:00, 15468.36it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
[I 2026-10-23 19:52:05,139] A new study created in memory with name: no-name-96acc0e7-4bb4-41c0-8faa-93d2a908836a
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 10940.93it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 19:57:54,183] Trial 0 finished with value: 0.8314220183486238 and parameters: {'num_train_epochs': 8, 'learning_rate': 3.1846108373878996e-05, 'alpha': 0.29441369773250325, 'temperature': 23}. Best is trial 0 with value: 0.8314220183486238.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 16405.36it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:01:44,674] Trial 1 finished with value: 0.8038990825688074 and parameters: {'num_train_epochs': 5, 'learning_rate': 0.0007748633451084891, 'alpha': 0.28966767425445883, 'temperature': 22}. Best is trial 0 with value: 0.8314220183486238.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 11323.40it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:04:04,027] Trial 2 finished with value: 0.8096330275229358 and parameters: {'num_train_epochs': 3, 'learning_rate': 5.1848949380749934e-05, 'alpha': 0.7809170083141649, 'temperature': 25}. Best is trial 0 with value: 0.8314220183486238.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 28256.67it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:07:12,162] Trial 3 finished with value: 0.8096330275229358 and parameters: {'num_train_epochs': 4, 'learning_rate': 0.0006596159749447177, 'alpha': 0.6467199263367329, 'temperature': 12}. Best is trial 0 with value: 0.8314220183486238.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 12496.40it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:11:06,654] Trial 4 finished with value: 0.7924311926605505 and parameters: {'num_train_epochs': 5, 'learning_rate': 1.8689764857801264e-05, 'alpha': 0.39756717565520083, 'temperature': 28}. Best is trial 0 with value: 0.8314220183486238.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 9591.76it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:11:53,151] Trial 5 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 9138.43it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:15:47,408] Trial 6 finished with value: 0.8256880733944955 and parameters: {'num_train_epochs': 5, 'learning_rate': 0.00019514510651557203, 'alpha': 0.7167402867995182, 'temperature': 15}. Best is trial 0 with value: 0.8314220183486238.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 8167.46it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:21:16,839] Trial 7 finished with value: 0.8188073394495413 and parameters: {'num_train_epochs': 7, 'learning_rate': 0.0001867248744170336, 'alpha': 0.6635963975873619, 'temperature': 5}. Best is trial 0 with value: 0.8314220183486238.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 13039.29it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:27:35,799] Trial 8 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 10836.56it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:28:23,532] Trial 9 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 10102.39it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:29:10,417] Trial 10 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 9429.21it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:29:57,584] Trial 11 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 15769.58it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:30:44,808] Trial 12 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 9741.42it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:31:31,791] Trial 13 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 13625.81it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:32:18,721] Trial 14 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 10613.67it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:33:05,966] Trial 15 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 10049.63it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:35:27,660] Trial 16 finished with value: 0.8325688073394495 and parameters: {'num_train_epochs': 3, 'learning_rate': 0.00025188557226078285, 'alpha': 0.9323748659008131, 'temperature': 16}. Best is trial 16 with value: 0.8325688073394495.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 12476.38it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:36:15,015] Trial 17 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 12779.52it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:37:50,112] Trial 18 finished with value: 0.8268348623853211 and parameters: {'num_train_epochs': 2, 'learning_rate': 0.00037025746798779346, 'alpha': 0.45866438748848104, 'temperature': 22}. Best is trial 16 with value: 0.8325688073394495.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 10462.96it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:38:37,778] Trial 19 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 9260.52it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:40:59,973] Trial 20 finished with value: 0.8325688073394495 and parameters: {'num_train_epochs': 3, 'learning_rate': 0.0002596144376435558, 'alpha': 0.8816844535222633, 'temperature': 16}. Best is trial 16 with value: 0.8325688073394495.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 9455.91it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:41:46,789] Trial 21 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 2494.06it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:42:34,285] Trial 22 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 17583.34it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:43:21,922] Trial 23 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 8896.39it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:44:57,122] Trial 24 finished with value: 0.8279816513761468 and parameters: {'num_train_epochs': 2, 'learning_rate': 0.0003138834530586035, 'alpha': 0.7441676808541395, 'temperature': 14}. Best is trial 16 with value: 0.8325688073394495.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 8180.12it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:48:07,233] Trial 25 finished with value: 0.8165137614678899 and parameters: {'num_train_epochs': 4, 'learning_rate': 0.0004450736320591505, 'alpha': 0.8436126859858373, 'temperature': 15}. Best is trial 16 with value: 0.8325688073394495.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 13099.85it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:48:54,867] Trial 26 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 5508.04it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:51:17,127] Trial 27 finished with value: 0.8360091743119266 and parameters: {'num_train_epochs': 3, 'learning_rate': 0.00027423186148808275, 'alpha': 0.7409313511123574, 'temperature': 22}. Best is trial 27 with value: 0.8360091743119266.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 10789.38it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:52:52,371] Trial 28 finished with value: 0.8279816513761468 and parameters: {'num_train_epochs': 2, 'learning_rate': 0.00030714951008487906, 'alpha': 0.9761524492364161, 'temperature': 21}. Best is trial 27 with value: 0.8360091743119266.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 9519.75it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:53:39,473] Trial 29 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 8737.20it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:56:48,941] Trial 30 finished with value: 0.8314220183486238 and parameters: {'num_train_epochs': 4, 'learning_rate': 0.00030049534341822015, 'alpha': 0.6669819728655406, 'temperature': 21}. Best is trial 27 with value: 0.8360091743119266.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 10478.37it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:57:36,338] Trial 31 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 6791.69it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 20:58:24,691] Trial 32 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 12552.01it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 21:00:00,022] Trial 33 finished with value: 0.8325688073394495 and parameters: {'num_train_epochs': 2, 'learning_rate': 0.0004978663083375217, 'alpha': 0.8526039315845236, 'temperature': 19}. Best is trial 27 with value: 0.8360091743119266.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 6775.94it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 21:00:47,582] Trial 34 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 7714.12it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 21:02:23,474] Trial 35 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 10183.52it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 21:03:59,278] Trial 36 finished with value: 0.8337155963302753 and parameters: {'num_train_epochs': 2, 'learning_rate': 0.0002840532366230455, 'alpha': 0.6768119669088151, 'temperature': 25}. Best is trial 27 with value: 0.8360091743119266.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 3506.49it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 21:05:34,771] Trial 37 finished with value: 0.8268348623853211 and parameters: {'num_train_epochs': 2, 'learning_rate': 0.0003147592415837873, 'alpha': 0.9156198343915238, 'temperature': 11}. Best is trial 27 with value: 0.8360091743119266.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 10517.45it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 21:06:22,259] Trial 38 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 8709.29it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 21:07:09,987] Trial 39 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 9774.60it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 21:07:57,740] Trial 40 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 9293.14it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 21:08:45,507] Trial 41 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 10729.23it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 21:11:07,957] Trial 42 finished with value: 0.8302752293577982 and parameters: {'num_train_epochs': 3, 'learning_rate': 0.00015561421512371487, 'alpha': 0.8579194276037193, 'temperature': 19}. Best is trial 27 with value: 0.8360091743119266.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 8129.71it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 21:12:42,999] Trial 43 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 16305.61it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 21:14:18,203] Trial 44 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 12183.66it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 21:15:53,429] Trial 45 finished with value: 0.8279816513761468 and parameters: {'num_train_epochs': 2, 'learning_rate': 0.000769728357879761, 'alpha': 0.7212118329256972, 'temperature': 20}. Best is trial 27 with value: 0.8360091743119266.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 11090.78it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 21:16:41,377] Trial 46 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 14157.68it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 21:19:04,933] Trial 47 finished with value: 0.8256880733944955 and parameters: {'num_train_epochs': 3, 'learning_rate': 0.0003398283884630005, 'alpha': 0.8349134377057904, 'temperature': 22}. Best is trial 27 with value: 0.8360091743119266.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 12797.52it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 21:20:40,532] Trial 48 finished with value: 0.8279816513761468 and parameters: {'num_train_epochs': 2, 'learning_rate': 0.00032304100932588825, 'alpha': 0.7621177292647641, 'temperature': 19}. Best is trial 27 with value: 0.8360091743119266.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 9870.74it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-23 21:23:03,696] Trial 49 finished with value: 0.8291284403669725 and parameters: {'num_train_epochs': 3, 'learning_rate': 0.00033075733802282484, 'alpha': 0.7068005769059232, 'temperature': 24}. Best is trial 27 with value: 0.8360091743119266.

BestRun(run_id='27', objective=0.8360091743119266, hyperparameters={'num_train_epochs': 3, 'learning_rate': 0.00027423186148808275, 'alpha': 0.7409313511123574, 'temperature': 22}, run_summary=None)

After finding the best combination we can overwrite hyperparameters .

In [23]:
training_args.save_strategy = "epoch"
training_args.load_best_model_at_end = True

# overwrite initial hyperparameters with from the best_run
for k,v in best_run.hyperparameters.items():
    setattr(training_args, k, v)

# Define a new repository to store our distilled model
best_model_ckpt = "../models/tiny-bert-best"
training_args.output_dir = best_model_ckpt

Now we can start training fine-tuned model.

In [ ]:
# Create a new Trainer with optimal parameters
optimal_trainer = DistillationTrainer(
    student_init(),
    training_args,
    teacher_model=teacher_model,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    data_collator=data_collator,
    processing_class=tokenizer,
    compute_metrics=compute_metrics,
)

optimal_trainer.train()

optimal_trainer.save_model("../models/tiny-bert-best")
tokenizer.save_pretrained("../models/tiny-bert-best")

# save best model, metrics and create model card
optimal_trainer.create_model_card(
    model_name="tiny-bert-sst2",
    finetuned_from="google/bert_uncased_L-2_H-128_A-2",
    dataset="nyu-mll/glue",
    dataset_args="sst2",
    tasks="text-classification",
)

Loading weights: 100%|██████████| 39/39 [00:00<00:00, 16611.95it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 116.33it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 165.31it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 158.57it/s]