# Task-specific distillation for BERT
Link:
- https://www.philschmid.de/knowledge-distillation-bert-transformers

This is an end-to-end task-specific knowledge distillation text-classification example. Here we'll be using Transformers and PyTorch.

Distillation is the process of training a small "student" model to mimic a larger "teacher" model. 

In this example, we will use a [BERT-base](https://huggingface.co/textattack/bert-base-uncased-SST-2) as Teacher (~109 M) and [BERT-Tiny](https://huggingface.co/google/bert_uncased_L-2_H-128_A-2) (4.4 M) as Student. We will use [Text-Classification](https://huggingface.co/tasks/text-classification) as our task-specific knowledge distillation task and the [Stanford Sentiment Treebank v2 (SST-2)](https://huggingface.co/datasets/stanfordnlp/sst2) dataset for training.

They are two different types of knowledge distillation, the Task-agnostic knowledge distillation (right) and the Task-specific knowledge distillation (left). In this example we are going to use the Task-specific knowledge distillation.

In Task-specific knowledge distillation a "second step of distillation" is used to "fine-tune" the model on a given dataset. This idea comes from the [DistilBERT](https://arxiv.org/abs/1910.01108) paper where it was shown that a student performed better than simply finetuning the distilled language model.

## Installation

In [1]:
%pip install transformers==5.20.2 datasets==5.1.0 tensorboard==2.21.0
%pip install accelerate==1.15.0
# run in terminal:
# !sudo apt-get install git-lfs
# or
# brew install git-lfs
# git lfs install

Requirement already satisfied: transformers==5.20.2 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (5.20.2)
Requirement already satisfied: datasets==5.1.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (5.1.0)
Requirement already satisfied: tensorboard==2.21.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (2.21.0)
Requirement already satisfied: huggingface-hub<3.0,>=1.31.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from transformers==5.20.2) (1.33.0)
Requirement already satisfied: numpy>=1.17 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from transformers==5.20.2) (2.5.2)
Requirement already satisfied: packaging>=20.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from transformers==5.20.2) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from transformers==5.20.2) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from transformers==5.20.2) (2026.9.29)
Requirement already satisfied: tokenizers<0.24.0,>=0.23.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from transformers==5.20.2) (0.23.3)
Requirement already satisfied: typer in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from transformers==5.20.2) (0.27.3)
Requirement already satisfied: safetensors>=0.8.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from transformers==5.20.2) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from transformers==5.20.2) (4.70.1)
Requirement already satisfied: filelock in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from datasets==5.1.0) (4.2.4)
Requirement already satisfied: pyarrow>=24.0.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from datasets==5.1.0) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from datasets==5.1.0) (0.4.1)
Requirement already satisfied: pandas in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from datasets==5.1.0) (3.0.5)
Requirement already satisfied: xxhash in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from datasets==5.1.0) (4.0.2)
Requirement already satisfied: multiprocess<0.70.20 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from datasets==5.1.0) (0.70.19)
Requirement already satisfied: fsspec<=2026.7.0,>=2023.1.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from fsspec[http]<=2026.7.0,>=2023.1.0->datasets==5.1.0) (2026.6.0)
Requirement already satisfied: absl-py>=0.4 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from tensorboard==2.21.0) (2.5.1)
Requirement already satisfied: grpcio<2.0,>=1.74.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from tensorboard==2.21.0) (1.84.1)
Requirement already satisfied: markdown>=2.6.8 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from tensorboard==2.21.0) (3.11.2)
Requirement already satisfied: pillow in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from tensorboard==2.21.0) (12.3.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from tensorboard==2.21.0) (7.36.2)
Requirement already satisfied: setuptools>=41.0.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from tensorboard==2.21.0) (84.2.1)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from tensorboard==2.21.0) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from tensorboard==2.21.0) (3.1.9)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from fsspec[http]<=2026.7.0,>=2023.1.0->datasets==5.1.0) (3.14.5)
Requirement already satisfied: typing-extensions~=4.12 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from grpcio<2.0,>=1.74.0->tensorboard==2.21.0) (4.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from huggingface-hub<3.0,>=1.31.0->transformers==5.20.2) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from huggingface-hub<3.0,>=1.31.0->transformers==5.20.2) (1.7.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from huggingface-hub<3.0,>=1.31.0->transformers==5.20.2) (0.28.1)
Requirement already satisfied: markupsafe>=2.1.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from werkzeug>=1.0.1->tensorboard==2.21.0) (3.0.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from pandas->datasets==5.1.0) (3.0.0)
Requirement already satisfied: shellingham>=1.3.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from typer->transformers==5.20.2) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from typer->transformers==5.20.2) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from typer->transformers==5.20.2) (0.0.5)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets==5.1.0) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets==5.1.0) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets==5.1.0) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets==5.1.0) (1.8.0)
Requirement already satisfied: multidict<8.0,>=4.5 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets==5.1.0) (7.1.0)
Requirement already satisfied: propcache>=0.2.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets==5.1.0) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.25.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets==5.1.0) (1.25.1)
Requirement already satisfied: anyio in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers==5.20.2) (4.15.1)
Requirement already satisfied: certifi in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers==5.20.2) (2026.10.19)
Requirement already satisfied: httpcore==1.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers==5.20.2) (1.0.9)
Requirement already satisfied: idna in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers==5.20.2) (3.20)
Requirement already satisfied: h11>=0.16 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers==5.20.2) (0.16.0)
Requirement already satisfied: six>=1.6 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->datasets==5.1.0) (1.17.0)
Requirement already satisfied: tzdata in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->datasets==5.1.0) (2026.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from rich>=13.8.0->typer->transformers==5.20.2) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from rich>=13.8.0->typer->transformers==5.20.2) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers==5.20.2) (0.1.2)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: accelerate==1.15.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (1.15.0)
Requirement already satisfied: numpy>=1.17 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from accelerate==1.15.0) (2.5.2)
Requirement already satisfied: packaging>=20.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from accelerate==1.15.0) (26.3)
Requirement already satisfied: psutil in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from accelerate==1.15.0) (7.2.2)
Requirement already satisfied: pyyaml in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from accelerate==1.15.0) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from accelerate==1.15.0) (2.14.0)
Requirement already satisfied: huggingface_hub>=0.21.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from accelerate==1.15.0) (1.33.0)
Requirement already satisfied: safetensors>=0.4.3 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from accelerate==1.15.0) (0.8.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate==1.15.0) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate==1.15.0) (4.2.4)
Requirement already satisfied: fsspec>=2023.5.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate==1.15.0) (2026.6.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate==1.15.0) (1.7.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate==1.15.0) (0.28.1)
Requirement already satisfied: tqdm>=4.42.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate==1.15.0) (4.70.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate==1.15.0) (4.16.0)
Requirement already satisfied: setuptools>=77.0.3 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate==1.15.0) (84.2.1)
Requirement already satisfied: sympy>=1.13.3 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate==1.15.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate==1.15.0) (3.7)
Requirement already satisfied: jinja2 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate==1.15.0) (3.1.6)
Requirement already satisfied: cuda-toolkit==13.0.3 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate==1.15.0) (13.0.3.0)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate==1.15.0) (13.4.4)
Requirement already satisfied: nvidia-cudnn-cu13==9.24.0.43 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate==1.15.0) (9.24.0.43)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate==1.15.0) (0.8.1)
Requirement already satisfied: nvidia-nccl-cu13==2.30.7 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate==1.15.0) (2.30.7)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate==1.15.0) (3.4.5)
Requirement already satisfied: triton~=3.8.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate==1.15.0) (3.8.0)
Requirement already satisfied: nvidia-cublas==13.1.1.3.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate==1.15.0) (13.1.1.3)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate==1.15.0) (13.0.88)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate==1.15.0) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate==1.15.0) (12.0.0.61)
Requirement already satisfied: nvidia-nvjitlink<14,>=13.0.88 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate==1.15.0) (13.4.92)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate==1.15.0) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate==1.15.0) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate==1.15.0) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate==1.15.0) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate==1.15.0) (12.6.3.3)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate==1.15.0) (13.0.85)
Requirement already satisfied: cuda-pathfinder>=1.4.2 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-bindings<14,>=13.0.3->torch>=2.0.0->accelerate==1.15.0) (1.8.4)
Requirement already satisfied: anyio in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate==1.15.0) (4.15.1)
Requirement already satisfied: certifi in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate==1.15.0) (2026.10.19)
Requirement already satisfied: httpcore==1.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate==1.15.0) (1.0.9)
Requirement already satisfied: idna in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate==1.15.0) (3.20)
Requirement already satisfied: h11>=0.16 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate==1.15.0) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate==1.15.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from jinja2->torch>=2.0.0->accelerate==1.15.0) (3.0.4)
Note: you may need to restart the kernel to use updated packages.

## Setup and configuration
In this example, we will use BERT-base as Teacher and BERT-Tiny as Student. Our Teacher is already fine-tuned on our dataset, which makes it easy for us to directly start the distillation training job rather than fine-tuning the teacher first to then distill it afterwards.

*IMPORTANT: This example will only work with a Teacher & Student combination where the Tokenizer is creating the same output.*

In [2]:
student_id = "google/bert_uncased_L-2_H-128_A-2"
teacher_id = "textattack/bert-base-uncased-SST-2"

In [3]:
from transformers import AutoTokenizer

/home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Here we check, that teacher and student divide identical text into the same tokens. Otherwise it won'r work.

In [4]:
# init tokenizer
teacher_tokenizer = AutoTokenizer.from_pretrained(teacher_id)
student_tokenizer = AutoTokenizer.from_pretrained(student_id)
 
# sample input
sample = "This is a basic example, with different words to test."
 
# assert results
assert teacher_tokenizer(sample) == student_tokenizer(sample), "Tokenizers haven't created the same output"

## Dataset and pre-processing

As Dataset we will use the [Stanford Sentiment Treebank v2 (SST-2)](https://huggingface.co/datasets/stanfordnlp/sst2) a text-classification for `sentiment-analysis`, which is included in the [GLUE benchmark](https://gluebenchmark.com/). The dataset is based on the dataset introduced by Pang and Lee (2005) and consists of 11,855 single sentences extracted from movie reviews. It was parsed with the Stanford parser and includes a total of 215,154 unique phrases from those parse trees, each annotated by 3 human judges. It uses the two-way (positive/negative) class split, with only sentence-level labels.

In [5]:
from datasets import load_dataset
from transformers import AutoTokenizer

In [6]:
dataset_id="nyu-mll/glue"
dataset_config="sst2"

In [7]:
dataset = load_dataset(dataset_id,dataset_config)

### Pre-processing & Tokenization

To distill our model we need to convert our "Natural Language" to token IDs.

We are going to use the tokenizer of the Teacher, though we could also go with the Student tokenizer.

In [8]:

tokenizer = AutoTokenizer.from_pretrained(teacher_id)

Additionally we add the `truncation=True` and `max_length=512` to align the length and truncate texts that are bigger than the maximum size allowed by the model.

In [9]:
def process(examples):
    tokenized_inputs = tokenizer(
        examples["sentence"], truncation=True, max_length=512
    )
    return tokenized_inputs

In [10]:
tokenized_datasets = dataset.map(process, batched=True)
tokenized_datasets = tokenized_datasets.rename_column("label","labels")
 
tokenized_datasets["test"].features

{'sentence': Value('string'),
 'labels': ClassLabel(names=['negative', 'positive']),
 'idx': Value('int32'),
 'input_ids': List(Value('int32')),
 'token_type_ids': List(Value('int8')),
 'attention_mask': List(Value('int8'))}

### Train split

Ten percent of the SST-2 train split is held out for hyperparameter search and the `alpha=1` comparison. Final models train on the other 90% only. The original validation split is reserved for the reported metrics.

In [11]:
parts = tokenized_datasets["train"].train_test_split(
    test_size=0.1,
    seed=33,
    stratify_by_column="labels",
)
fit_dataset = parts["train"]
selection_dataset = parts["test"]
print(len(fit_dataset), len(selection_dataset), len(tokenized_datasets["validation"]))

60614 6735 872

`input_ids` -- stores tokenized sentences.

## Distilling the model using PyTorch and DistillationTrainer
Now that our `dataset` is processed, we can distill it. Normally, when fine-tuning a transformer model using PyTorch you should go with the `Trainer-API`. The [Trainer](https://huggingface.co/docs/transformers/v4.16.1/en/main_classes/trainer#transformers.Trainer) class provides an API for feature-complete training in PyTorch for most standard use cases.

In our example we cannot use the `Trainer` out-of-the-box, since we need to pass in two models, the `Teacher` and the `Student` and compute the loss for both. But we can subclass the `Trainer` to create a `DistillationTrainer` which will take care of it and only overwrite the [compute_loss](https://github.com/huggingface/transformers/blob/c4ad38e5ac69e6d96116f39df789a2369dd33c21/src/transformers/trainer.py#L1962) method as well as the `init` method. In addition to this we also need to subclass the `TrainingArguments` to include the our distillation hyperparameters.

In [12]:
from transformers import TrainingArguments, Trainer
import torch
import torch.nn as nn
import torch.nn.functional as F
from transformers import AutoModelForSequenceClassification, DataCollatorWithPadding

In [13]:
class DistillationTrainingArguments(TrainingArguments):
    def __init__(self, *args, alpha=0.5, temperature=2.0, **kwargs):
        super().__init__(*args, **kwargs)
 
        self.alpha = alpha # to include two losses equally: 
                            # real label of sst and how much 
                            # distributions of student and teacher differ
        self.temperature = temperature # 2.0 by default 
                                        # logits are dividet by this value
                                        # student studies how confident was the teacher
        # because TrainingArguments does not have those args

class DistillationTrainer(Trainer):
    def __init__(self, *args, teacher_model=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.teacher = teacher_model # adding teacher into the trainer
        # place teacher on same device as student
        self._move_model_to_device(self.teacher,self.model.device) # placing teacher on the same device 
                                                                    # so comparison of logits is valid
        self.teacher.eval() # turn on evaluation regime: no dropout, same logits for the same sentence;
                            # weights are not updated, it also does not get into the optimiser


    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
 
        # compute student output
        outputs_student = model(**inputs)
        student_loss=outputs_student.loss # cross-entropy loss
        # compute teacher output
        with torch.no_grad(): # weights are not being updated
          outputs_teacher = self.teacher(**inputs)
 
        # assert size
        assert outputs_student.logits.size() == outputs_teacher.logits.size()
 
        # Soften probabilities and compute distillation loss
        loss_function = nn.KLDivLoss(reduction="batchmean") 
        loss_logits = (loss_function(
            F.log_softmax(outputs_student.logits / self.args.temperature, dim=-1),
            F.softmax(outputs_teacher.logits / self.args.temperature, dim=-1)) * (self.args.temperature ** 2)) 
                                                                                # multiplication for scaling
        # Return weighted student loss
        loss = self.args.alpha * student_loss + (1. - self.args.alpha) * loss_logits
        return (loss, outputs_student) if return_outputs else loss

Kullback-Leibler loss (`KLDivLoss`):
- how much student's distributtion differs from teacher's
- teacher_p * log(teacher_p / student_p)

`reduction="batchmean"` averages those sums per batch:
$$\frac{1}{m}\sum^m_1(p_T(neg)\log(\frac{p_T(neg)}{p_S(neg)})+p_T(pos)\log(\frac{p_T(pos)}{p_S(pos)}))$$

### Hyperparameter Definition, Model Loading

In [14]:
# create label2id, id2label dicts for nice outputs for the model
labels = tokenized_datasets["train"].features["labels"].names
num_labels = len(labels)
label2id, id2label = dict(), dict()
for i, label in enumerate(labels):
    label2id[label] = str(i)
    id2label[str(i)] = label
 
output_dir = "../models/tiny-bert-sst2"

# define training args
training_args = DistillationTrainingArguments(
    output_dir=output_dir,
    num_train_epochs=7, # n of epoch for whole train-split
    per_device_train_batch_size=128, # how many sentences per step
    per_device_eval_batch_size=128,
    fp16=torch.cuda.is_available(), # mixed precision only on CUDA
    learning_rate=6e-5, # optimiser's step
    seed=33,

    # logging & evaluation strategies
    logging_strategy="epoch", # to get more information to TensorBoard
    eval_strategy="epoch", # accuracy for validation
    save_strategy="epoch", 
    save_total_limit=2, # n of last checkpoints
    load_best_model_at_end=True, 
    metric_for_best_model="accuracy",
    report_to="tensorboard",

    # distilation parameters
    alpha=0.5,
    temperature=4.0
    )
 
# define data_collator
data_collator = DataCollatorWithPadding(tokenizer=tokenizer) # padding fot too short sentences
 
# define model
teacher_model = AutoModelForSequenceClassification.from_pretrained(
    teacher_id,
    num_labels=num_labels,
    id2label=id2label,
    label2id=label2id,
)
 
# define student model
student_model = AutoModelForSequenceClassification.from_pretrained(
    student_id,
    num_labels=num_labels,
    id2label=id2label,
    label2id=label2id,
)

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 65262.05it/s]
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 5468.27it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [15]:
print(training_args.device)

cuda:0

In [16]:
teacher_model.save_pretrained("../models/bert-base-sst2-teacher")
tokenizer.save_pretrained("../models/bert-base-sst2-teacher")

Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 14.25it/s]

('../models/bert-base-sst2-teacher/tokenizer_config.json',
 '../models/bert-base-sst2-teacher/tokenizer.json')

### Evaluation metric

In [17]:
import numpy as np

In [18]:
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    return {"accuracy": (predictions == labels).mean().item()}

### Training

In [19]:
trainer = DistillationTrainer(
    student_model,
    training_args,
    teacher_model=teacher_model,
    train_dataset=fit_dataset,
    eval_dataset=selection_dataset,
    data_collator=data_collator,
    processing_class=tokenizer,
    compute_metrics=compute_metrics,
)

In [20]:
trainer.train()

Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 93.59it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 167.63it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 98.99it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 174.75it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 173.34it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 165.80it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 167.77it/s]

TrainOutput(global_step=3318, training_loss=0.7410370342123573, metrics={'train_runtime': 284.9268, 'train_samples_per_second': 1489.148, 'train_steps_per_second': 11.645, 'total_flos': 50853794675760.0, 'train_loss': 0.7410370342123573, 'epoch': 7.0})

This first run only checks that distillation trains. It uses 90% of the SST-2 train split and is scored on the held-out 10%. The reported numbers are printed later, on the original validation split: the teacher, the distilled student, and the `alpha=1` control.

### Hyperparameter Search for Distillation parameter alpha & temperature with optuna
The parameter `alpha` & `temparature` in the `DistillationTrainer` can also be used when doing Hyperparamter search to maxizime our "knowledge extraction". As Hyperparamter Optimization framework are we using [Optuna](https://optuna.org/), which has an integration into the Trainer-API. Since the DistillationTrainer is a sublcass of the Trainer we can use the hyperparameter_search without any code changes.

In [21]:
%pip install optuna==5.0.0

Requirement already satisfied: optuna==5.0.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (5.0.0)
Requirement already satisfied: alembic>=1.5.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from optuna==5.0.0) (1.20.1)
Requirement already satisfied: colorlog in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from optuna==5.0.0) (6.12.0)
Requirement already satisfied: numpy in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from optuna==5.0.0) (2.5.2)
Requirement already satisfied: packaging>=20.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from optuna==5.0.0) (26.3)
Requirement already satisfied: sqlalchemy>=1.4.2 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from optuna==5.0.0) (2.1.6)
Requirement already satisfied: tqdm in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from optuna==5.0.0) (4.70.1)
Requirement already satisfied: PyYAML in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from optuna==5.0.0) (6.0.3)
Requirement already satisfied: Mako in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from alembic>=1.5.0->optuna==5.0.0) (1.4.3)
Requirement already satisfied: typing-extensions>=4.12 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from alembic>=1.5.0->optuna==5.0.0) (4.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from Mako->alembic>=1.5.0->optuna==5.0.0) (3.0.4)
Note: you may need to restart the kernel to use updated packages.

To do optimisation we need to define hyperparameter space.

In [22]:
def hp_space(trial):
    return {
        "num_train_epochs": trial.suggest_int("num_train_epochs", 2, 10),
        "learning_rate": trial.suggest_float("learning_rate", 1e-5, 1e-3 ,log=True),
        "alpha": trial.suggest_float("alpha", 0, 1),
        "temperature": trial.suggest_int("temperature", 2, 30),
        }

In [23]:
def student_init():
    return AutoModelForSequenceClassification.from_pretrained(
        student_id,
        num_labels=num_labels,
        id2label=id2label,
        label2id=label2id
    )

training_args.output_dir = "../models/tiny-bert-hpo"
training_args.save_strategy = "no"
training_args.load_best_model_at_end = False

trainer = DistillationTrainer(
    model_init=student_init,
    args=training_args,
    teacher_model=teacher_model,
    train_dataset=fit_dataset,
    eval_dataset=selection_dataset,
    data_collator=data_collator,
    processing_class=tokenizer,
    compute_metrics=compute_metrics,
)
best_run = trainer.hyperparameter_search(
    n_trials=50,
    direction="maximize",
    hp_space=hp_space
)

print(best_run)

Loading weights: 100%|██████████| 39/39 [00:00<00:00, 10564.32it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
[I 2026-10-25 11:45:44,206] A new study created in memory with name: no-name-3d2b03e4-b384-4ce1-ad64-5ffed16dfb94
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 7545.10it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 11:51:24,246] Trial 0 finished with value: 0.927691165553081 and parameters: {'num_train_epochs': 8, 'learning_rate': 0.00010431534209871124, 'alpha': 0.6054179749517107, 'temperature': 18}. Best is trial 0 with value: 0.927691165553081.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 14114.92it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 11:55:03,444] Trial 1 finished with value: 0.8556792873051225 and parameters: {'num_train_epochs': 5, 'learning_rate': 2.0984583991949252e-05, 'alpha': 0.3644675284947123, 'temperature': 29}. Best is trial 0 with value: 0.927691165553081.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 19727.19it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 11:58:43,914] Trial 2 finished with value: 0.8197475872308835 and parameters: {'num_train_epochs': 5, 'learning_rate': 1.1086571931113778e-05, 'alpha': 0.7559374378904261, 'temperature': 4}. Best is trial 0 with value: 0.927691165553081.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 18856.24it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 12:00:12,610] Trial 3 finished with value: 0.7867854491462509 and parameters: {'num_train_epochs': 2, 'learning_rate': 1.805688980253173e-05, 'alpha': 0.2870846549275061, 'temperature': 30}. Best is trial 0 with value: 0.927691165553081.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 8820.59it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 12:07:37,203] Trial 4 finished with value: 0.9346696362286563 and parameters: {'num_train_epochs': 10, 'learning_rate': 0.00011927173464498794, 'alpha': 0.43713774289007157, 'temperature': 28}. Best is trial 4 with value: 0.9346696362286563.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 14831.61it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 12:11:20,993] Trial 5 finished with value: 0.9374907201187824 and parameters: {'num_train_epochs': 5, 'learning_rate': 0.00042134623590159374, 'alpha': 0.7036838083776481, 'temperature': 14}. Best is trial 5 with value: 0.9374907201187824.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 19314.90it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 12:18:49,312] Trial 6 finished with value: 0.9382331106161841 and parameters: {'num_train_epochs': 10, 'learning_rate': 0.0008433210815094049, 'alpha': 0.754995063852233, 'temperature': 24}. Best is trial 6 with value: 0.9382331106161841.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 22015.86it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 12:22:33,866] Trial 7 finished with value: 0.9287305122494433 and parameters: {'num_train_epochs': 5, 'learning_rate': 0.0002287807714981694, 'alpha': 0.8377089735726369, 'temperature': 3}. Best is trial 6 with value: 0.9382331106161841.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 8344.11it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 12:23:18,746] Trial 8 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 9863.00it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 12:30:03,306] Trial 9 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 13032.02it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 12:36:47,488] Trial 10 finished with value: 0.9429844097995546 and parameters: {'num_train_epochs': 9, 'learning_rate': 0.0007073401280119382, 'alpha': 0.46270781717606, 'temperature': 7}. Best is trial 10 with value: 0.9429844097995546.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 9249.00it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 12:43:33,984] Trial 11 finished with value: 0.9444691907943579 and parameters: {'num_train_epochs': 9, 'learning_rate': 0.0007073176295428896, 'alpha': 0.3184480727663615, 'temperature': 6}. Best is trial 11 with value: 0.9444691907943579.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 11773.27it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 12:48:46,911] Trial 12 finished with value: 0.9403118040089087 and parameters: {'num_train_epochs': 7, 'learning_rate': 0.0009489991253073501, 'alpha': 0.40404883320875506, 'temperature': 4}. Best is trial 11 with value: 0.9444691907943579.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 8780.82it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 12:56:17,828] Trial 13 finished with value: 0.9434298440979956 and parameters: {'num_train_epochs': 10, 'learning_rate': 0.0004980376497245734, 'alpha': 0.028595202115268448, 'temperature': 9}. Best is trial 11 with value: 0.9444691907943579.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 13047.61it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 12:58:34,065] Trial 14 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 14830.27it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 12:59:19,396] Trial 15 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 9937.90it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 13:03:49,227] Trial 16 finished with value: 0.9432813659985152 and parameters: {'num_train_epochs': 6, 'learning_rate': 0.0008465692582762986, 'alpha': 0.0731480950324882, 'temperature': 6}. Best is trial 11 with value: 0.9444691907943579.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 10333.41it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 13:04:33,893] Trial 17 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 19534.02it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 13:10:31,763] Trial 18 finished with value: 0.9444691907943579 and parameters: {'num_train_epochs': 8, 'learning_rate': 0.0006131713170451023, 'alpha': 0.15816687640082125, 'temperature': 16}. Best is trial 11 with value: 0.9444691907943579.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 15284.79it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 13:16:29,500] Trial 19 finished with value: 0.9453600593912398 and parameters: {'num_train_epochs': 8, 'learning_rate': 0.0008258879417208129, 'alpha': 0.008291728921826391, 'temperature': 16}. Best is trial 19 with value: 0.9453600593912398.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 14870.71it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 13:17:14,709] Trial 20 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 7405.40it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 13:23:13,342] Trial 21 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 11527.69it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 13:23:58,646] Trial 22 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 12253.94it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 13:28:27,255] Trial 23 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 11704.20it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 13:29:12,968] Trial 24 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 4102.06it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 13:35:57,542] Trial 25 finished with value: 0.9434298440979956 and parameters: {'num_train_epochs': 9, 'learning_rate': 0.0006714581978831489, 'alpha': 0.28848538113837335, 'temperature': 19}. Best is trial 19 with value: 0.9453600593912398.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 15713.53it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 13:38:12,634] Trial 26 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 15274.80it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 13:42:42,359] Trial 27 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 9446.63it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 13:47:11,134] Trial 28 finished with value: 0.9423904974016333 and parameters: {'num_train_epochs': 6, 'learning_rate': 0.000544838005368319, 'alpha': 0.142323077569008, 'temperature': 19}. Best is trial 19 with value: 0.9453600593912398.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 9526.40it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 13:50:09,961] Trial 29 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 14885.60it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 13:50:55,168] Trial 30 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 10070.05it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 13:51:40,625] Trial 31 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 14807.45it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 13:52:25,607] Trial 32 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 7892.02it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 13:56:55,417] Trial 33 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 8957.77it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 13:59:54,836] Trial 34 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 8441.86it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 14:02:09,942] Trial 35 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 4070.62it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 14:02:55,346] Trial 36 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 22036.62it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 14:03:40,281] Trial 37 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 12087.33it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 14:04:25,711] Trial 38 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 12405.42it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 14:08:55,123] Trial 39 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 11427.02it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 14:09:40,525] Trial 40 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 10073.77it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 14:15:43,619] Trial 41 finished with value: 0.9450631031922792 and parameters: {'num_train_epochs': 8, 'learning_rate': 0.0008124823223201345, 'alpha': 0.07127220536290968, 'temperature': 11}. Best is trial 19 with value: 0.9453600593912398.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 11027.23it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 14:17:14,407] Trial 42 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 14505.44it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 14:18:45,051] Trial 43 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 9374.63it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 14:24:45,876] Trial 44 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 7244.05it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 14:26:16,275] Trial 45 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 14685.15it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 14:27:02,203] Trial 46 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 11915.64it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 14:27:47,602] Trial 47 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 10088.68it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 14:28:32,996] Trial 48 pruned.
Loading weights: 100%|██████████| 39/39 [00:00<00:00, 12175.50it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[I 2026-10-25 14:33:03,974] Trial 49 pruned.

BestRun(run_id='19', objective=0.9453600593912398, hyperparameters={'num_train_epochs': 8, 'learning_rate': 0.0008258879417208129, 'alpha': 0.008291728921826391, 'temperature': 16}, run_summary=None)

After finding the best combination we can overwrite hyperparameters .

In [24]:
training_args.save_strategy = "epoch"
training_args.load_best_model_at_end = True

# overwrite initial hyperparameters with from the best_run
for k,v in best_run.hyperparameters.items():
    setattr(training_args, k, v)

# Define a new repository to store our distilled model
best_model_ckpt = "../models/tiny-bert-best"
training_args.output_dir = best_model_ckpt

### Selection scores

Optuna scores each trial on the 10% selection slice. The control uses that best trial's `num_train_epochs`, `learning_rate`, and `temperature`, with `alpha=1` (cross-entropy only, no distillation). Both scores below are last-epoch accuracy on the selection slice, which is the quantity Optuna maximises. The original validation split is not used here.

In [25]:
import copy

selection_distill_accuracy = best_run.objective

control_args = copy.copy(training_args)
control_args.alpha = 1.0
control_args.output_dir = "../models/tiny-bert-alpha1-selection"
control_args.save_strategy = "no"
control_args.load_best_model_at_end = False

control_trainer = DistillationTrainer(
    student_init(),
    control_args,
    teacher_model=teacher_model,
    train_dataset=fit_dataset,
    eval_dataset=selection_dataset,
    data_collator=data_collator,
    processing_class=tokenizer,
    compute_metrics=compute_metrics,
)
control_trainer.train()
selection_control_accuracy = control_trainer.evaluate()["eval_accuracy"]

print("selection distill", selection_distill_accuracy)
print("selection alpha=1", selection_control_accuracy)

Loading weights: 100%|██████████| 39/39 [00:00<00:00, 11993.39it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

selection distill 0.9453600593912398
selection alpha=1 0.9278396436525612

### Validation scores

These three numbers are the reported result. Both students train on the other 90% of the train split. The printed student accuracy is the best checkpoint on the original validation split (`metric_for_best_model="accuracy"`), and that checkpoint stays loaded. The teacher is only evaluated.

In [26]:
import copy

final_trainer = DistillationTrainer(
    student_init(),
    training_args,
    teacher_model=teacher_model,
    train_dataset=fit_dataset,
    eval_dataset=tokenized_datasets["validation"],
    data_collator=data_collator,
    processing_class=tokenizer,
    compute_metrics=compute_metrics,
)
final_trainer.train()

def best_accuracy_row(trainer):
    rows = [row for row in trainer.state.log_history if "eval_accuracy" in row]
    return max(rows, key=lambda row: row["eval_accuracy"])

distill_best = best_accuracy_row(final_trainer)
print(
    "distilled validation accuracy",
    distill_best["eval_accuracy"],
    "epoch",
    distill_best["epoch"],
)

final_control_args = copy.copy(training_args)
final_control_args.alpha = 1.0
final_control_args.output_dir = "../models/tiny-bert-alpha1"
final_control = DistillationTrainer(
    student_init(),
    final_control_args,
    teacher_model=teacher_model,
    train_dataset=fit_dataset,
    eval_dataset=tokenized_datasets["validation"],
    data_collator=data_collator,
    processing_class=tokenizer,
    compute_metrics=compute_metrics,
)
final_control.train()
control_best = best_accuracy_row(final_control)
print(
    "alpha=1 validation accuracy",
    control_best["eval_accuracy"],
    "epoch",
    control_best["epoch"],
)

teacher_eval = Trainer(
    teacher_model,
    args=training_args,
    eval_dataset=tokenized_datasets["validation"],
    data_collator=data_collator,
    processing_class=tokenizer,
    compute_metrics=compute_metrics,
)
print("teacher validation", teacher_eval.evaluate())

final_trainer.save_model("../models/tiny-bert-best")
tokenizer.save_pretrained("../models/tiny-bert-best")

# The generated card takes its headline from the last eval row. Append the
# loaded checkpoint so that headline is the best validation accuracy.
final_trainer.state.log_history.append(dict(distill_best))
final_trainer.create_model_card(
    model_name="tiny-bert-sst2",
    finetuned_from="google/bert_uncased_L-2_H-128_A-2",
    dataset="nyu-mll/glue",
    dataset_args="sst2",
    tasks="text-classification",
)

Loading weights: 100%|██████████| 39/39 [00:00<00:00, 8628.43it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 91.85it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 164.48it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 163.69it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 160.49it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 170.20it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 160.30it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 158.19it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 162.97it/s]

distilled validation accuracy 0.8165137614678899 epoch 7.0

Loading weights: 100%|██████████| 39/39 [00:00<00:00, 8257.75it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 161.08it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 164.22it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 162.24it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 160.72it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 163.19it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 161.90it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 171.08it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 165.57it/s]

alpha=1 validation accuracy 0.805045871559633 epoch 1.0

teacher validation {'eval_loss': 0.28186291456222534, 'eval_accuracy': 0.9243119266055045}

Writing model shards: 100%|██████████| 1/1 [00:00<00:00, 161.62it/s]