# Quantization intro

This notebook focuses on post-training quantization methods for Google Gemma 3 model with 270m parameters.

Post-training model quantization is a technique that converts a pre-trained neural network from high-precision floating-point formats into lower-precision representations after training is already complete. For the validation of the methods was used an `XLSum` dataset and `c4` (Ukrainian) for calibration of GPTQ and AWQ methods. Metrics used in model evaluation - loss and ROUGE (1, 2, L).

## Installation

In [1]:
%pip install -U transformers accelerate datasets huggingface_hub llmcompressor hqq bitsandbytes rouge-score

Requirement already satisfied: transformers in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (5.17.0)
Collecting transformers
  Using cached transformers-5.20.2-py3-none-any.whl.metadata (31 kB)
Requirement already satisfied: accelerate in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (1.15.0)
Requirement already satisfied: datasets in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (5.1.0)
Requirement already satisfied: huggingface_hub in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (1.33.0)
Collecting huggingface_hub
  Using cached huggingface_hub-2.3.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: llmcompressor in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (0.14.0.1)
Requirement already satisfied: hqq in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (0.2.8.post1)
Requirement already satisfied: bitsandbytes in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (0.50.2)
Requirement already satisfied: rouge-score in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (0.1.2)
Requirement already satisfied: numpy>=1.17 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from transformers) (2.5.2)
Requirement already satisfied: packaging>=20.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from transformers) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from transformers) (2026.9.29)
Requirement already satisfied: tokenizers<0.24.0,>=0.23.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from transformers) (0.23.3)
Requirement already satisfied: typer in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from transformers) (0.27.3)
Requirement already satisfied: safetensors>=0.8.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from transformers) (4.70.1)
Requirement already satisfied: psutil in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from accelerate) (7.2.2)
Requirement already satisfied: torch>=2.0.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from accelerate) (2.14.0)
Requirement already satisfied: filelock in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from datasets) (4.2.4)
Requirement already satisfied: pyarrow>=24.0.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from datasets) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from datasets) (3.0.5)
Requirement already satisfied: xxhash in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from datasets) (4.0.2)
Requirement already satisfied: multiprocess<0.70.20 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.7.0,>=2023.1.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (2026.6.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from huggingface_hub) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from huggingface_hub) (1.7.0)
Requirement already satisfied: httpx2<3,>=2.0.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from huggingface_hub) (2.16.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from huggingface_hub) (4.16.0)
Requirement already satisfied: loguru>=0.7.2 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from llmcompressor) (0.7.3)
Requirement already satisfied: requests>=2.32.2 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from llmcompressor) (2.34.2)
Requirement already satisfied: auto-round<=0.15.1,>=0.14.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from llmcompressor) (0.15.1)
Requirement already satisfied: nvidia-ml-py>=12.560.30 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from llmcompressor) (13.615.71)
Requirement already satisfied: pillow>=10.4.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from llmcompressor) (12.3.0)
Requirement already satisfied: compressed-tensors==0.19.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from llmcompressor) (0.19.0)
Requirement already satisfied: pydantic>=2.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from compressed-tensors==0.19.0->llmcompressor) (2.14.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: einops in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from hqq) (0.8.2)
Requirement already satisfied: termcolor in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from hqq) (3.3.0)
Requirement already satisfied: absl-py in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from rouge-score) (2.5.1)
Requirement already satisfied: nltk in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from rouge-score) (3.10.4)
Requirement already satisfied: six>=1.14.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from rouge-score) (1.17.0)
Requirement already satisfied: py-cpuinfo in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from auto-round<=0.15.1,>=0.14.1->llmcompressor) (9.0.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (3.14.5)
Requirement already satisfied: anyio in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.15.1)
Requirement already satisfied: certifi in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub) (2026.10.19)
Requirement already satisfied: httpcore==1.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: idna in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.20)
Requirement already satisfied: h11>=0.16 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from requests>=2.32.2->llmcompressor) (3.5.2)
Requirement already satisfied: urllib3<3,>=1.26 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from requests>=2.32.2->llmcompressor) (2.8.0)
Requirement already satisfied: setuptools>=77.0.3 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (84.2.1)
Requirement already satisfied: sympy>=1.13.3 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (3.7)
Requirement already satisfied: jinja2 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-toolkit==13.0.3 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.0.3.0)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (13.4.4)
Requirement already satisfied: nvidia-cudnn-cu13==9.24.0.43 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (9.24.0.43)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (0.8.1)
Requirement already satisfied: nvidia-nccl-cu13==2.30.7 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (2.30.7)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: triton~=3.8.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (3.8.0)
Requirement already satisfied: nvidia-cublas==13.1.1.3.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.1.1.3)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.0.88)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.0.0.61)
Requirement already satisfied: nvidia-nvjitlink<14,>=13.0.88 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.4.92)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.6.3.3)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.0.85)
Requirement already satisfied: defusedxml in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from nltk->rouge-score) (0.7.1)
Requirement already satisfied: joblib in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from nltk->rouge-score) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from pandas->datasets) (3.0.0)
Requirement already satisfied: shellingham>=1.3.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from typer->transformers) (0.0.5)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<8.0,>=4.5 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (7.1.0)
Requirement already satisfied: propcache>=0.2.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.25.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.7.0,>=2023.1.0->datasets) (1.25.1)
Requirement already satisfied: cuda-pathfinder>=1.4.2 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from cuda-bindings<14,>=13.0.3->torch>=2.0.0->accelerate) (1.8.4)
Requirement already satisfied: annotated-types>=0.6.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from pydantic>=2.0->compressed-tensors==0.19.0->llmcompressor) (0.8.0)
Requirement already satisfied: pydantic-core==2.50.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from pydantic>=2.0->compressed-tensors==0.19.0->llmcompressor) (2.50.1)
Requirement already satisfied: typing-inspection>=0.4.4 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from pydantic>=2.0->compressed-tensors==0.19.0->llmcompressor) (0.4.4)
Requirement already satisfied: tzdata in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (2026.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from rich>=13.8.0->typer->transformers) (2.21.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.4)
Requirement already satisfied: mdurl~=0.1 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Requirement already satisfied: httpcore2==2.16.0 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from httpx2<3,>=2.0.0->huggingface_hub) (2.16.0)
Requirement already satisfied: truststore>=0.10 in /home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages (from httpx2<3,>=2.0.0->huggingface_hub) (0.10.5)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import torch
import gc
import dotenv
import re
import unicodedata
import pandas as pd

from pathlib import Path
from getpass import getpass
from huggingface_hub import login
from datasets import load_dataset, Dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from llmcompressor import oneshot
from llmcompressor.modifiers.quantization import GPTQModifier, QuantizationModifier
from compressed_tensors.offload import dispatch_model
from llmcompressor.modifiers.transform.awq import AWQModifier
from llmcompressor.core import reset_session
from hqq.core.quantize import BaseQuantizeConfig
from hqq.models.hf.base import AutoHQQHFModel
from rouge_score import rouge_scorer
from sklearn.model_selection import ParameterGrid

dotenv.load_dotenv()

/home/imaha/Desktop/study/small-LLM/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

False

In [4]:
login(token=getpass("Hugging Face token: "), add_to_git_credential=False)

### Load XL-SUM dataset for validation

In [5]:
device = "cuda" if torch.cuda.is_available() else "cpu"
MODEL_NAME = "google/gemma-3-270m-it"
DTYPE = torch.float32
NUM_CALIBRATION_SAMPLES = 64
MAX_SEQ_LENGTH = 256

In [6]:
cwd = Path.cwd()
PROJECT_ROOT = cwd.parent if cwd.name == "notebooks" else cwd

validation_dataset = load_dataset(
    "parquet",
    data_files={
        "validation": str(PROJECT_ROOT / "data" / "raw" / "xlsum" / "ukrainian" / "validation" / "0000.parquet")
    },
    split="validation",
)

val_subset = validation_dataset.shuffle(seed=42).select(range(100))
val_data = val_subset["text"]
val_summaries = val_subset["summary"]

### Rouge tokenizer for Ukrainian

In [7]:
class UnicodeWordTokenizer:
  def tokenize(self, text):
    text = unicodedata.normalize("NFC", text).lower()
    text = text.replace("’", "'").replace("ʼ", "'")
    return re.findall(r"[^\W_]+(?:'[^\W_]+)*", text)

rouge = rouge_scorer.RougeScorer(["rouge1", "rouge2", "rougeL"], tokenizer=UnicodeWordTokenizer())

### Helper functions

In [8]:
def clear_memory():
    """
    Helper function to run garbage collection
    and release unused CUDA/MPS cached memory.
    """
    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    if torch.backends.mps.is_available():
        torch.mps.empty_cache()

def describe_model(model):
    """
    Helper function to retrieve information
    about model name and layers.
    """
    return type(model).__name__, model.model.layers

def model_size_mb(model):
    """
    Helper function to retrieve model size in MiB.
    """
    return model.get_memory_footprint() / 1_000_000

def load_baseline_model():
    """
    Helper function to load baseline model
    as a template for quantization methods.
    """
    return AutoModelForCausalLM.from_pretrained(MODEL_NAME, dtype=DTYPE).to(device).eval()


def tokenize_recieve(model, prompt):
    """
    Helper function to tokenize the prompt
    and recieve an answer.
    """
    message = [{"role": "user", "content": prompt}]

    inputs = tokenizer.apply_chat_template(message, tokenize=True, add_generation_prompt=True, return_tensors="pt", return_dict=True).to(model.device)

    with torch.inference_mode():
        outputs = model.generate(**inputs, max_new_tokens=100, do_sample=False)

    input_length = inputs["input_ids"].shape[1]
    new_tokens = outputs[0, input_length:]
    answer = tokenizer.decode(new_tokens, skip_special_tokens=True)

    return answer

def xlsum_prompt_formation(record):
    record = re.sub(r" {2,}", " ", record)

    prompt = (
        "Підсумуй цю статтю:\n"
        f"{record}\n"
    )

    return prompt

def evaluate_model(model, tokenizer):
    """
    Helper function to evaluate model's loss
    """
    model.eval()
    device = next(model.parameters()).device

    total_loss, total_tokens = 0.0, 0

    for prompt in val_data:
        inputs = tokenizer(prompt,
            return_tensors="pt",
            truncation=True,
            max_length=512,
        ).to(device)

        with torch.no_grad():
            outputs = model(
                **inputs,
                labels=inputs["input_ids"],
                use_cache=False,
            )

        token_count = inputs["input_ids"].shape[1] - 1
        total_loss += outputs.loss.item() * token_count
        total_tokens += token_count
        del outputs, inputs

    return { "loss": total_loss / total_tokens}

def evaluate_rouge(model):
    model.eval()
    rouge_res = []

    for text, reference in zip(val_data, val_summaries):
        prompt = xlsum_prompt_formation(text)
        prediction = tokenize_recieve(model, prompt)
        scores = rouge.score(target=reference, prediction=prediction)
        rouge_res.append({name: score.fmeasure for name, score in scores.items()})

    details = pd.DataFrame(rouge_res)
    rouge_averages = details[["rouge1", "rouge2", "rougeL"]].mean().to_dict()

    return rouge_averages

def model_results(baseline_model, baseline_model_loss, baseline_model_rouge, baseline_model_size, quantized_model, method_name):
    """
    Helper function for checking and comparing model's results.
    """
    example_prompt = "Explain quantization of Large Language Models in 1 sentence."

    loss_results_quantization = evaluate_model(quantized_model, tokenizer)
    loss_q = loss_results_quantization["loss"]

    rouge_results_quantization = evaluate_rouge(quantized_model)
    rouge1, rouge2, rougeL = rouge_results_quantization["rouge1"], rouge_results_quantization["rouge2"], rouge_results_quantization["rougeL"]

    print(f"\nBaseline model size (MB): {baseline_model_size:.3f}")
    print(f"Quantized {method_name} model size (MB): {model_size_mb(quantized_model):.3f}")

    print(f"Baseline loss: {baseline_model_loss:.4f}")
    print(f"{method_name} loss: {loss_q:.4f}\n")

    print("Baseline Rouge: "
          f"Rouge1: {baseline_model_rouge["rouge1"]:.4f}, "
          f"Rouge2: {baseline_model_rouge["rouge2"]:.4f}, "
          f"RougeL: {baseline_model_rouge["rougeL"]:.4f}")

    print(f"{method_name} Rouge: "
          f"Rouge1: {rouge1:.4f}, "
          f"Rouge2: {rouge2:.4f}, "
          f"RougeL: {rougeL:.4f}")

    print(f"\nPrompt: {example_prompt}")
    print(f"\nOutput Baseline: {tokenize_recieve(baseline_model, example_prompt).strip("\n")}")
    print(f"Output {method_name}: {tokenize_recieve(quantized_model, example_prompt).strip("\n")}")

## Baseline model

In [9]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForCausalLM.from_pretrained(MODEL_NAME, dtype=DTYPE).to(device)
model.eval()

model_type, baseline_model_descr = describe_model(model)

print(f"Model loaded on: {model.device}")
print(model_type)
print(baseline_model_descr)

del baseline_model_descr
del model
clear_memory()

Loading weights: 100%|██████████| 236/236 [00:00<00:00, 5879.99it/s]

Model loaded on: cuda:0
Gemma3ForCausalLM
ModuleList(
  (0-17): 18 x Gemma3DecoderLayer(
    (self_attn): Gemma3Attention(
      (q_proj): Linear(in_features=640, out_features=1024, bias=False)
      (k_proj): Linear(in_features=640, out_features=256, bias=False)
      (v_proj): Linear(in_features=640, out_features=256, bias=False)
      (o_proj): Linear(in_features=1024, out_features=640, bias=False)
      (q_norm): Gemma3RMSNorm((256,), eps=1e-06)
      (k_norm): Gemma3RMSNorm((256,), eps=1e-06)
    )
    (mlp): Gemma3MLP(
      (gate_proj): Linear(in_features=640, out_features=2048, bias=False)
      (up_proj): Linear(in_features=640, out_features=2048, bias=False)
      (down_proj): Linear(in_features=2048, out_features=640, bias=False)
      (act_fn): GELUTanh()
    )
    (input_layernorm): Gemma3RMSNorm((640,), eps=1e-06)
    (post_attention_layernorm): Gemma3RMSNorm((640,), eps=1e-06)
    (pre_feedforward_layernorm): Gemma3RMSNorm((640,), eps=1e-06)
    (post_feedforward_layernorm): Gemma3RMSNorm((640,), eps=1e-06)
  )
)

In [11]:
baseline_model = load_baseline_model()
evaluation_results_baseline = evaluate_model(baseline_model, tokenizer)
baseline_model_loss = evaluation_results_baseline["loss"]
baseline_model_rouge = evaluate_rouge(baseline_model)
baseline_size = model_size_mb(baseline_model)

Loading weights: 100%|██████████| 236/236 [00:00<00:00, 5124.86it/s]

### Calibration Dataset preparation

In [12]:
c4_dataset = load_dataset("allenai/c4", "uk", split="train", streaming=True,)
calibration_texts = [row["text"] for row in c4_dataset.take(NUM_CALIBRATION_SAMPLES)]

encoded = tokenizer(calibration_texts, truncation=True, max_length=MAX_SEQ_LENGTH, padding=False, add_special_tokens=False)
calibration_dataset = Dataset.from_dict(dict(encoded))

print("Calibration samples:", len(calibration_dataset))
print(calibration_texts[0][:500])

Calibration samples: 64
Як обмежити швидкість Інтернету? | Комп'ютер
Відповіді на питання. > Комп'ютер > Як обмежити швидкість Інтернету?
Як обмежити швидкість Інтернету?
Насправді, суть даної дії зовсім не в тому, щоб назавжди забезпечити себе слабкими швидкостями. Це необхідно лише для того, щоб розвантажити потік: коли швидкість використовується на повну котушку, нічого іншого з Інтернетом зробити просто не можна.
Якщо Ви володієте роутером, то Ви зможете обмежити швидкість всієї мережі в цілому, так і окремих прист

## Linear symmetric and asymmetric quantization

Linear quantization is the most fundamental method of model quantization. It maps floating-point values to discrete integers using a scale factor and a zero point, reducing the precision required to represent model weights.

Symmetric quantization uses a range symmetric around zero and fixes the zero point at 0. The scale is calculated from the maximum absolute value.

Asymmetric quantization uses the minimum and maximum values to calculate both the scale and the zero point, allowing the quantization range to adapt to unevenly distributed values.

In [13]:
def symmetric_quantize(x: torch.Tensor, dtype=torch.int8) -> tuple[torch.Tensor, torch.Tensor]:
    """
    Function implements Linear Symmetric Quantization per tensor.
    Zero point is fixed at 0.

    :param x: torch.Tensor, single tensor
    :param dtype: torch.dtype, type to downcast tensor to
    :return: tuple[torch.Tensor, torch.Tensor], downcast tensor, scale
    """
    max_original = x.abs().max()
    max_int = torch.iinfo(dtype).max
    s = max_original / max_int
    s = torch.where(s == 0, torch.ones_like(s), s)
    q = torch.round(x / s).clamp(-max_int, max_int).to(dtype)

    return q, s

def asymmetric_quantize(x: torch.Tensor, dtype=torch.int8) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """
    Function implements Linear Asymmetric Quantization per tensor.

    :param x: torch.Tensor, single tensor
    :param dtype: torch.dtype, type to downcast tensor to
    :return: tuple[torch.Tensor, torch.Tensor, torch.Tensor], downcast tensor, scale, zero point
    """
    min_original, max_original = x.min().clamp(max=0), x.max().clamp(min=0)
    min_int, max_int = torch.iinfo(dtype).min, torch.iinfo(dtype).max

    s = (max_original - min_original) / (max_int - min_int)
    s = torch.where(s == 0, torch.ones_like(s), s)

    z = torch.round(min_int - min_original / s).clamp(min_int, max_int).to(dtype)
    q = (torch.round(x / s) + z.float()).clamp(min_int, max_int).to(dtype)

    return q, s, z

def dequantize(q: torch.Tensor, s: torch.Tensor, z: int | torch.Tensor = 0) -> torch.Tensor:
    """
    Function implements Linear Dequantization per tensor.

    :param q: torch.Tensor, quantized tensor
    :param s: torch.Tensor, scale
    :param z: torch.Tensor, zero point
    :return: torch.Tensor, dequantized tensor
    """
    return s.float() * (q.float() - torch.as_tensor(z, dtype=torch.float32, device=q.device))


class QuantizedLinear(torch.nn.Module):
    @torch.no_grad()
    def __init__(self, linear, method="symmetric"):
        super().__init__()

        self.in_features = linear.in_features
        self.out_features = linear.out_features
        weights = linear.weight.detach().float()

        if method == "symmetric":
            q, scale = symmetric_quantize(weights)
            zero_point = torch.zeros((), dtype=torch.int8, device=q.device)
        elif method == "asymmetric":
            q, scale, zero_point = asymmetric_quantize(weights)

        self.register_buffer("bias", linear.bias.detach().clone() if linear.bias is not None else None)
        self.register_buffer("qweight", q)
        self.register_buffer("scale", scale)
        self.register_buffer("zero_point", zero_point)

    def forward(self, x):
        weight = dequantize(self.qweight, self.scale, self.zero_point).to(dtype=x.dtype)
        bias = (self.bias.to(dtype=x.dtype) if self.bias is not None else None)

        return torch.nn.functional.linear(x, weight, bias)

In [14]:
@torch.no_grad()
def linear_weights_quantization(model, method="symmetric"):
    results = []

    _, model_layers = describe_model(model)

    def replace_layers(parent):
        for name, module in list(parent.named_children()):
            if isinstance(module, torch.nn.Linear):
                quantized = QuantizedLinear(module, method)

                results.append({
                    "layer": name,
                    "shape": tuple(quantized.qweight.shape),
                    "num_weights": quantized.qweight.numel(),
                    "scale": quantized.scale.item(),
                    "zero_point": quantized.zero_point.item(),
                })

                setattr(parent, name, quantized)
            else:
                replace_layers(module)

    replace_layers(model_layers)
    return results

In [15]:
symmetric_model = load_baseline_model()

results_sym = linear_weights_quantization(symmetric_model, method="symmetric",)
prompt_results_symmetric = model_results(baseline_model, baseline_model_loss, baseline_model_rouge, baseline_size, symmetric_model, "Linear Symmetric")

del symmetric_model
clear_memory()

Loading weights: 100%|██████████| 236/236 [00:00<00:00, 6582.06it/s]

Baseline model size (MB): 1072.395
Quantized Linear Symmetric model size (MB): 771.585
Baseline loss: 3.8468
Linear Symmetric loss: 4.0384

Baseline Rouge: Rouge1: 0.1168, Rouge2: 0.0290, RougeL: 0.0914
Linear Symmetric Rouge: Rouge1: 0.1114, Rouge2: 0.0267, RougeL: 0.0848

Prompt: Explain quantization of Large Language Models in 1 sentence.

Output Baseline: Quantization reduces the size of a Large Language Model (LLM) while maintaining its performance, allowing for faster inference and lower computational costs.
Output Linear Symmetric: Large Language Models (LLMs) are designed to process and understand natural language, achieving a state-of-the-art performance in various tasks.

Symmetric quantization of linear layers reduced the model size by approximately 28%, with a small increase in loss and small decreases across all ROUGE scores. In the example prompt, the quantized model produced fluent text but failed to explain quantization, which suggests some degradation.

In [16]:
asymmetric_model = load_baseline_model()

results_asym = linear_weights_quantization(asymmetric_model, method="asymmetric",)
prompt_results_asymmetric = model_results(baseline_model, baseline_model_loss, baseline_model_rouge, baseline_size, asymmetric_model, "Linear Asymmetric")

del asymmetric_model
clear_memory()

Loading weights: 100%|██████████| 236/236 [00:00<00:00, 5173.36it/s]

Baseline model size (MB): 1072.395
Quantized Linear Asymmetric model size (MB): 771.585
Baseline loss: 3.8468
Linear Asymmetric loss: 3.9352

Baseline Rouge: Rouge1: 0.1168, Rouge2: 0.0290, RougeL: 0.0914
Linear Asymmetric Rouge: Rouge1: 0.1049, Rouge2: 0.0227, RougeL: 0.0810

Prompt: Explain quantization of Large Language Models in 1 sentence.

Output Baseline: Quantization reduces the size of a Large Language Model (LLM) while maintaining its performance, allowing for faster inference and lower computational costs.
Output Linear Asymmetric: Quantization reduces the model's size and computational cost, making it suitable for lower-resource environments.

Asymmetric quantization shows more precise results than symmetric quantization in terms of loss, likely because it uses a zero point to shift the quantization range and better represent weight distributions that are not centered around zero, although its ROUGE scores are lower.

## NF4 model - bitsandbytes

BitsAndBytes NF4 quantization compresses model weights into a 4-bit NormalFloat format using 16 nonuniformly spaced values designed for approximately normally distributed weights. Weights are quantized in blocks with separate scaling factors and dequantized to a higher precision for computation.

In [17]:
quantization_config = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_quant_type="nf4", bnb_4bit_compute_dtype=DTYPE)

nf4_model = AutoModelForCausalLM.from_pretrained(MODEL_NAME, quantization_config=quantization_config, device_map={"": 0}, dtype=DTYPE).eval()
prompt_results_nf4 = model_results(baseline_model, baseline_model_loss, baseline_model_rouge, baseline_size, nf4_model, "NF4")

del nf4_model
clear_memory()

Loading weights: 100%|██████████| 236/236 [00:00<00:00, 1213.90it/s]

Baseline model size (MB): 1072.395
Quantized NF4 model size (MB): 721.449
Baseline loss: 3.8468
NF4 loss: 4.3888

Baseline Rouge: Rouge1: 0.1168, Rouge2: 0.0290, RougeL: 0.0914
NF4 Rouge: Rouge1: 0.1120, Rouge2: 0.0252, RougeL: 0.0847

Prompt: Explain quantization of Large Language Models in 1 sentence.

Output Baseline: Quantization reduces the size of a Large Language Model (LLM) while maintaining its performance, allowing for faster inference and lower computational costs.
Output NF4: Quantization of Large Language Models (LLMs) aims to reduce the size and complexity of the model by lowering the number of parameters, typically to fractions of the original size. This reduces the model's computational cost, memory requirements, and training time, leading to improved performance on specific, often less-studied, tasks.

NF4 quantization reduced the model size by approximately 32%, but increased loss from 3.8468 to 4.3888 and lowered all ROUGE scores. The example response incorrectly described quantization as reducing the number of parameters and exceeded the one-sentence instruction, indicating reduced factual accuracy and instruction following.

## GPTQ

GPTQ is a method that uses calibration data and approximate second-order information to minimize layer output error. It quantizes weights sequentially, adjusting the remaining weights to compensate for quantization errors.

In [18]:
gptq_model = load_baseline_model()
gptq_recipe = GPTQModifier(targets=["Linear"], scheme="W4A16", ignore=["lm_head"], dampening_frac=0.1, actorder=None)

oneshot(model=gptq_model, tokenizer=tokenizer, dataset=calibration_dataset, recipe=gptq_recipe,
        max_seq_length=MAX_SEQ_LENGTH,
        num_calibration_samples=len(calibration_dataset),
        batch_size=1,
        shuffle_calibration_samples=False)

dispatch_model(gptq_model)
prompt_results_gptq = model_results(baseline_model, baseline_model_loss, baseline_model_rouge, baseline_size, gptq_model, "GPTQ")

reset_session()
del gptq_model, gptq_recipe
clear_memory()

Loading weights: 100%|██████████| 236/236 [00:00<00:00, 5168.72it/s]

2026-10-24T19:47:25.1038 | __init__ | WARNING - Disabling tokenizer parallelism due to threading conflict between FastTokenizer and Datasets. Set TOKENIZERS_PARALLELISM=false to suppress this warning.
2026-10-24T19:47:25.4932 | reset | INFO - Compression lifecycle reset
2026-10-24T19:47:25.5120 | norm_calibration_context | INFO - Found 109 offset-norm modules to convert
2026-10-24T19:47:25.5149 | from_modifiers | INFO - Creating recipe from modifiers

Applying quantization config: 100%|██████████| 126/126 [00:00<00:00, 14718.09it/s]

2026-10-24T19:47:25.5282 | initialize | INFO - Compression lifecycle initialized for 1 modifiers
2026-10-24T19:47:25.5284 | IndependentPipeline | INFO - Inferred `SequentialPipeline` for `GPTQModifier`

W1024 19:47:25.549000 474893 torch/fx/_symbolic_trace.py:57] is_fx_tracing will return true for both fx.symbolic_trace and torch.export. Please use is_fx_tracing_symbolic_tracing() for specifically fx.symbolic_trace or torch.compiler.is_compiling() for specifically torch.export/compile.
Preparing cache: 100%|██████████| 64/64 [00:00<00:00, 5066.92it/s]
(1/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 1390.85it/s]
(1/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 486.63it/s]
(2/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 773.65it/s]

2026-10-24T19:47:25.8601 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.0.self_attn.q_proj']
2026-10-24T19:47:25.8898 | GPTQ | METRIC - time 0.03s
2026-10-24T19:47:25.8902 | GPTQ | METRIC - error 337895.94
2026-10-24T19:47:25.8906 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:25.8914 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.0.self_attn.k_proj', 'model.layers.0.self_attn.v_proj']
2026-10-24T19:47:25.8959 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:25.8961 | GPTQ | METRIC - error 73580.51
2026-10-24T19:47:25.8965 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:25.8967 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:25.8969 | GPTQ | METRIC - error 87008.29
2026-10-24T19:47:25.8973 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:25.8978 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.0.self_attn.o_proj']
2026-10-24T19:47:25.9021 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:25.9024 | GPTQ | METRIC - error 63721.51
2026-10-24T19:47:25.9028 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:25.9035 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.0.mlp.gate_proj', 'model.layers.0.mlp.up_proj']
2026-10-24T19:47:25.9082 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:25.9085 | GPTQ | METRIC - error 14304.16
2026-10-24T19:47:25.9089 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:25.9091 | GPTQ | METRIC - time 0.01s
2026-10-24T19:47:25.9092 | GPTQ | METRIC - error 15342.76
2026-10-24T19:47:25.9096 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:25.9102 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.0.mlp.down_proj']
2026-10-24T19:47:25.9200 | GPTQ | METRIC - time 0.01s
2026-10-24T19:47:25.9202 | GPTQ | METRIC - error 4035.97
2026-10-24T19:47:25.9206 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb

(2/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 864.42it/s]
(3/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 812.29it/s]

2026-10-24T19:47:26.0765 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.1.self_attn.q_proj']
2026-10-24T19:47:26.0793 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.0796 | GPTQ | METRIC - error 136584.06
2026-10-24T19:47:26.0800 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.0807 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.1.self_attn.k_proj', 'model.layers.1.self_attn.v_proj']
2026-10-24T19:47:26.0846 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.0848 | GPTQ | METRIC - error 32386.93
2026-10-24T19:47:26.0852 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.0854 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.0857 | GPTQ | METRIC - error 31271.30
2026-10-24T19:47:26.0860 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.0865 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.1.self_attn.o_proj']
2026-10-24T19:47:26.0905 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.0907 | GPTQ | METRIC - error 7587.00
2026-10-24T19:47:26.0911 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.0918 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.1.mlp.gate_proj', 'model.layers.1.mlp.up_proj']
2026-10-24T19:47:26.0961 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.0964 | GPTQ | METRIC - error 4478.20
2026-10-24T19:47:26.0967 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.0968 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.0970 | GPTQ | METRIC - error 4582.70
2026-10-24T19:47:26.0974 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.0980 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.1.mlp.down_proj']
2026-10-24T19:47:26.1065 | GPTQ | METRIC - time 0.01s
2026-10-24T19:47:26.1067 | GPTQ | METRIC - error 126.71
2026-10-24T19:47:26.1071 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb

(3/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 954.28it/s]
(4/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 840.66it/s]

2026-10-24T19:47:26.2534 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.2.self_attn.q_proj']
2026-10-24T19:47:26.2563 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.2566 | GPTQ | METRIC - error 5572.87
2026-10-24T19:47:26.2570 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.2577 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.2.self_attn.k_proj', 'model.layers.2.self_attn.v_proj']
2026-10-24T19:47:26.2616 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.2619 | GPTQ | METRIC - error 1279.18
2026-10-24T19:47:26.2622 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.2624 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.2626 | GPTQ | METRIC - error 1292.61
2026-10-24T19:47:26.2629 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.2635 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.2.self_attn.o_proj']
2026-10-24T19:47:26.2674 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.2677 | GPTQ | METRIC - error 659.41
2026-10-24T19:47:26.2680 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.2687 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.2.mlp.gate_proj', 'model.layers.2.mlp.up_proj']
2026-10-24T19:47:26.2729 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.2731 | GPTQ | METRIC - error 2719.90
2026-10-24T19:47:26.2735 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.2737 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.2739 | GPTQ | METRIC - error 2749.03
2026-10-24T19:47:26.2743 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.2748 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.2.mlp.down_proj']

2026-10-24T19:47:26.2833 | GPTQ | METRIC - time 0.01s
2026-10-24T19:47:26.2836 | GPTQ | METRIC - error 59.94
2026-10-24T19:47:26.2840 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb

(4/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 973.45it/s]
(5/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 831.25it/s]

2026-10-24T19:47:26.4296 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.3.self_attn.q_proj']
2026-10-24T19:47:26.4325 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.4328 | GPTQ | METRIC - error 4584.46
2026-10-24T19:47:26.4332 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.4339 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.3.self_attn.k_proj', 'model.layers.3.self_attn.v_proj']
2026-10-24T19:47:26.4378 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.4381 | GPTQ | METRIC - error 1044.26
2026-10-24T19:47:26.4385 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.4387 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.4388 | GPTQ | METRIC - error 1320.86
2026-10-24T19:47:26.4392 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.4398 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.3.self_attn.o_proj']
2026-10-24T19:47:26.4437 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.4440 | GPTQ | METRIC - error 196.65
2026-10-24T19:47:26.4444 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.4451 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.3.mlp.gate_proj', 'model.layers.3.mlp.up_proj']
2026-10-24T19:47:26.4493 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.4496 | GPTQ | METRIC - error 2522.62
2026-10-24T19:47:26.4500 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.4502 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.4503 | GPTQ | METRIC - error 2463.00
2026-10-24T19:47:26.4507 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.4512 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.3.mlp.down_proj']

2026-10-24T19:47:26.4598 | GPTQ | METRIC - time 0.01s
2026-10-24T19:47:26.4600 | GPTQ | METRIC - error 72.67
2026-10-24T19:47:26.4604 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb

(5/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 989.61it/s]
(6/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 826.24it/s]

2026-10-24T19:47:26.6056 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.4.self_attn.q_proj']
2026-10-24T19:47:26.6086 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.6089 | GPTQ | METRIC - error 3786.71
2026-10-24T19:47:26.6092 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.6099 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.4.self_attn.k_proj', 'model.layers.4.self_attn.v_proj']
2026-10-24T19:47:26.6139 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.6142 | GPTQ | METRIC - error 995.75
2026-10-24T19:47:26.6146 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.6148 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.6150 | GPTQ | METRIC - error 864.32
2026-10-24T19:47:26.6153 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.6159 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.4.self_attn.o_proj']
2026-10-24T19:47:26.6199 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.6201 | GPTQ | METRIC - error 118.85
2026-10-24T19:47:26.6205 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.6212 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.4.mlp.gate_proj', 'model.layers.4.mlp.up_proj']
2026-10-24T19:47:26.6255 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.6258 | GPTQ | METRIC - error 1856.70
2026-10-24T19:47:26.6262 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.6264 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.6265 | GPTQ | METRIC - error 1915.93
2026-10-24T19:47:26.6269 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.6275 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.4.mlp.down_proj']

2026-10-24T19:47:26.6361 | GPTQ | METRIC - time 0.01s
2026-10-24T19:47:26.6363 | GPTQ | METRIC - error 12.98
2026-10-24T19:47:26.6367 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb

(6/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 977.63it/s]
(7/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 818.58it/s]

2026-10-24T19:47:26.7832 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.5.self_attn.q_proj']
2026-10-24T19:47:26.7862 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.7865 | GPTQ | METRIC - error 1889.59
2026-10-24T19:47:26.7869 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.7876 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.5.self_attn.k_proj', 'model.layers.5.self_attn.v_proj']
2026-10-24T19:47:26.7916 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.7918 | GPTQ | METRIC - error 531.34
2026-10-24T19:47:26.7923 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.7925 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.7926 | GPTQ | METRIC - error 1208.68
2026-10-24T19:47:26.7930 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.7936 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.5.self_attn.o_proj']
2026-10-24T19:47:26.7976 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.7978 | GPTQ | METRIC - error 180.36
2026-10-24T19:47:26.7982 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.7989 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.5.mlp.gate_proj', 'model.layers.5.mlp.up_proj']
2026-10-24T19:47:26.8032 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.8034 | GPTQ | METRIC - error 1279.73
2026-10-24T19:47:26.8038 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.8040 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.8042 | GPTQ | METRIC - error 1299.75

2026-10-24T19:47:26.8045 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.8052 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.5.mlp.down_proj']
2026-10-24T19:47:26.8138 | GPTQ | METRIC - time 0.01s
2026-10-24T19:47:26.8140 | GPTQ | METRIC - error 34.96
2026-10-24T19:47:26.8144 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb

(7/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 969.60it/s]
(8/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 817.55it/s]

2026-10-24T19:47:26.9616 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.6.self_attn.q_proj']
2026-10-24T19:47:26.9645 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.9648 | GPTQ | METRIC - error 3333.54
2026-10-24T19:47:26.9652 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.9659 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.6.self_attn.k_proj', 'model.layers.6.self_attn.v_proj']
2026-10-24T19:47:26.9699 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.9702 | GPTQ | METRIC - error 791.31
2026-10-24T19:47:26.9705 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.9707 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.9709 | GPTQ | METRIC - error 843.29
2026-10-24T19:47:26.9713 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.9719 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.6.self_attn.o_proj']
2026-10-24T19:47:26.9759 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.9761 | GPTQ | METRIC - error 132.57
2026-10-24T19:47:26.9765 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.9772 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.6.mlp.gate_proj', 'model.layers.6.mlp.up_proj']
2026-10-24T19:47:26.9812 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.9816 | GPTQ | METRIC - error 923.43
2026-10-24T19:47:26.9820 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb

2026-10-24T19:47:26.9821 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:26.9823 | GPTQ | METRIC - error 979.23
2026-10-24T19:47:26.9828 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:26.9834 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.6.mlp.down_proj']
2026-10-24T19:47:26.9919 | GPTQ | METRIC - time 0.01s
2026-10-24T19:47:26.9922 | GPTQ | METRIC - error 8.17
2026-10-24T19:47:26.9925 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb

(8/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 972.27it/s]
(9/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 830.80it/s]

2026-10-24T19:47:27.1383 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.7.self_attn.q_proj']
2026-10-24T19:47:27.1412 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.1415 | GPTQ | METRIC - error 7531.67
2026-10-24T19:47:27.1419 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.1426 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.7.self_attn.k_proj', 'model.layers.7.self_attn.v_proj']
2026-10-24T19:47:27.1465 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.1468 | GPTQ | METRIC - error 1936.23
2026-10-24T19:47:27.1472 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.1474 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.1475 | GPTQ | METRIC - error 1778.61
2026-10-24T19:47:27.1479 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.1485 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.7.self_attn.o_proj']
2026-10-24T19:47:27.1524 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.1527 | GPTQ | METRIC - error 639.31
2026-10-24T19:47:27.1531 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.1537 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.7.mlp.gate_proj', 'model.layers.7.mlp.up_proj']
2026-10-24T19:47:27.1579 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.1582 | GPTQ | METRIC - error 871.53
2026-10-24T19:47:27.1585 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.1587 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.1589 | GPTQ | METRIC - error 978.82
2026-10-24T19:47:27.1593 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.1598 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.7.mlp.down_proj']

2026-10-24T19:47:27.1685 | GPTQ | METRIC - time 0.01s
2026-10-24T19:47:27.1688 | GPTQ | METRIC - error 17.75
2026-10-24T19:47:27.1692 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb

(9/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 987.82it/s]
(10/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 817.66it/s]

2026-10-24T19:47:27.3152 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.8.self_attn.q_proj']
2026-10-24T19:47:27.3181 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.3184 | GPTQ | METRIC - error 7829.44
2026-10-24T19:47:27.3187 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.3195 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.8.self_attn.k_proj', 'model.layers.8.self_attn.v_proj']
2026-10-24T19:47:27.3234 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.3237 | GPTQ | METRIC - error 2005.79
2026-10-24T19:47:27.3241 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.3243 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.3244 | GPTQ | METRIC - error 2148.80
2026-10-24T19:47:27.3248 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.3254 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.8.self_attn.o_proj']
2026-10-24T19:47:27.3299 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.3302 | GPTQ | METRIC - error 470.42
2026-10-24T19:47:27.3306 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.3314 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.8.mlp.gate_proj', 'model.layers.8.mlp.up_proj']
2026-10-24T19:47:27.3357 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.3360 | GPTQ | METRIC - error 911.36
2026-10-24T19:47:27.3364 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.3365 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.3366 | GPTQ | METRIC - error 1004.26
2026-10-24T19:47:27.3369 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.3374 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.8.mlp.down_proj']

2026-10-24T19:47:27.3458 | GPTQ | METRIC - time 0.01s
2026-10-24T19:47:27.3459 | GPTQ | METRIC - error 8.32
2026-10-24T19:47:27.3463 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb

(10/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 997.64it/s]
(11/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 836.81it/s]

2026-10-24T19:47:27.4896 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.9.self_attn.q_proj']
2026-10-24T19:47:27.4923 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.4926 | GPTQ | METRIC - error 6080.16
2026-10-24T19:47:27.4929 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.4935 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.9.self_attn.k_proj', 'model.layers.9.self_attn.v_proj']
2026-10-24T19:47:27.4974 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.4976 | GPTQ | METRIC - error 1516.41
2026-10-24T19:47:27.4980 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.4981 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.4982 | GPTQ | METRIC - error 1543.28
2026-10-24T19:47:27.4985 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.4990 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.9.self_attn.o_proj']
2026-10-24T19:47:27.5028 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.5031 | GPTQ | METRIC - error 278.52
2026-10-24T19:47:27.5034 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.5039 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.9.mlp.gate_proj', 'model.layers.9.mlp.up_proj']
2026-10-24T19:47:27.5081 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.5083 | GPTQ | METRIC - error 409.55
2026-10-24T19:47:27.5087 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.5089 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.5090 | GPTQ | METRIC - error 466.25
2026-10-24T19:47:27.5093 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.5098 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.9.mlp.down_proj']

2026-10-24T19:47:27.5182 | GPTQ | METRIC - time 0.01s
2026-10-24T19:47:27.5184 | GPTQ | METRIC - error 6.06
2026-10-24T19:47:27.5187 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb

(11/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 1004.31it/s]
(12/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 827.15it/s]

2026-10-24T19:47:27.6627 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.10.self_attn.q_proj']
2026-10-24T19:47:27.6654 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.6657 | GPTQ | METRIC - error 8118.32
2026-10-24T19:47:27.6660 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.6666 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.10.self_attn.k_proj', 'model.layers.10.self_attn.v_proj']
2026-10-24T19:47:27.6706 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.6708 | GPTQ | METRIC - error 2303.41
2026-10-24T19:47:27.6712 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.6713 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.6715 | GPTQ | METRIC - error 1878.38
2026-10-24T19:47:27.6718 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.6724 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.10.self_attn.o_proj']
2026-10-24T19:47:27.6763 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.6766 | GPTQ | METRIC - error 796.64
2026-10-24T19:47:27.6769 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.6775 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.10.mlp.gate_proj', 'model.layers.10.mlp.up_proj']
2026-10-24T19:47:27.6815 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.6817 | GPTQ | METRIC - error 769.49
2026-10-24T19:47:27.6820 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.6822 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.6823 | GPTQ | METRIC - error 813.45
2026-10-24T19:47:27.6827 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.6837 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.10.mlp.down_proj']

2026-10-24T19:47:27.6924 | GPTQ | METRIC - time 0.01s
2026-10-24T19:47:27.6927 | GPTQ | METRIC - error 8.14
2026-10-24T19:47:27.6930 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb

(12/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 977.08it/s]
(13/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 812.21it/s]

2026-10-24T19:47:27.8402 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.11.self_attn.q_proj']
2026-10-24T19:47:27.8433 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.8435 | GPTQ | METRIC - error 615.73
2026-10-24T19:47:27.8440 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.8447 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.11.self_attn.k_proj', 'model.layers.11.self_attn.v_proj']
2026-10-24T19:47:27.8486 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.8489 | GPTQ | METRIC - error 229.06
2026-10-24T19:47:27.8493 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.8495 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.8497 | GPTQ | METRIC - error 246.15
2026-10-24T19:47:27.8500 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.8506 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.11.self_attn.o_proj']
2026-10-24T19:47:27.8546 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.8549 | GPTQ | METRIC - error 92.49
2026-10-24T19:47:27.8553 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.8559 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.11.mlp.gate_proj', 'model.layers.11.mlp.up_proj']
2026-10-24T19:47:27.8606 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:27.8608 | GPTQ | METRIC - error 1261.17
2026-10-24T19:47:27.8612 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.8614 | GPTQ | METRIC - time 0.00s

2026-10-24T19:47:27.8615 | GPTQ | METRIC - error 1386.53
2026-10-24T19:47:27.8618 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:27.8624 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.11.mlp.down_proj']
2026-10-24T19:47:27.8709 | GPTQ | METRIC - time 0.01s
2026-10-24T19:47:27.8711 | GPTQ | METRIC - error 30.54
2026-10-24T19:47:27.8714 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb

(13/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 976.52it/s]
(14/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 814.37it/s]

2026-10-24T19:47:28.0184 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.12.self_attn.q_proj']
2026-10-24T19:47:28.0213 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.0216 | GPTQ | METRIC - error 6221.46
2026-10-24T19:47:28.0220 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.0227 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.12.self_attn.k_proj', 'model.layers.12.self_attn.v_proj']
2026-10-24T19:47:28.0266 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.0269 | GPTQ | METRIC - error 2689.33
2026-10-24T19:47:28.0273 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.0275 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.0277 | GPTQ | METRIC - error 1621.26
2026-10-24T19:47:28.0280 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.0286 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.12.self_attn.o_proj']
2026-10-24T19:47:28.0326 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.0328 | GPTQ | METRIC - error 477.87
2026-10-24T19:47:28.0332 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.0339 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.12.mlp.gate_proj', 'model.layers.12.mlp.up_proj']
2026-10-24T19:47:28.0380 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.0383 | GPTQ | METRIC - error 655.17
2026-10-24T19:47:28.0387 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.0389 | GPTQ | METRIC - time 0.00s

2026-10-24T19:47:28.0391 | GPTQ | METRIC - error 676.02
2026-10-24T19:47:28.0394 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.0401 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.12.mlp.down_proj']
2026-10-24T19:47:28.0487 | GPTQ | METRIC - time 0.01s
2026-10-24T19:47:28.0489 | GPTQ | METRIC - error 13.69
2026-10-24T19:47:28.0493 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb

(14/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 978.18it/s]
(15/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 829.29it/s]

2026-10-24T19:47:28.1949 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.13.self_attn.q_proj']
2026-10-24T19:47:28.1977 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.1980 | GPTQ | METRIC - error 12021.91
2026-10-24T19:47:28.1983 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.1991 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.13.self_attn.k_proj', 'model.layers.13.self_attn.v_proj']
2026-10-24T19:47:28.2030 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.2033 | GPTQ | METRIC - error 3301.38
2026-10-24T19:47:28.2036 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.2038 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.2039 | GPTQ | METRIC - error 3757.92
2026-10-24T19:47:28.2043 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.2049 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.13.self_attn.o_proj']
2026-10-24T19:47:28.2088 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.2091 | GPTQ | METRIC - error 574.76
2026-10-24T19:47:28.2094 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.2101 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.13.mlp.gate_proj', 'model.layers.13.mlp.up_proj']
2026-10-24T19:47:28.2141 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.2143 | GPTQ | METRIC - error 427.17
2026-10-24T19:47:28.2147 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.2149 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.2151 | GPTQ | METRIC - error 484.11
2026-10-24T19:47:28.2155 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.2160 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.13.mlp.down_proj']

2026-10-24T19:47:28.2246 | GPTQ | METRIC - time 0.01s
2026-10-24T19:47:28.2248 | GPTQ | METRIC - error 5.47
2026-10-24T19:47:28.2252 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb

(15/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 987.82it/s]
(16/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 828.94it/s]

2026-10-24T19:47:28.3701 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.14.self_attn.q_proj']
2026-10-24T19:47:28.3731 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.3733 | GPTQ | METRIC - error 9534.83
2026-10-24T19:47:28.3737 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.3745 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.14.self_attn.k_proj', 'model.layers.14.self_attn.v_proj']
2026-10-24T19:47:28.3784 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.3787 | GPTQ | METRIC - error 3090.42
2026-10-24T19:47:28.3791 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.3793 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.3795 | GPTQ | METRIC - error 2349.39
2026-10-24T19:47:28.3798 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.3804 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.14.self_attn.o_proj']
2026-10-24T19:47:28.3844 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.3847 | GPTQ | METRIC - error 585.08
2026-10-24T19:47:28.3851 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.3857 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.14.mlp.gate_proj', 'model.layers.14.mlp.up_proj']
2026-10-24T19:47:28.3898 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.3900 | GPTQ | METRIC - error 367.24
2026-10-24T19:47:28.3904 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.3906 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.3907 | GPTQ | METRIC - error 416.06
2026-10-24T19:47:28.3911 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.3917 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.14.mlp.down_proj']

2026-10-24T19:47:28.4002 | GPTQ | METRIC - time 0.01s
2026-10-24T19:47:28.4004 | GPTQ | METRIC - error 3.27
2026-10-24T19:47:28.4008 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb

(16/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 992.57it/s]
(17/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 842.52it/s]

2026-10-24T19:47:28.5442 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.15.self_attn.q_proj']
2026-10-24T19:47:28.5470 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.5473 | GPTQ | METRIC - error 11429.89
2026-10-24T19:47:28.5477 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.5484 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.15.self_attn.k_proj', 'model.layers.15.self_attn.v_proj']
2026-10-24T19:47:28.5523 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.5526 | GPTQ | METRIC - error 3340.57
2026-10-24T19:47:28.5529 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.5531 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.5533 | GPTQ | METRIC - error 2731.65
2026-10-24T19:47:28.5536 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.5542 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.15.self_attn.o_proj']
2026-10-24T19:47:28.5581 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.5584 | GPTQ | METRIC - error 1285.41
2026-10-24T19:47:28.5587 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.5594 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.15.mlp.gate_proj', 'model.layers.15.mlp.up_proj']
2026-10-24T19:47:28.5635 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.5641 | GPTQ | METRIC - error 249.92
2026-10-24T19:47:28.5646 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.5647 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.5649 | GPTQ | METRIC - error 274.94
2026-10-24T19:47:28.5653 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.5659 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.15.mlp.down_proj']

2026-10-24T19:47:28.5744 | GPTQ | METRIC - time 0.01s
2026-10-24T19:47:28.5747 | GPTQ | METRIC - error 2.46
2026-10-24T19:47:28.5751 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb

(17/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 982.86it/s]
(18/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 828.31it/s]

2026-10-24T19:47:28.7203 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.16.self_attn.q_proj']
2026-10-24T19:47:28.7232 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.7235 | GPTQ | METRIC - error 16395.54
2026-10-24T19:47:28.7239 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.7245 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.16.self_attn.k_proj', 'model.layers.16.self_attn.v_proj']
2026-10-24T19:47:28.7284 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.7288 | GPTQ | METRIC - error 4473.06
2026-10-24T19:47:28.7291 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.7293 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.7295 | GPTQ | METRIC - error 4385.84
2026-10-24T19:47:28.7298 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.7304 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.16.self_attn.o_proj']
2026-10-24T19:47:28.7345 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.7348 | GPTQ | METRIC - error 1101.88
2026-10-24T19:47:28.7351 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.7358 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.16.mlp.gate_proj', 'model.layers.16.mlp.up_proj']
2026-10-24T19:47:28.7398 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.7400 | GPTQ | METRIC - error 251.82
2026-10-24T19:47:28.7404 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.7406 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.7408 | GPTQ | METRIC - error 277.20
2026-10-24T19:47:28.7411 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.7417 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.16.mlp.down_proj']

2026-10-24T19:47:28.7503 | GPTQ | METRIC - time 0.01s
2026-10-24T19:47:28.7505 | GPTQ | METRIC - error 3.47
2026-10-24T19:47:28.7509 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb

(18/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 976.51it/s]
(19/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 794.79it/s]

2026-10-24T19:47:28.8998 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.17.self_attn.q_proj']
2026-10-24T19:47:28.9027 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.9030 | GPTQ | METRIC - error 4699.55
2026-10-24T19:47:28.9034 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.9041 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.17.self_attn.k_proj', 'model.layers.17.self_attn.v_proj']
2026-10-24T19:47:28.9080 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.9083 | GPTQ | METRIC - error 1428.04
2026-10-24T19:47:28.9087 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.9089 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.9091 | GPTQ | METRIC - error 1529.53
2026-10-24T19:47:28.9093 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.9100 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.17.self_attn.o_proj']
2026-10-24T19:47:28.9141 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.9144 | GPTQ | METRIC - error 502.85
2026-10-24T19:47:28.9148 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.9155 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.17.mlp.gate_proj', 'model.layers.17.mlp.up_proj']
2026-10-24T19:47:28.9195 | GPTQ | METRIC - time 0.00s

2026-10-24T19:47:28.9198 | GPTQ | METRIC - error 459.05
2026-10-24T19:47:28.9202 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.9204 | GPTQ | METRIC - time 0.00s
2026-10-24T19:47:28.9206 | GPTQ | METRIC - error 469.74
2026-10-24T19:47:28.9210 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb
2026-10-24T19:47:28.9216 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.17.mlp.down_proj']
2026-10-24T19:47:28.9302 | GPTQ | METRIC - time 0.01s
2026-10-24T19:47:28.9306 | GPTQ | METRIC - error 6.60
2026-10-24T19:47:28.9309 | GPTQ | METRIC - Accelerator 0 | usage: 17.52% | total memory: 16.7 Gb

(19/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 1024.65it/s]

2026-10-24T19:47:28.9983 | norm_calibration_context | INFO - Restoring 109 norm modules to offset convention
2026-10-24T19:47:29.0007 | finalize | INFO - Compression lifecycle finalized for 1 modifiers

Baseline model size (MB): 1072.395
Quantized GPTQ model size (MB): 1076.312
Baseline loss: 3.8468
GPTQ loss: 4.4205

Baseline Rouge: Rouge1: 0.1168, Rouge2: 0.0290, RougeL: 0.0914
GPTQ Rouge: Rouge1: 0.0744, Rouge2: 0.0139, RougeL: 0.0587

Prompt: Explain quantization of Large Language Models in 1 sentence.

Output Baseline: Quantization reduces the size of a Large Language Model (LLM) while maintaining its performance, allowing for faster inference and lower computational costs.
Output GPTQ: In the field of Artificial Intelligence, quantization is a crucial technique to reduce the size of a large language model (LLM) to a manageable integer. This is done by performing operations on the model's weights and parameters, such as reducing the number of bits of information. This process ensures the model performs its intended task efficiently and accurately, ensuring the model doesn't have any off-reading or misinterpretations.

In essence, quantization is a way to make LLMs more performant by
2026-10-24T19:51:01.9475 | reset | INFO - Compression lifecycle reset

GPTQ showed a slightly larger reported model size, increased loss from 3.8468 to 4.4205, and lowered ROUGE scores. The example response contained inaccurate explanations and exceeded the one-sentence instruction, indicating reduced factual accuracy and instruction following. This GPTQ model uses a basic configuration, so tuning its quantization parameters and calibration setup may improve the results.

In [19]:
param_grid = {"dampening_frac": [0.01, 0.05, 0.1], "actorder": [None, "static"],}
gptq_search_results = []

for params in ParameterGrid(param_grid):
  print(f"\nTesting: {params}", flush=True)

  gptq_model = load_baseline_model()

  try:
    recipe = GPTQModifier(targets=["Linear"], scheme="W4A16", ignore=["lm_head"], **params,)

    oneshot(model=gptq_model, tokenizer=tokenizer, dataset=calibration_dataset,
            recipe=recipe, max_seq_length=MAX_SEQ_LENGTH,
            num_calibration_samples=len(calibration_dataset),
            batch_size=1,
            shuffle_calibration_samples=False)

    dispatch_model(gptq_model)

    loss = evaluate_model(gptq_model, tokenizer)["loss"]
    rouge_scores = evaluate_rouge(gptq_model)

    gptq_search_results.append({**params, "loss": loss, "size_MB": model_size_mb(gptq_model), **rouge_scores})

  finally:
    reset_session()
    del gptq_model, recipe
    clear_memory()

gptq_search_df = (pd.DataFrame(gptq_search_results).sort_values("loss").reset_index(drop=True))
display(gptq_search_df)

Testing: {'actorder': None, 'dampening_frac': 0.01}

Loading weights: 100%|██████████| 236/236 [00:00<00:00, 5933.21it/s]

2026-10-24T19:51:03.5969 | reset | INFO - Compression lifecycle reset
2026-10-24T19:51:03.6009 | norm_calibration_context | INFO - Found 109 offset-norm modules to convert
2026-10-24T19:51:03.6063 | from_modifiers | INFO - Creating recipe from modifiers

Applying quantization config: 100%|██████████| 126/126 [00:00<00:00, 13256.80it/s]

2026-10-24T19:51:03.6206 | initialize | INFO - Compression lifecycle initialized for 1 modifiers
2026-10-24T19:51:03.6209 | IndependentPipeline | INFO - Inferred `SequentialPipeline` for `GPTQModifier`

Preparing cache: 100%|██████████| 64/64 [00:00<00:00, 5014.86it/s]
(1/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 1406.85it/s]
(1/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 607.56it/s]
(2/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 785.86it/s]

2026-10-24T19:51:03.9094 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.0.self_attn.q_proj']
2026-10-24T19:51:03.9125 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:03.9132 | GPTQ | METRIC - error 209755.77
2026-10-24T19:51:03.9137 | GPTQ | METRIC - Accelerator 0 | usage: 19.69% | total memory: 16.7 Gb
2026-10-24T19:51:03.9143 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.0.self_attn.k_proj', 'model.layers.0.self_attn.v_proj']
2026-10-24T19:51:03.9187 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:03.9190 | GPTQ | METRIC - error 45435.80
2026-10-24T19:51:03.9193 | GPTQ | METRIC - Accelerator 0 | usage: 19.69% | total memory: 16.7 Gb
2026-10-24T19:51:03.9195 | GPTQ | METRIC - time 0.00s

2026-10-24T19:51:03.9197 | GPTQ | METRIC - error 54158.76
2026-10-24T19:51:03.9202 | GPTQ | METRIC - Accelerator 0 | usage: 19.69% | total memory: 16.7 Gb
2026-10-24T19:51:03.9208 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.0.self_attn.o_proj']
2026-10-24T19:51:03.9250 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:03.9253 | GPTQ | METRIC - error 41993.03
2026-10-24T19:51:03.9257 | GPTQ | METRIC - Accelerator 0 | usage: 19.69% | total memory: 16.7 Gb
2026-10-24T19:51:03.9264 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.0.mlp.gate_proj', 'model.layers.0.mlp.up_proj']
2026-10-24T19:51:03.9311 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:03.9314 | GPTQ | METRIC - error 10731.58
2026-10-24T19:51:03.9317 | GPTQ | METRIC - Accelerator 0 | usage: 19.69% | total memory: 16.7 Gb
2026-10-24T19:51:03.9319 | GPTQ | METRIC - time 0.01s
2026-10-24T19:51:03.9320 | GPTQ | METRIC - error 11520.77
2026-10-24T19:51:03.9324 | GPTQ | METRIC - Accelerator 0 | usage: 19.69% | total memory: 16.7 Gb
2026-10-24T19:51:03.9330 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.0.mlp.down_proj']
2026-10-24T19:51:03.9425 | GPTQ | METRIC - time 0.01s
2026-10-24T19:51:03.9428 | GPTQ | METRIC - error 2738.34
2026-10-24T19:51:03.9432 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb

(2/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 904.78it/s]
(3/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 825.22it/s]

2026-10-24T19:51:04.0944 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.1.self_attn.q_proj']
2026-10-24T19:51:04.0974 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.0977 | GPTQ | METRIC - error 109962.27
2026-10-24T19:51:04.0981 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.0988 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.1.self_attn.k_proj', 'model.layers.1.self_attn.v_proj']
2026-10-24T19:51:04.1028 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.1030 | GPTQ | METRIC - error 25951.75
2026-10-24T19:51:04.1034 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.1036 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.1037 | GPTQ | METRIC - error 24950.43
2026-10-24T19:51:04.1041 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.1047 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.1.self_attn.o_proj']
2026-10-24T19:51:04.1086 | GPTQ | METRIC - time 0.00s

2026-10-24T19:51:04.1089 | GPTQ | METRIC - error 5096.02
2026-10-24T19:51:04.1093 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.1100 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.1.mlp.gate_proj', 'model.layers.1.mlp.up_proj']
2026-10-24T19:51:04.1143 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.1145 | GPTQ | METRIC - error 3737.42
2026-10-24T19:51:04.1149 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.1151 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.1153 | GPTQ | METRIC - error 3827.79
2026-10-24T19:51:04.1157 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.1163 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.1.mlp.down_proj']
2026-10-24T19:51:04.1248 | GPTQ | METRIC - time 0.01s
2026-10-24T19:51:04.1251 | GPTQ | METRIC - error 103.80
2026-10-24T19:51:04.1255 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb

(3/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 968.34it/s]
(4/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 811.69it/s]

2026-10-24T19:51:04.2734 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.2.self_attn.q_proj']
2026-10-24T19:51:04.2764 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.2766 | GPTQ | METRIC - error 4550.28
2026-10-24T19:51:04.2771 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.2778 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.2.self_attn.k_proj', 'model.layers.2.self_attn.v_proj']
2026-10-24T19:51:04.2818 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.2821 | GPTQ | METRIC - error 1016.22
2026-10-24T19:51:04.2824 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.2826 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.2828 | GPTQ | METRIC - error 1034.82
2026-10-24T19:51:04.2832 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.2838 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.2.self_attn.o_proj']
2026-10-24T19:51:04.2877 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.2880 | GPTQ | METRIC - error 436.73
2026-10-24T19:51:04.2884 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.2891 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.2.mlp.gate_proj', 'model.layers.2.mlp.up_proj']
2026-10-24T19:51:04.2934 | GPTQ | METRIC - time 0.00s

2026-10-24T19:51:04.2937 | GPTQ | METRIC - error 2230.95
2026-10-24T19:51:04.2940 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.2942 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.2943 | GPTQ | METRIC - error 2258.60
2026-10-24T19:51:04.2948 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.2954 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.2.mlp.down_proj']
2026-10-24T19:51:04.3039 | GPTQ | METRIC - time 0.01s
2026-10-24T19:51:04.3042 | GPTQ | METRIC - error 49.96
2026-10-24T19:51:04.3046 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb

(4/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 963.95it/s]
(5/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 813.75it/s]

2026-10-24T19:51:04.4526 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.3.self_attn.q_proj']
2026-10-24T19:51:04.4556 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.4559 | GPTQ | METRIC - error 3438.35
2026-10-24T19:51:04.4563 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.4570 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.3.self_attn.k_proj', 'model.layers.3.self_attn.v_proj']
2026-10-24T19:51:04.4609 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.4612 | GPTQ | METRIC - error 789.95
2026-10-24T19:51:04.4616 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.4617 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.4619 | GPTQ | METRIC - error 1004.10
2026-10-24T19:51:04.4622 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.4628 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.3.self_attn.o_proj']
2026-10-24T19:51:04.4668 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.4671 | GPTQ | METRIC - error 153.07
2026-10-24T19:51:04.4675 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.4682 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.3.mlp.gate_proj', 'model.layers.3.mlp.up_proj']
2026-10-24T19:51:04.4724 | GPTQ | METRIC - time 0.00s

2026-10-24T19:51:04.4727 | GPTQ | METRIC - error 1927.67
2026-10-24T19:51:04.4732 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.4733 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.4735 | GPTQ | METRIC - error 1894.13
2026-10-24T19:51:04.4739 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.4745 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.3.mlp.down_proj']
2026-10-24T19:51:04.4830 | GPTQ | METRIC - time 0.01s
2026-10-24T19:51:04.4833 | GPTQ | METRIC - error 52.74
2026-10-24T19:51:04.4837 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb

(5/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 972.54it/s]
(6/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 822.37it/s]

2026-10-24T19:51:04.6302 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.4.self_attn.q_proj']
2026-10-24T19:51:04.6331 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.6334 | GPTQ | METRIC - error 2578.12
2026-10-24T19:51:04.6338 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.6345 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.4.self_attn.k_proj', 'model.layers.4.self_attn.v_proj']
2026-10-24T19:51:04.6385 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.6388 | GPTQ | METRIC - error 678.46
2026-10-24T19:51:04.6391 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.6393 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.6395 | GPTQ | METRIC - error 584.53
2026-10-24T19:51:04.6399 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.6405 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.4.self_attn.o_proj']
2026-10-24T19:51:04.6445 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.6447 | GPTQ | METRIC - error 73.07
2026-10-24T19:51:04.6451 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.6458 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.4.mlp.gate_proj', 'model.layers.4.mlp.up_proj']
2026-10-24T19:51:04.6500 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.6502 | GPTQ | METRIC - error 1231.40
2026-10-24T19:51:04.6506 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.6508 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.6510 | GPTQ | METRIC - error 1271.00
2026-10-24T19:51:04.6514 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb

2026-10-24T19:51:04.6524 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.4.mlp.down_proj']
2026-10-24T19:51:04.6612 | GPTQ | METRIC - time 0.01s
2026-10-24T19:51:04.6614 | GPTQ | METRIC - error 9.35
2026-10-24T19:51:04.6617 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb

(6/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 956.14it/s]
(7/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 828.66it/s]

2026-10-24T19:51:04.8087 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.5.self_attn.q_proj']
2026-10-24T19:51:04.8117 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.8120 | GPTQ | METRIC - error 1274.56
2026-10-24T19:51:04.8124 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.8131 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.5.self_attn.k_proj', 'model.layers.5.self_attn.v_proj']
2026-10-24T19:51:04.8171 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.8175 | GPTQ | METRIC - error 360.23
2026-10-24T19:51:04.8178 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.8180 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.8182 | GPTQ | METRIC - error 827.36
2026-10-24T19:51:04.8186 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.8194 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.5.self_attn.o_proj']
2026-10-24T19:51:04.8235 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.8238 | GPTQ | METRIC - error 102.97
2026-10-24T19:51:04.8243 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.8252 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.5.mlp.gate_proj', 'model.layers.5.mlp.up_proj']
2026-10-24T19:51:04.8295 | GPTQ | METRIC - time 0.00s

2026-10-24T19:51:04.8298 | GPTQ | METRIC - error 947.28
2026-10-24T19:51:04.8302 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.8303 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.8306 | GPTQ | METRIC - error 955.41
2026-10-24T19:51:04.8309 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.8315 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.5.mlp.down_proj']
2026-10-24T19:51:04.8399 | GPTQ | METRIC - time 0.01s
2026-10-24T19:51:04.8402 | GPTQ | METRIC - error 22.22
2026-10-24T19:51:04.8405 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb

(7/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 980.43it/s]
(8/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 813.19it/s]

2026-10-24T19:51:04.9874 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.6.self_attn.q_proj']
2026-10-24T19:51:04.9903 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.9906 | GPTQ | METRIC - error 2533.49
2026-10-24T19:51:04.9910 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.9917 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.6.self_attn.k_proj', 'model.layers.6.self_attn.v_proj']
2026-10-24T19:51:04.9957 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.9960 | GPTQ | METRIC - error 602.94
2026-10-24T19:51:04.9963 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.9965 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:04.9967 | GPTQ | METRIC - error 644.50
2026-10-24T19:51:04.9971 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:04.9976 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.6.self_attn.o_proj']
2026-10-24T19:51:05.0016 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.0018 | GPTQ | METRIC - error 64.17
2026-10-24T19:51:05.0022 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.0029 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.6.mlp.gate_proj', 'model.layers.6.mlp.up_proj']
2026-10-24T19:51:05.0069 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.0073 | GPTQ | METRIC - error 686.49

2026-10-24T19:51:05.0078 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.0079 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.0081 | GPTQ | METRIC - error 721.41
2026-10-24T19:51:05.0085 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.0091 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.6.mlp.down_proj']
2026-10-24T19:51:05.0176 | GPTQ | METRIC - time 0.01s
2026-10-24T19:51:05.0179 | GPTQ | METRIC - error 5.31
2026-10-24T19:51:05.0183 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb

(8/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 971.19it/s]
(9/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 811.68it/s]

2026-10-24T19:51:05.1660 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.7.self_attn.q_proj']
2026-10-24T19:51:05.1690 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.1692 | GPTQ | METRIC - error 4958.46
2026-10-24T19:51:05.1696 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.1703 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.7.self_attn.k_proj', 'model.layers.7.self_attn.v_proj']
2026-10-24T19:51:05.1743 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.1747 | GPTQ | METRIC - error 1257.51
2026-10-24T19:51:05.1750 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.1752 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.1754 | GPTQ | METRIC - error 1162.59
2026-10-24T19:51:05.1757 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.1763 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.7.self_attn.o_proj']
2026-10-24T19:51:05.1803 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.1806 | GPTQ | METRIC - error 285.87
2026-10-24T19:51:05.1812 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.1825 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.7.mlp.gate_proj', 'model.layers.7.mlp.up_proj']

2026-10-24T19:51:05.1878 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.1880 | GPTQ | METRIC - error 630.55
2026-10-24T19:51:05.1883 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.1884 | GPTQ | METRIC - time 0.01s
2026-10-24T19:51:05.1885 | GPTQ | METRIC - error 710.88
2026-10-24T19:51:05.1887 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.1892 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.7.mlp.down_proj']
2026-10-24T19:51:05.1977 | GPTQ | METRIC - time 0.01s
2026-10-24T19:51:05.1979 | GPTQ | METRIC - error 9.35
2026-10-24T19:51:05.1982 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb

(9/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 1007.05it/s]
(10/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 822.81it/s]

2026-10-24T19:51:05.3424 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.8.self_attn.q_proj']
2026-10-24T19:51:05.3452 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.3455 | GPTQ | METRIC - error 4598.44
2026-10-24T19:51:05.3458 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.3464 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.8.self_attn.k_proj', 'model.layers.8.self_attn.v_proj']
2026-10-24T19:51:05.3503 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.3506 | GPTQ | METRIC - error 1183.29
2026-10-24T19:51:05.3509 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.3510 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.3512 | GPTQ | METRIC - error 1232.63
2026-10-24T19:51:05.3514 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.3519 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.8.self_attn.o_proj']
2026-10-24T19:51:05.3559 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.3561 | GPTQ | METRIC - error 256.19
2026-10-24T19:51:05.3564 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.3573 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.8.mlp.gate_proj', 'model.layers.8.mlp.up_proj']
2026-10-24T19:51:05.3615 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.3618 | GPTQ | METRIC - error 630.87
2026-10-24T19:51:05.3621 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.3622 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.3623 | GPTQ | METRIC - error 688.10
2026-10-24T19:51:05.3625 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.3631 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.8.mlp.down_proj']

2026-10-24T19:51:05.3716 | GPTQ | METRIC - time 0.01s
2026-10-24T19:51:05.3718 | GPTQ | METRIC - error 4.96
2026-10-24T19:51:05.3721 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb

(10/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 966.61it/s]
(11/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 832.91it/s]

2026-10-24T19:51:05.5182 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.9.self_attn.q_proj']
2026-10-24T19:51:05.5213 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.5216 | GPTQ | METRIC - error 3421.78
2026-10-24T19:51:05.5220 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.5227 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.9.self_attn.k_proj', 'model.layers.9.self_attn.v_proj']
2026-10-24T19:51:05.5265 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.5268 | GPTQ | METRIC - error 861.69
2026-10-24T19:51:05.5271 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.5272 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.5273 | GPTQ | METRIC - error 876.27
2026-10-24T19:51:05.5276 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.5281 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.9.self_attn.o_proj']
2026-10-24T19:51:05.5319 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.5321 | GPTQ | METRIC - error 120.56
2026-10-24T19:51:05.5325 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.5331 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.9.mlp.gate_proj', 'model.layers.9.mlp.up_proj']
2026-10-24T19:51:05.5372 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.5375 | GPTQ | METRIC - error 283.65
2026-10-24T19:51:05.5378 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.5379 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.5381 | GPTQ | METRIC - error 325.98
2026-10-24T19:51:05.5383 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.5388 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.9.mlp.down_proj']

2026-10-24T19:51:05.5472 | GPTQ | METRIC - time 0.01s
2026-10-24T19:51:05.5475 | GPTQ | METRIC - error 3.19
2026-10-24T19:51:05.5478 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb

(11/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 967.58it/s]
(12/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 825.64it/s]

2026-10-24T19:51:05.6941 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.10.self_attn.q_proj']
2026-10-24T19:51:05.6970 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.6973 | GPTQ | METRIC - error 4574.32
2026-10-24T19:51:05.6977 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.6983 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.10.self_attn.k_proj', 'model.layers.10.self_attn.v_proj']
2026-10-24T19:51:05.7021 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.7023 | GPTQ | METRIC - error 1274.64
2026-10-24T19:51:05.7026 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.7027 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.7029 | GPTQ | METRIC - error 1035.89
2026-10-24T19:51:05.7031 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.7036 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.10.self_attn.o_proj']
2026-10-24T19:51:05.7075 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.7077 | GPTQ | METRIC - error 387.41
2026-10-24T19:51:05.7079 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.7085 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.10.mlp.gate_proj', 'model.layers.10.mlp.up_proj']
2026-10-24T19:51:05.7125 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.7127 | GPTQ | METRIC - error 495.48
2026-10-24T19:51:05.7130 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.7131 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.7132 | GPTQ | METRIC - error 526.33
2026-10-24T19:51:05.7134 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.7139 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.10.mlp.down_proj']

2026-10-24T19:51:05.7224 | GPTQ | METRIC - time 0.01s
2026-10-24T19:51:05.7228 | GPTQ | METRIC - error 3.95
2026-10-24T19:51:05.7233 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb

(12/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 971.85it/s]
(13/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 792.66it/s]

2026-10-24T19:51:05.8736 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.11.self_attn.q_proj']
2026-10-24T19:51:05.8768 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.8772 | GPTQ | METRIC - error 427.56
2026-10-24T19:51:05.8776 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.8786 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.11.self_attn.k_proj', 'model.layers.11.self_attn.v_proj']
2026-10-24T19:51:05.8827 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.8831 | GPTQ | METRIC - error 154.37
2026-10-24T19:51:05.8836 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.8838 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.8841 | GPTQ | METRIC - error 168.34
2026-10-24T19:51:05.8845 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.8852 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.11.self_attn.o_proj']
2026-10-24T19:51:05.8891 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.8894 | GPTQ | METRIC - error 54.24
2026-10-24T19:51:05.8899 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.8905 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.11.mlp.gate_proj', 'model.layers.11.mlp.up_proj']

2026-10-24T19:51:05.8947 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.8950 | GPTQ | METRIC - error 876.97
2026-10-24T19:51:05.8953 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.8955 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:05.8956 | GPTQ | METRIC - error 959.41
2026-10-24T19:51:05.8959 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:05.8963 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.11.mlp.down_proj']
2026-10-24T19:51:05.9047 | GPTQ | METRIC - time 0.01s
2026-10-24T19:51:05.9049 | GPTQ | METRIC - error 16.71
2026-10-24T19:51:05.9052 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb

(13/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 993.64it/s]
(14/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 830.14it/s]

2026-10-24T19:51:06.0494 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.12.self_attn.q_proj']
2026-10-24T19:51:06.0523 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.0527 | GPTQ | METRIC - error 4569.22
2026-10-24T19:51:06.0531 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.0538 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.12.self_attn.k_proj', 'model.layers.12.self_attn.v_proj']
2026-10-24T19:51:06.0578 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.0581 | GPTQ | METRIC - error 1987.60
2026-10-24T19:51:06.0584 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.0586 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.0588 | GPTQ | METRIC - error 1194.02
2026-10-24T19:51:06.0592 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.0597 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.12.self_attn.o_proj']
2026-10-24T19:51:06.0636 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.0639 | GPTQ | METRIC - error 305.02
2026-10-24T19:51:06.0642 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.0649 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.12.mlp.gate_proj', 'model.layers.12.mlp.up_proj']
2026-10-24T19:51:06.0689 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.0692 | GPTQ | METRIC - error 465.83
2026-10-24T19:51:06.0697 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.0699 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.0701 | GPTQ | METRIC - error 480.19
2026-10-24T19:51:06.0704 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.0710 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.12.mlp.down_proj']

2026-10-24T19:51:06.0797 | GPTQ | METRIC - time 0.01s
2026-10-24T19:51:06.0799 | GPTQ | METRIC - error 7.36
2026-10-24T19:51:06.0803 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb

(14/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 982.73it/s]
(15/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 824.02it/s]

2026-10-24T19:51:06.2261 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.13.self_attn.q_proj']
2026-10-24T19:51:06.2290 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.2293 | GPTQ | METRIC - error 6046.04
2026-10-24T19:51:06.2297 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.2304 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.13.self_attn.k_proj', 'model.layers.13.self_attn.v_proj']
2026-10-24T19:51:06.2344 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.2347 | GPTQ | METRIC - error 1654.39
2026-10-24T19:51:06.2350 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.2352 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.2354 | GPTQ | METRIC - error 1886.62
2026-10-24T19:51:06.2358 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.2364 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.13.self_attn.o_proj']
2026-10-24T19:51:06.2404 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.2407 | GPTQ | METRIC - error 355.15
2026-10-24T19:51:06.2410 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.2417 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.13.mlp.gate_proj', 'model.layers.13.mlp.up_proj']
2026-10-24T19:51:06.2458 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.2460 | GPTQ | METRIC - error 320.16
2026-10-24T19:51:06.2464 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.2466 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.2468 | GPTQ | METRIC - error 360.18
2026-10-24T19:51:06.2471 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.2477 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.13.mlp.down_proj']

2026-10-24T19:51:06.2563 | GPTQ | METRIC - time 0.01s
2026-10-24T19:51:06.2566 | GPTQ | METRIC - error 3.15
2026-10-24T19:51:06.2570 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb

(15/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 985.58it/s]
(16/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 830.55it/s]

2026-10-24T19:51:06.4019 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.14.self_attn.q_proj']
2026-10-24T19:51:06.4048 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.4050 | GPTQ | METRIC - error 6777.19
2026-10-24T19:51:06.4055 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.4061 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.14.self_attn.k_proj', 'model.layers.14.self_attn.v_proj']
2026-10-24T19:51:06.4101 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.4104 | GPTQ | METRIC - error 2192.65
2026-10-24T19:51:06.4108 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.4110 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.4112 | GPTQ | METRIC - error 1641.25
2026-10-24T19:51:06.4115 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.4121 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.14.self_attn.o_proj']
2026-10-24T19:51:06.4160 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.4163 | GPTQ | METRIC - error 306.35
2026-10-24T19:51:06.4167 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.4174 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.14.mlp.gate_proj', 'model.layers.14.mlp.up_proj']
2026-10-24T19:51:06.4214 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.4217 | GPTQ | METRIC - error 267.91
2026-10-24T19:51:06.4221 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.4222 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.4224 | GPTQ | METRIC - error 303.86
2026-10-24T19:51:06.4228 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.4234 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.14.mlp.down_proj']

2026-10-24T19:51:06.4321 | GPTQ | METRIC - time 0.01s
2026-10-24T19:51:06.4323 | GPTQ | METRIC - error 1.74
2026-10-24T19:51:06.4327 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb

(16/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 994.14it/s]
(17/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 840.49it/s]

2026-10-24T19:51:06.5760 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.15.self_attn.q_proj']
2026-10-24T19:51:06.5789 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.5791 | GPTQ | METRIC - error 7910.98
2026-10-24T19:51:06.5795 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.5802 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.15.self_attn.k_proj', 'model.layers.15.self_attn.v_proj']
2026-10-24T19:51:06.5841 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.5844 | GPTQ | METRIC - error 2309.07
2026-10-24T19:51:06.5848 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.5849 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.5851 | GPTQ | METRIC - error 1874.68
2026-10-24T19:51:06.5855 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.5861 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.15.self_attn.o_proj']
2026-10-24T19:51:06.5900 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.5902 | GPTQ | METRIC - error 716.07
2026-10-24T19:51:06.5906 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.5913 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.15.mlp.gate_proj', 'model.layers.15.mlp.up_proj']
2026-10-24T19:51:06.5955 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.5957 | GPTQ | METRIC - error 180.99
2026-10-24T19:51:06.5961 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.5963 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.5965 | GPTQ | METRIC - error 200.03
2026-10-24T19:51:06.5968 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.5974 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.15.mlp.down_proj']

2026-10-24T19:51:06.6059 | GPTQ | METRIC - time 0.01s
2026-10-24T19:51:06.6062 | GPTQ | METRIC - error 1.17
2026-10-24T19:51:06.6066 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb

(17/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 978.51it/s]
(18/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 829.72it/s]

2026-10-24T19:51:06.7525 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.16.self_attn.q_proj']
2026-10-24T19:51:06.7556 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.7560 | GPTQ | METRIC - error 11399.07
2026-10-24T19:51:06.7565 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.7572 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.16.self_attn.k_proj', 'model.layers.16.self_attn.v_proj']
2026-10-24T19:51:06.7611 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.7615 | GPTQ | METRIC - error 3087.04
2026-10-24T19:51:06.7618 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.7620 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.7622 | GPTQ | METRIC - error 3026.70
2026-10-24T19:51:06.7624 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.7628 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.16.self_attn.o_proj']
2026-10-24T19:51:06.7665 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.7667 | GPTQ | METRIC - error 547.97
2026-10-24T19:51:06.7670 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.7674 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.16.mlp.gate_proj', 'model.layers.16.mlp.up_proj']
2026-10-24T19:51:06.7713 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.7715 | GPTQ | METRIC - error 175.79
2026-10-24T19:51:06.7717 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.7719 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.7720 | GPTQ | METRIC - error 193.59
2026-10-24T19:51:06.7722 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.7727 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.16.mlp.down_proj']

2026-10-24T19:51:06.7810 | GPTQ | METRIC - time 0.01s
2026-10-24T19:51:06.7812 | GPTQ | METRIC - error 1.87
2026-10-24T19:51:06.7815 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb

(18/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 1010.85it/s]
(19/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 803.32it/s]

2026-10-24T19:51:06.9272 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.17.self_attn.q_proj']
2026-10-24T19:51:06.9300 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.9303 | GPTQ | METRIC - error 2845.55
2026-10-24T19:51:06.9306 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.9313 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.17.self_attn.k_proj', 'model.layers.17.self_attn.v_proj']
2026-10-24T19:51:06.9351 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.9354 | GPTQ | METRIC - error 873.23
2026-10-24T19:51:06.9358 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.9360 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.9361 | GPTQ | METRIC - error 933.34
2026-10-24T19:51:06.9364 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.9369 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.17.self_attn.o_proj']
2026-10-24T19:51:06.9408 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.9411 | GPTQ | METRIC - error 324.05
2026-10-24T19:51:06.9414 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.9420 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.17.mlp.gate_proj', 'model.layers.17.mlp.up_proj']
2026-10-24T19:51:06.9460 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.9463 | GPTQ | METRIC - error 268.59
2026-10-24T19:51:06.9467 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.9468 | GPTQ | METRIC - time 0.00s
2026-10-24T19:51:06.9470 | GPTQ | METRIC - error 274.49
2026-10-24T19:51:06.9474 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb
2026-10-24T19:51:06.9479 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.17.mlp.down_proj']

2026-10-24T19:51:06.9562 | GPTQ | METRIC - time 0.01s
2026-10-24T19:51:06.9566 | GPTQ | METRIC - error 3.25
2026-10-24T19:51:06.9569 | GPTQ | METRIC - Accelerator 0 | usage: 19.85% | total memory: 16.7 Gb

(19/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 1016.37it/s]

2026-10-24T19:51:07.0247 | norm_calibration_context | INFO - Restoring 109 norm modules to offset convention
2026-10-24T19:51:07.0270 | finalize | INFO - Compression lifecycle finalized for 1 modifiers

2026-10-24T19:55:06.5658 | reset | INFO - Compression lifecycle reset

Testing: {'actorder': None, 'dampening_frac': 0.05}

Loading weights: 100%|██████████| 236/236 [00:00<00:00, 5669.54it/s]

2026-10-24T19:55:07.7249 | reset | INFO - Compression lifecycle reset
2026-10-24T19:55:07.7286 | norm_calibration_context | INFO - Found 109 offset-norm modules to convert
2026-10-24T19:55:07.7320 | from_modifiers | INFO - Creating recipe from modifiers

Applying quantization config: 100%|██████████| 126/126 [00:00<00:00, 15587.15it/s]

2026-10-24T19:55:07.7443 | initialize | INFO - Compression lifecycle initialized for 1 modifiers
2026-10-24T19:55:07.7445 | IndependentPipeline | INFO - Inferred `SequentialPipeline` for `GPTQModifier`

Preparing cache: 100%|██████████| 64/64 [00:00<00:00, 5418.12it/s]
(1/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 1446.82it/s]
(1/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 654.43it/s]
(2/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 803.90it/s]

2026-10-24T19:55:08.0211 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.0.self_attn.q_proj']
2026-10-24T19:55:08.0245 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.0248 | GPTQ | METRIC - error 269600.06
2026-10-24T19:55:08.0252 | GPTQ | METRIC - Accelerator 0 | usage: 26.13% | total memory: 16.7 Gb
2026-10-24T19:55:08.0258 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.0.self_attn.k_proj', 'model.layers.0.self_attn.v_proj']
2026-10-24T19:55:08.0296 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.0298 | GPTQ | METRIC - error 58609.25
2026-10-24T19:55:08.0301 | GPTQ | METRIC - Accelerator 0 | usage: 26.13% | total memory: 16.7 Gb
2026-10-24T19:55:08.0302 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.0303 | GPTQ | METRIC - error 69638.32
2026-10-24T19:55:08.0306 | GPTQ | METRIC - Accelerator 0 | usage: 26.13% | total memory: 16.7 Gb
2026-10-24T19:55:08.0310 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.0.self_attn.o_proj']
2026-10-24T19:55:08.0348 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.0351 | GPTQ | METRIC - error 52268.81
2026-10-24T19:55:08.0354 | GPTQ | METRIC - Accelerator 0 | usage: 26.13% | total memory: 16.7 Gb
2026-10-24T19:55:08.0360 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.0.mlp.gate_proj', 'model.layers.0.mlp.up_proj']
2026-10-24T19:55:08.0401 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.0403 | GPTQ | METRIC - error 12389.71
2026-10-24T19:55:08.0406 | GPTQ | METRIC - Accelerator 0 | usage: 26.13% | total memory: 16.7 Gb
2026-10-24T19:55:08.0407 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.0408 | GPTQ | METRIC - error 13287.21

2026-10-24T19:55:08.0411 | GPTQ | METRIC - Accelerator 0 | usage: 26.13% | total memory: 16.7 Gb
2026-10-24T19:55:08.0417 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.0.mlp.down_proj']
2026-10-24T19:55:08.0502 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:08.0505 | GPTQ | METRIC - error 3347.02
2026-10-24T19:55:08.0508 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb

(2/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 969.04it/s]
(3/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 816.24it/s]

2026-10-24T19:55:08.1980 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.1.self_attn.q_proj']
2026-10-24T19:55:08.2010 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.2012 | GPTQ | METRIC - error 124120.33
2026-10-24T19:55:08.2015 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.2021 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.1.self_attn.k_proj', 'model.layers.1.self_attn.v_proj']
2026-10-24T19:55:08.2059 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.2061 | GPTQ | METRIC - error 29137.64
2026-10-24T19:55:08.2064 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.2065 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.2067 | GPTQ | METRIC - error 28043.88
2026-10-24T19:55:08.2070 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.2074 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.1.self_attn.o_proj']
2026-10-24T19:55:08.2112 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.2114 | GPTQ | METRIC - error 6265.52
2026-10-24T19:55:08.2117 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.2123 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.1.mlp.gate_proj', 'model.layers.1.mlp.up_proj']
2026-10-24T19:55:08.2163 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.2166 | GPTQ | METRIC - error 4071.47
2026-10-24T19:55:08.2169 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.2171 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.2172 | GPTQ | METRIC - error 4163.22
2026-10-24T19:55:08.2175 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.2180 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.1.mlp.down_proj']

2026-10-24T19:55:08.2263 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:08.2265 | GPTQ | METRIC - error 114.89
2026-10-24T19:55:08.2268 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb

(3/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 965.15it/s]
(4/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 813.90it/s]

2026-10-24T19:55:08.3742 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.2.self_attn.q_proj']
2026-10-24T19:55:08.3770 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.3772 | GPTQ | METRIC - error 4965.85
2026-10-24T19:55:08.3775 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.3781 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.2.self_attn.k_proj', 'model.layers.2.self_attn.v_proj']
2026-10-24T19:55:08.3820 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.3823 | GPTQ | METRIC - error 1149.70
2026-10-24T19:55:08.3827 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.3828 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.3830 | GPTQ | METRIC - error 1149.65
2026-10-24T19:55:08.3833 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.3837 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.2.self_attn.o_proj']
2026-10-24T19:55:08.3877 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.3878 | GPTQ | METRIC - error 541.88
2026-10-24T19:55:08.3881 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.3887 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.2.mlp.gate_proj', 'model.layers.2.mlp.up_proj']
2026-10-24T19:55:08.3927 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.3929 | GPTQ | METRIC - error 2449.59
2026-10-24T19:55:08.3931 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.3933 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.3934 | GPTQ | METRIC - error 2481.00
2026-10-24T19:55:08.3936 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.3941 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.2.mlp.down_proj']

2026-10-24T19:55:08.4025 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:08.4028 | GPTQ | METRIC - error 54.82
2026-10-24T19:55:08.4030 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb

(4/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 973.25it/s]
(5/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 816.15it/s]

2026-10-24T19:55:08.5498 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.3.self_attn.q_proj']
2026-10-24T19:55:08.5526 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.5528 | GPTQ | METRIC - error 3889.30
2026-10-24T19:55:08.5531 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.5537 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.3.self_attn.k_proj', 'model.layers.3.self_attn.v_proj']
2026-10-24T19:55:08.5574 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.5576 | GPTQ | METRIC - error 903.66
2026-10-24T19:55:08.5579 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.5581 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.5582 | GPTQ | METRIC - error 1135.31
2026-10-24T19:55:08.5585 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.5589 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.3.self_attn.o_proj']
2026-10-24T19:55:08.5627 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.5630 | GPTQ | METRIC - error 168.97
2026-10-24T19:55:08.5633 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.5639 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.3.mlp.gate_proj', 'model.layers.3.mlp.up_proj']
2026-10-24T19:55:08.5680 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.5683 | GPTQ | METRIC - error 2176.21
2026-10-24T19:55:08.5686 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.5687 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.5688 | GPTQ | METRIC - error 2128.58
2026-10-24T19:55:08.5691 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.5695 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.3.mlp.down_proj']

2026-10-24T19:55:08.5779 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:08.5781 | GPTQ | METRIC - error 60.66
2026-10-24T19:55:08.5783 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb

(5/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 968.19it/s]
(6/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 810.95it/s]

2026-10-24T19:55:08.7259 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.4.self_attn.q_proj']
2026-10-24T19:55:08.7289 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.7292 | GPTQ | METRIC - error 3137.38
2026-10-24T19:55:08.7297 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.7305 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.4.self_attn.k_proj', 'model.layers.4.self_attn.v_proj']
2026-10-24T19:55:08.7346 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.7348 | GPTQ | METRIC - error 826.69
2026-10-24T19:55:08.7351 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.7352 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.7353 | GPTQ | METRIC - error 716.74
2026-10-24T19:55:08.7356 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.7361 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.4.self_attn.o_proj']
2026-10-24T19:55:08.7398 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.7400 | GPTQ | METRIC - error 95.28
2026-10-24T19:55:08.7403 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.7408 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.4.mlp.gate_proj', 'model.layers.4.mlp.up_proj']
2026-10-24T19:55:08.7448 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.7449 | GPTQ | METRIC - error 1513.64
2026-10-24T19:55:08.7452 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.7453 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.7454 | GPTQ | METRIC - error 1564.72
2026-10-24T19:55:08.7457 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.7461 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.4.mlp.down_proj']

2026-10-24T19:55:08.7544 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:08.7547 | GPTQ | METRIC - error 11.04
2026-10-24T19:55:08.7549 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb

(6/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 1035.79it/s]
(7/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 771.65it/s]

2026-10-24T19:55:08.9024 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.5.self_attn.q_proj']
2026-10-24T19:55:08.9053 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.9056 | GPTQ | METRIC - error 1564.07
2026-10-24T19:55:08.9059 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.9065 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.5.self_attn.k_proj', 'model.layers.5.self_attn.v_proj']
2026-10-24T19:55:08.9104 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.9106 | GPTQ | METRIC - error 440.91
2026-10-24T19:55:08.9109 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.9111 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.9114 | GPTQ | METRIC - error 1001.35
2026-10-24T19:55:08.9117 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.9122 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.5.self_attn.o_proj']
2026-10-24T19:55:08.9160 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.9163 | GPTQ | METRIC - error 140.43
2026-10-24T19:55:08.9167 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.9172 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.5.mlp.gate_proj', 'model.layers.5.mlp.up_proj']
2026-10-24T19:55:08.9214 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.9216 | GPTQ | METRIC - error 1090.24
2026-10-24T19:55:08.9220 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.9221 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:08.9223 | GPTQ | METRIC - error 1102.88
2026-10-24T19:55:08.9225 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:08.9230 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.5.mlp.down_proj']

2026-10-24T19:55:08.9313 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:08.9316 | GPTQ | METRIC - error 27.70
2026-10-24T19:55:08.9319 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb

(7/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 976.45it/s]
(8/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 841.69it/s]

2026-10-24T19:55:09.0766 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.6.self_attn.q_proj']
2026-10-24T19:55:09.0795 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.0798 | GPTQ | METRIC - error 2867.33
2026-10-24T19:55:09.0801 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.0807 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.6.self_attn.k_proj', 'model.layers.6.self_attn.v_proj']
2026-10-24T19:55:09.0845 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.0848 | GPTQ | METRIC - error 684.35
2026-10-24T19:55:09.0851 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.0852 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.0854 | GPTQ | METRIC - error 731.74
2026-10-24T19:55:09.0857 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.0861 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.6.self_attn.o_proj']
2026-10-24T19:55:09.0899 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.0901 | GPTQ | METRIC - error 95.75
2026-10-24T19:55:09.0904 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.0909 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.6.mlp.gate_proj', 'model.layers.6.mlp.up_proj']
2026-10-24T19:55:09.0948 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.0950 | GPTQ | METRIC - error 783.91
2026-10-24T19:55:09.0952 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.0954 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.0955 | GPTQ | METRIC - error 825.31
2026-10-24T19:55:09.0957 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.0962 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.6.mlp.down_proj']

2026-10-24T19:55:09.1046 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:09.1048 | GPTQ | METRIC - error 6.52
2026-10-24T19:55:09.1051 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb

(8/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 973.87it/s]
(9/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 812.61it/s]

2026-10-24T19:55:09.2521 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.7.self_attn.q_proj']
2026-10-24T19:55:09.2548 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.2550 | GPTQ | METRIC - error 6154.98
2026-10-24T19:55:09.2554 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.2559 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.7.self_attn.k_proj', 'model.layers.7.self_attn.v_proj']
2026-10-24T19:55:09.2598 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.2599 | GPTQ | METRIC - error 1576.13
2026-10-24T19:55:09.2602 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.2604 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.2605 | GPTQ | METRIC - error 1443.45
2026-10-24T19:55:09.2608 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.2613 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.7.self_attn.o_proj']
2026-10-24T19:55:09.2652 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.2655 | GPTQ | METRIC - error 452.68
2026-10-24T19:55:09.2658 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.2664 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.7.mlp.gate_proj', 'model.layers.7.mlp.up_proj']
2026-10-24T19:55:09.2704 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.2706 | GPTQ | METRIC - error 739.55
2026-10-24T19:55:09.2708 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.2709 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.2710 | GPTQ | METRIC - error 828.25
2026-10-24T19:55:09.2713 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.2717 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.7.mlp.down_proj']

2026-10-24T19:55:09.2799 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:09.2801 | GPTQ | METRIC - error 13.56
2026-10-24T19:55:09.2804 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb

(9/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 1029.17it/s]
(10/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 824.87it/s]

2026-10-24T19:55:09.4229 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.8.self_attn.q_proj']
2026-10-24T19:55:09.4256 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.4258 | GPTQ | METRIC - error 6038.71
2026-10-24T19:55:09.4261 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.4267 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.8.self_attn.k_proj', 'model.layers.8.self_attn.v_proj']
2026-10-24T19:55:09.4305 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.4307 | GPTQ | METRIC - error 1533.81
2026-10-24T19:55:09.4309 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.4311 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.4312 | GPTQ | METRIC - error 1642.76
2026-10-24T19:55:09.4316 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.4322 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.8.self_attn.o_proj']
2026-10-24T19:55:09.4360 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.4363 | GPTQ | METRIC - error 350.44
2026-10-24T19:55:09.4366 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.4371 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.8.mlp.gate_proj', 'model.layers.8.mlp.up_proj']
2026-10-24T19:55:09.4411 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.4413 | GPTQ | METRIC - error 752.73
2026-10-24T19:55:09.4417 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.4419 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.4420 | GPTQ | METRIC - error 827.06
2026-10-24T19:55:09.4423 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.4427 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.8.mlp.down_proj']
2026-10-24T19:55:09.4510 | GPTQ | METRIC - time 0.01s

2026-10-24T19:55:09.4513 | GPTQ | METRIC - error 6.57
2026-10-24T19:55:09.4516 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb

(10/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 1015.29it/s]
(11/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 832.14it/s]

2026-10-24T19:55:09.5947 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.9.self_attn.q_proj']
2026-10-24T19:55:09.5975 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.5976 | GPTQ | METRIC - error 4561.12
2026-10-24T19:55:09.5979 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.5986 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.9.self_attn.k_proj', 'model.layers.9.self_attn.v_proj']
2026-10-24T19:55:09.6024 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.6026 | GPTQ | METRIC - error 1136.59
2026-10-24T19:55:09.6029 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.6030 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.6032 | GPTQ | METRIC - error 1158.26
2026-10-24T19:55:09.6035 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.6039 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.9.self_attn.o_proj']
2026-10-24T19:55:09.6077 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.6078 | GPTQ | METRIC - error 180.32
2026-10-24T19:55:09.6081 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.6087 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.9.mlp.gate_proj', 'model.layers.9.mlp.up_proj']
2026-10-24T19:55:09.6125 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.6126 | GPTQ | METRIC - error 333.98
2026-10-24T19:55:09.6129 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.6131 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.6132 | GPTQ | METRIC - error 380.87
2026-10-24T19:55:09.6134 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.6138 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.9.mlp.down_proj']

2026-10-24T19:55:09.6224 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:09.6226 | GPTQ | METRIC - error 4.41
2026-10-24T19:55:09.6229 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb

(11/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 990.48it/s]
(12/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 811.33it/s]

2026-10-24T19:55:09.7690 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.10.self_attn.q_proj']
2026-10-24T19:55:09.7718 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.7719 | GPTQ | METRIC - error 6157.26
2026-10-24T19:55:09.7723 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.7728 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.10.self_attn.k_proj', 'model.layers.10.self_attn.v_proj']
2026-10-24T19:55:09.7766 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.7767 | GPTQ | METRIC - error 1747.12
2026-10-24T19:55:09.7770 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.7772 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.7773 | GPTQ | METRIC - error 1426.49
2026-10-24T19:55:09.7776 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.7780 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.10.self_attn.o_proj']
2026-10-24T19:55:09.7819 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.7821 | GPTQ | METRIC - error 568.75
2026-10-24T19:55:09.7824 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.7829 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.10.mlp.gate_proj', 'model.layers.10.mlp.up_proj']
2026-10-24T19:55:09.7869 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.7871 | GPTQ | METRIC - error 615.44
2026-10-24T19:55:09.7874 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.7875 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.7877 | GPTQ | METRIC - error 654.08
2026-10-24T19:55:09.7879 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.7884 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.10.mlp.down_proj']

2026-10-24T19:55:09.7966 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:09.7967 | GPTQ | METRIC - error 5.86
2026-10-24T19:55:09.7970 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb

(12/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 973.84it/s]
(13/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 815.41it/s]

2026-10-24T19:55:09.9437 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.11.self_attn.q_proj']
2026-10-24T19:55:09.9465 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.9467 | GPTQ | METRIC - error 509.86
2026-10-24T19:55:09.9471 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.9477 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.11.self_attn.k_proj', 'model.layers.11.self_attn.v_proj']
2026-10-24T19:55:09.9516 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.9518 | GPTQ | METRIC - error 189.33
2026-10-24T19:55:09.9521 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.9523 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.9524 | GPTQ | METRIC - error 206.33
2026-10-24T19:55:09.9527 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.9531 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.11.self_attn.o_proj']
2026-10-24T19:55:09.9568 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.9570 | GPTQ | METRIC - error 69.81
2026-10-24T19:55:09.9573 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.9578 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.11.mlp.gate_proj', 'model.layers.11.mlp.up_proj']
2026-10-24T19:55:09.9616 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.9619 | GPTQ | METRIC - error 1053.38
2026-10-24T19:55:09.9622 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.9623 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:09.9624 | GPTQ | METRIC - error 1155.33
2026-10-24T19:55:09.9627 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:09.9631 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.11.mlp.down_proj']

2026-10-24T19:55:09.9715 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:09.9718 | GPTQ | METRIC - error 23.32
2026-10-24T19:55:09.9720 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb

(13/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 968.60it/s]
(14/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 812.38it/s]

2026-10-24T19:55:10.1194 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.12.self_attn.q_proj']
2026-10-24T19:55:10.1221 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.1223 | GPTQ | METRIC - error 5340.31
2026-10-24T19:55:10.1226 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.1232 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.12.self_attn.k_proj', 'model.layers.12.self_attn.v_proj']
2026-10-24T19:55:10.1270 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.1272 | GPTQ | METRIC - error 2314.75
2026-10-24T19:55:10.1275 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.1276 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.1277 | GPTQ | METRIC - error 1397.93
2026-10-24T19:55:10.1280 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.1285 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.12.self_attn.o_proj']
2026-10-24T19:55:10.1323 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.1326 | GPTQ | METRIC - error 355.79
2026-10-24T19:55:10.1329 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.1335 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.12.mlp.gate_proj', 'model.layers.12.mlp.up_proj']
2026-10-24T19:55:10.1374 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.1376 | GPTQ | METRIC - error 555.84
2026-10-24T19:55:10.1379 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.1380 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.1381 | GPTQ | METRIC - error 572.23
2026-10-24T19:55:10.1384 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.1388 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.12.mlp.down_proj']

2026-10-24T19:55:10.1471 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:10.1473 | GPTQ | METRIC - error 10.49
2026-10-24T19:55:10.1476 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb

(14/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 961.38it/s]
(15/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 842.16it/s]

2026-10-24T19:55:10.2930 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.13.self_attn.q_proj']
2026-10-24T19:55:10.2958 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.2961 | GPTQ | METRIC - error 8890.33
2026-10-24T19:55:10.2965 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.2972 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.13.self_attn.k_proj', 'model.layers.13.self_attn.v_proj']
2026-10-24T19:55:10.3012 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.3014 | GPTQ | METRIC - error 2442.21
2026-10-24T19:55:10.3018 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.3019 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.3021 | GPTQ | METRIC - error 2776.80
2026-10-24T19:55:10.3023 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.3028 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.13.self_attn.o_proj']
2026-10-24T19:55:10.3065 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.3068 | GPTQ | METRIC - error 431.53
2026-10-24T19:55:10.3070 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.3075 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.13.mlp.gate_proj', 'model.layers.13.mlp.up_proj']
2026-10-24T19:55:10.3113 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.3115 | GPTQ | METRIC - error 367.13
2026-10-24T19:55:10.3118 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.3119 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.3120 | GPTQ | METRIC - error 413.93
2026-10-24T19:55:10.3123 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.3127 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.13.mlp.down_proj']

2026-10-24T19:55:10.3213 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:10.3215 | GPTQ | METRIC - error 4.26
2026-10-24T19:55:10.3218 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb

(15/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 1007.80it/s]
(16/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 823.96it/s]

2026-10-24T19:55:10.4659 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.14.self_attn.q_proj']
2026-10-24T19:55:10.4687 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.4689 | GPTQ | METRIC - error 8083.18
2026-10-24T19:55:10.4692 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.4698 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.14.self_attn.k_proj', 'model.layers.14.self_attn.v_proj']
2026-10-24T19:55:10.4735 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.4738 | GPTQ | METRIC - error 2599.63
2026-10-24T19:55:10.4741 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.4742 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.4743 | GPTQ | METRIC - error 1974.58
2026-10-24T19:55:10.4746 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.4750 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.14.self_attn.o_proj']
2026-10-24T19:55:10.4788 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.4790 | GPTQ | METRIC - error 409.89
2026-10-24T19:55:10.4793 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.4798 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.14.mlp.gate_proj', 'model.layers.14.mlp.up_proj']
2026-10-24T19:55:10.4839 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.4842 | GPTQ | METRIC - error 310.61
2026-10-24T19:55:10.4845 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.4846 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.4847 | GPTQ | METRIC - error 351.61
2026-10-24T19:55:10.4850 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.4855 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.14.mlp.down_proj']

2026-10-24T19:55:10.4938 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:10.4940 | GPTQ | METRIC - error 2.44
2026-10-24T19:55:10.4942 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb

(16/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 984.51it/s]
(17/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 821.32it/s]

2026-10-24T19:55:10.6399 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.15.self_attn.q_proj']
2026-10-24T19:55:10.6428 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.6430 | GPTQ | METRIC - error 9449.26
2026-10-24T19:55:10.6435 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.6441 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.15.self_attn.k_proj', 'model.layers.15.self_attn.v_proj']
2026-10-24T19:55:10.6480 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.6482 | GPTQ | METRIC - error 2759.58
2026-10-24T19:55:10.6485 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.6487 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.6488 | GPTQ | METRIC - error 2252.37
2026-10-24T19:55:10.6491 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.6495 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.15.self_attn.o_proj']
2026-10-24T19:55:10.6534 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.6535 | GPTQ | METRIC - error 943.63
2026-10-24T19:55:10.6538 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.6543 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.15.mlp.gate_proj', 'model.layers.15.mlp.up_proj']
2026-10-24T19:55:10.6582 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.6583 | GPTQ | METRIC - error 211.33
2026-10-24T19:55:10.6586 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.6587 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.6588 | GPTQ | METRIC - error 232.66
2026-10-24T19:55:10.6591 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.6595 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.15.mlp.down_proj']

2026-10-24T19:55:10.6682 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:10.6684 | GPTQ | METRIC - error 1.80
2026-10-24T19:55:10.6687 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb

(17/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 982.43it/s]
(18/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 812.83it/s]

2026-10-24T19:55:10.8153 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.16.self_attn.q_proj']
2026-10-24T19:55:10.8183 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.8186 | GPTQ | METRIC - error 13597.33
2026-10-24T19:55:10.8189 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.8195 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.16.self_attn.k_proj', 'model.layers.16.self_attn.v_proj']
2026-10-24T19:55:10.8233 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.8235 | GPTQ | METRIC - error 3694.10
2026-10-24T19:55:10.8238 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.8239 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.8240 | GPTQ | METRIC - error 3636.47
2026-10-24T19:55:10.8243 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.8248 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.16.self_attn.o_proj']
2026-10-24T19:55:10.8287 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.8288 | GPTQ | METRIC - error 782.09
2026-10-24T19:55:10.8291 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.8296 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.16.mlp.gate_proj', 'model.layers.16.mlp.up_proj']
2026-10-24T19:55:10.8335 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.8338 | GPTQ | METRIC - error 207.91
2026-10-24T19:55:10.8342 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.8344 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.8345 | GPTQ | METRIC - error 228.65
2026-10-24T19:55:10.8349 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:10.8353 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.16.mlp.down_proj']

2026-10-24T19:55:10.8436 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:10.8438 | GPTQ | METRIC - error 2.58
2026-10-24T19:55:10.8441 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb

(18/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 956.47it/s]
(19/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 779.40it/s]

2026-10-24T19:55:10.9959 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.17.self_attn.q_proj']
2026-10-24T19:55:10.9991 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:10.9995 | GPTQ | METRIC - error 3677.81
2026-10-24T19:55:10.9999 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:11.0006 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.17.self_attn.k_proj', 'model.layers.17.self_attn.v_proj']
2026-10-24T19:55:11.0045 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:11.0047 | GPTQ | METRIC - error 1120.16
2026-10-24T19:55:11.0050 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:11.0051 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:11.0052 | GPTQ | METRIC - error 1198.93
2026-10-24T19:55:11.0055 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:11.0059 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.17.self_attn.o_proj']
2026-10-24T19:55:11.0097 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:11.0099 | GPTQ | METRIC - error 403.60
2026-10-24T19:55:11.0101 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:11.0106 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.17.mlp.gate_proj', 'model.layers.17.mlp.up_proj']
2026-10-24T19:55:11.0145 | GPTQ | METRIC - time 0.00s

2026-10-24T19:55:11.0147 | GPTQ | METRIC - error 353.10
2026-10-24T19:55:11.0150 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:11.0152 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:11.0153 | GPTQ | METRIC - error 361.04
2026-10-24T19:55:11.0156 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb
2026-10-24T19:55:11.0162 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.17.mlp.down_proj']
2026-10-24T19:55:11.0245 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:11.0248 | GPTQ | METRIC - error 4.83
2026-10-24T19:55:11.0251 | GPTQ | METRIC - Accelerator 0 | usage: 26.29% | total memory: 16.7 Gb

(19/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 1043.09it/s]

2026-10-24T19:55:11.0908 | norm_calibration_context | INFO - Restoring 109 norm modules to offset convention
2026-10-24T19:55:11.0929 | finalize | INFO - Compression lifecycle finalized for 1 modifiers

2026-10-24T19:55:23.2173 | reset | INFO - Compression lifecycle reset

Testing: {'actorder': None, 'dampening_frac': 0.1}

Loading weights: 100%|██████████| 236/236 [00:00<00:00, 6341.73it/s]

2026-10-24T19:55:34.3460 | reset | INFO - Compression lifecycle reset
2026-10-24T19:55:34.3495 | norm_calibration_context | INFO - Found 109 offset-norm modules to convert
2026-10-24T19:55:34.3523 | from_modifiers | INFO - Creating recipe from modifiers

Applying quantization config: 100%|██████████| 126/126 [00:00<00:00, 15534.92it/s]

2026-10-24T19:55:34.3648 | initialize | INFO - Compression lifecycle initialized for 1 modifiers
2026-10-24T19:55:34.3651 | IndependentPipeline | INFO - Inferred `SequentialPipeline` for `GPTQModifier`

Preparing cache: 100%|██████████| 64/64 [00:00<00:00, 5081.31it/s]
(1/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 1442.87it/s]
(1/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 658.47it/s]
(2/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 805.08it/s]

2026-10-24T19:55:34.6424 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.0.self_attn.q_proj']
2026-10-24T19:55:34.6456 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:34.6459 | GPTQ | METRIC - error 337895.94
2026-10-24T19:55:34.6462 | GPTQ | METRIC - Accelerator 0 | usage: 32.56% | total memory: 16.7 Gb
2026-10-24T19:55:34.6468 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.0.self_attn.k_proj', 'model.layers.0.self_attn.v_proj']
2026-10-24T19:55:34.6507 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:34.6508 | GPTQ | METRIC - error 73580.51
2026-10-24T19:55:34.6511 | GPTQ | METRIC - Accelerator 0 | usage: 32.56% | total memory: 16.7 Gb
2026-10-24T19:55:34.6513 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:34.6514 | GPTQ | METRIC - error 87008.29
2026-10-24T19:55:34.6517 | GPTQ | METRIC - Accelerator 0 | usage: 32.56% | total memory: 16.7 Gb
2026-10-24T19:55:34.6522 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.0.self_attn.o_proj']
2026-10-24T19:55:34.6561 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:34.6562 | GPTQ | METRIC - error 63721.51
2026-10-24T19:55:34.6565 | GPTQ | METRIC - Accelerator 0 | usage: 32.56% | total memory: 16.7 Gb
2026-10-24T19:55:34.6571 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.0.mlp.gate_proj', 'model.layers.0.mlp.up_proj']
2026-10-24T19:55:34.6612 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:34.6614 | GPTQ | METRIC - error 14304.16
2026-10-24T19:55:34.6616 | GPTQ | METRIC - Accelerator 0 | usage: 32.57% | total memory: 16.7 Gb
2026-10-24T19:55:34.6617 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:34.6618 | GPTQ | METRIC - error 15342.76
2026-10-24T19:55:34.6622 | GPTQ | METRIC - Accelerator 0 | usage: 32.57% | total memory: 16.7 Gb
2026-10-24T19:55:34.6627 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.0.mlp.down_proj']

2026-10-24T19:55:34.6713 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:34.6715 | GPTQ | METRIC - error 4035.97
2026-10-24T19:55:34.6718 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb

(2/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 962.02it/s]
(3/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 815.69it/s]

2026-10-24T19:55:34.8195 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.1.self_attn.q_proj']
2026-10-24T19:55:34.8225 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:34.8228 | GPTQ | METRIC - error 136584.06
2026-10-24T19:55:34.8232 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:34.8238 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.1.self_attn.k_proj', 'model.layers.1.self_attn.v_proj']
2026-10-24T19:55:34.8278 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:34.8281 | GPTQ | METRIC - error 32386.93
2026-10-24T19:55:34.8285 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:34.8287 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:34.8289 | GPTQ | METRIC - error 31271.30
2026-10-24T19:55:34.8292 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:34.8298 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.1.self_attn.o_proj']
2026-10-24T19:55:34.8341 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:34.8345 | GPTQ | METRIC - error 7587.00
2026-10-24T19:55:34.8350 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:34.8358 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.1.mlp.gate_proj', 'model.layers.1.mlp.up_proj']
2026-10-24T19:55:34.8403 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:34.8407 | GPTQ | METRIC - error 4478.20
2026-10-24T19:55:34.8412 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb

2026-10-24T19:55:34.8414 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:34.8418 | GPTQ | METRIC - error 4582.70
2026-10-24T19:55:34.8423 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:34.8433 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.1.mlp.down_proj']
2026-10-24T19:55:34.8545 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:34.8549 | GPTQ | METRIC - error 126.71
2026-10-24T19:55:34.8555 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb

(3/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 988.71it/s]
(4/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 859.30it/s]

2026-10-24T19:55:34.9983 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.2.self_attn.q_proj']
2026-10-24T19:55:35.0012 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.0015 | GPTQ | METRIC - error 5572.87
2026-10-24T19:55:35.0018 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.0025 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.2.self_attn.k_proj', 'model.layers.2.self_attn.v_proj']
2026-10-24T19:55:35.0064 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.0067 | GPTQ | METRIC - error 1279.18
2026-10-24T19:55:35.0070 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.0072 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.0074 | GPTQ | METRIC - error 1292.61
2026-10-24T19:55:35.0077 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.0081 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.2.self_attn.o_proj']
2026-10-24T19:55:35.0119 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.0121 | GPTQ | METRIC - error 659.41
2026-10-24T19:55:35.0123 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.0128 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.2.mlp.gate_proj', 'model.layers.2.mlp.up_proj']
2026-10-24T19:55:35.0169 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.0172 | GPTQ | METRIC - error 2719.90
2026-10-24T19:55:35.0174 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.0175 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.0176 | GPTQ | METRIC - error 2749.03
2026-10-24T19:55:35.0179 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.0184 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.2.mlp.down_proj']

2026-10-24T19:55:35.0267 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:35.0269 | GPTQ | METRIC - error 59.94
2026-10-24T19:55:35.0272 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb

(4/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 1028.19it/s]
(5/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 849.26it/s]

2026-10-24T19:55:35.1673 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.3.self_attn.q_proj']
2026-10-24T19:55:35.1702 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.1705 | GPTQ | METRIC - error 4584.46
2026-10-24T19:55:35.1708 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.1715 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.3.self_attn.k_proj', 'model.layers.3.self_attn.v_proj']
2026-10-24T19:55:35.1754 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.1756 | GPTQ | METRIC - error 1044.26
2026-10-24T19:55:35.1759 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.1760 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.1761 | GPTQ | METRIC - error 1320.86
2026-10-24T19:55:35.1764 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.1769 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.3.self_attn.o_proj']
2026-10-24T19:55:35.1806 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.1810 | GPTQ | METRIC - error 196.65
2026-10-24T19:55:35.1814 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.1820 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.3.mlp.gate_proj', 'model.layers.3.mlp.up_proj']
2026-10-24T19:55:35.1861 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.1863 | GPTQ | METRIC - error 2522.62
2026-10-24T19:55:35.1865 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.1866 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.1867 | GPTQ | METRIC - error 2463.00
2026-10-24T19:55:35.1870 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.1874 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.3.mlp.down_proj']
2026-10-24T19:55:35.1957 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:35.1958 | GPTQ | METRIC - error 72.67
2026-10-24T19:55:35.1961 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb

(5/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 1052.76it/s]
(6/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 847.24it/s]

2026-10-24T19:55:35.3353 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.4.self_attn.q_proj']
2026-10-24T19:55:35.3382 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.3385 | GPTQ | METRIC - error 3786.71
2026-10-24T19:55:35.3388 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.3396 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.4.self_attn.k_proj', 'model.layers.4.self_attn.v_proj']
2026-10-24T19:55:35.3435 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.3438 | GPTQ | METRIC - error 995.75
2026-10-24T19:55:35.3440 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.3442 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.3444 | GPTQ | METRIC - error 864.32
2026-10-24T19:55:35.3447 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.3452 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.4.self_attn.o_proj']
2026-10-24T19:55:35.3490 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.3492 | GPTQ | METRIC - error 118.85
2026-10-24T19:55:35.3495 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.3501 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.4.mlp.gate_proj', 'model.layers.4.mlp.up_proj']
2026-10-24T19:55:35.3542 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.3543 | GPTQ | METRIC - error 1856.70
2026-10-24T19:55:35.3546 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.3548 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.3549 | GPTQ | METRIC - error 1915.93
2026-10-24T19:55:35.3552 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.3556 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.4.mlp.down_proj']
2026-10-24T19:55:35.3638 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:35.3640 | GPTQ | METRIC - error 12.98
2026-10-24T19:55:35.3643 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb

(6/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 1010.77it/s]
(7/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 839.55it/s]

2026-10-24T19:55:35.5067 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.5.self_attn.q_proj']
2026-10-24T19:55:35.5096 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.5099 | GPTQ | METRIC - error 1889.59
2026-10-24T19:55:35.5102 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.5109 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.5.self_attn.k_proj', 'model.layers.5.self_attn.v_proj']
2026-10-24T19:55:35.5149 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.5151 | GPTQ | METRIC - error 531.34
2026-10-24T19:55:35.5154 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.5155 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.5157 | GPTQ | METRIC - error 1208.68
2026-10-24T19:55:35.5160 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.5165 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.5.self_attn.o_proj']
2026-10-24T19:55:35.5203 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.5205 | GPTQ | METRIC - error 180.36
2026-10-24T19:55:35.5208 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.5213 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.5.mlp.gate_proj', 'model.layers.5.mlp.up_proj']
2026-10-24T19:55:35.5254 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.5256 | GPTQ | METRIC - error 1279.73
2026-10-24T19:55:35.5259 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.5260 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.5262 | GPTQ | METRIC - error 1299.75
2026-10-24T19:55:35.5264 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.5268 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.5.mlp.down_proj']

2026-10-24T19:55:35.5353 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:35.5354 | GPTQ | METRIC - error 34.96
2026-10-24T19:55:35.5357 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb

(7/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 1023.14it/s]
(8/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 865.53it/s]

2026-10-24T19:55:35.6751 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.6.self_attn.q_proj']
2026-10-24T19:55:35.6780 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.6783 | GPTQ | METRIC - error 3333.54
2026-10-24T19:55:35.6786 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.6793 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.6.self_attn.k_proj', 'model.layers.6.self_attn.v_proj']
2026-10-24T19:55:35.6833 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.6836 | GPTQ | METRIC - error 791.31
2026-10-24T19:55:35.6840 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.6842 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.6845 | GPTQ | METRIC - error 843.29
2026-10-24T19:55:35.6847 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.6853 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.6.self_attn.o_proj']
2026-10-24T19:55:35.6890 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.6892 | GPTQ | METRIC - error 132.57
2026-10-24T19:55:35.6895 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.6900 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.6.mlp.gate_proj', 'model.layers.6.mlp.up_proj']
2026-10-24T19:55:35.6939 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.6940 | GPTQ | METRIC - error 923.43
2026-10-24T19:55:35.6944 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.6946 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.6947 | GPTQ | METRIC - error 979.23
2026-10-24T19:55:35.6949 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.6954 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.6.mlp.down_proj']
2026-10-24T19:55:35.7037 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:35.7039 | GPTQ | METRIC - error 8.17
2026-10-24T19:55:35.7043 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb

(8/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 1000.71it/s]
(9/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 842.31it/s]

2026-10-24T19:55:35.8470 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.7.self_attn.q_proj']
2026-10-24T19:55:35.8499 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.8502 | GPTQ | METRIC - error 7531.67
2026-10-24T19:55:35.8507 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.8515 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.7.self_attn.k_proj', 'model.layers.7.self_attn.v_proj']
2026-10-24T19:55:35.8555 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.8558 | GPTQ | METRIC - error 1936.23
2026-10-24T19:55:35.8562 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.8564 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.8565 | GPTQ | METRIC - error 1778.61
2026-10-24T19:55:35.8568 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.8572 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.7.self_attn.o_proj']
2026-10-24T19:55:35.8609 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.8611 | GPTQ | METRIC - error 639.31
2026-10-24T19:55:35.8613 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.8618 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.7.mlp.gate_proj', 'model.layers.7.mlp.up_proj']
2026-10-24T19:55:35.8659 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.8662 | GPTQ | METRIC - error 871.53
2026-10-24T19:55:35.8665 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.8666 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:35.8667 | GPTQ | METRIC - error 978.82
2026-10-24T19:55:35.8670 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:35.8674 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.7.mlp.down_proj']

2026-10-24T19:55:35.8757 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:35.8759 | GPTQ | METRIC - error 17.75
2026-10-24T19:55:35.8761 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb

(9/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 1012.60it/s]
(10/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 839.52it/s]

2026-10-24T19:55:36.0181 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.8.self_attn.q_proj']
2026-10-24T19:55:36.0210 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.0213 | GPTQ | METRIC - error 7829.44
2026-10-24T19:55:36.0216 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.0222 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.8.self_attn.k_proj', 'model.layers.8.self_attn.v_proj']
2026-10-24T19:55:36.0260 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.0262 | GPTQ | METRIC - error 2005.79
2026-10-24T19:55:36.0265 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.0267 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.0268 | GPTQ | METRIC - error 2148.80
2026-10-24T19:55:36.0271 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.0276 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.8.self_attn.o_proj']
2026-10-24T19:55:36.0314 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.0317 | GPTQ | METRIC - error 470.42
2026-10-24T19:55:36.0320 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.0326 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.8.mlp.gate_proj', 'model.layers.8.mlp.up_proj']
2026-10-24T19:55:36.0367 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.0369 | GPTQ | METRIC - error 911.36
2026-10-24T19:55:36.0371 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.0373 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.0374 | GPTQ | METRIC - error 1004.26
2026-10-24T19:55:36.0376 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.0381 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.8.mlp.down_proj']

2026-10-24T19:55:36.0465 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:36.0467 | GPTQ | METRIC - error 8.32
2026-10-24T19:55:36.0469 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb

(10/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 994.09it/s]
(11/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 833.87it/s]

2026-10-24T19:55:36.1909 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.9.self_attn.q_proj']
2026-10-24T19:55:36.1939 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.1942 | GPTQ | METRIC - error 6080.16
2026-10-24T19:55:36.1946 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.1953 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.9.self_attn.k_proj', 'model.layers.9.self_attn.v_proj']
2026-10-24T19:55:36.1993 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.1995 | GPTQ | METRIC - error 1516.41
2026-10-24T19:55:36.1998 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.2000 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.2001 | GPTQ | METRIC - error 1543.28
2026-10-24T19:55:36.2004 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.2010 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.9.self_attn.o_proj']
2026-10-24T19:55:36.2048 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.2051 | GPTQ | METRIC - error 278.52
2026-10-24T19:55:36.2054 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.2060 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.9.mlp.gate_proj', 'model.layers.9.mlp.up_proj']
2026-10-24T19:55:36.2099 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.2101 | GPTQ | METRIC - error 409.55
2026-10-24T19:55:36.2104 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.2105 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.2107 | GPTQ | METRIC - error 466.25
2026-10-24T19:55:36.2110 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.2115 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.9.mlp.down_proj']

2026-10-24T19:55:36.2201 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:36.2203 | GPTQ | METRIC - error 6.06
2026-10-24T19:55:36.2206 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb

(11/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 1011.14it/s]
(12/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 854.66it/s]

2026-10-24T19:55:36.3616 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.10.self_attn.q_proj']
2026-10-24T19:55:36.3645 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.3648 | GPTQ | METRIC - error 8118.32
2026-10-24T19:55:36.3652 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.3659 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.10.self_attn.k_proj', 'model.layers.10.self_attn.v_proj']
2026-10-24T19:55:36.3697 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.3699 | GPTQ | METRIC - error 2303.41
2026-10-24T19:55:36.3702 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.3704 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.3705 | GPTQ | METRIC - error 1878.38
2026-10-24T19:55:36.3708 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.3712 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.10.self_attn.o_proj']
2026-10-24T19:55:36.3752 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.3755 | GPTQ | METRIC - error 796.64
2026-10-24T19:55:36.3758 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.3764 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.10.mlp.gate_proj', 'model.layers.10.mlp.up_proj']
2026-10-24T19:55:36.3803 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.3805 | GPTQ | METRIC - error 769.49
2026-10-24T19:55:36.3807 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.3810 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.3813 | GPTQ | METRIC - error 813.45
2026-10-24T19:55:36.3816 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.3825 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.10.mlp.down_proj']

2026-10-24T19:55:36.3911 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:36.3913 | GPTQ | METRIC - error 8.14
2026-10-24T19:55:36.3916 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb

(12/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 1033.02it/s]
(13/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 846.97it/s]

2026-10-24T19:55:36.5321 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.11.self_attn.q_proj']
2026-10-24T19:55:36.5350 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.5353 | GPTQ | METRIC - error 615.73
2026-10-24T19:55:36.5357 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.5365 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.11.self_attn.k_proj', 'model.layers.11.self_attn.v_proj']
2026-10-24T19:55:36.5403 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.5405 | GPTQ | METRIC - error 229.06
2026-10-24T19:55:36.5408 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.5409 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.5411 | GPTQ | METRIC - error 246.15
2026-10-24T19:55:36.5414 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.5423 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.11.self_attn.o_proj']
2026-10-24T19:55:36.5482 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:36.5486 | GPTQ | METRIC - error 92.49
2026-10-24T19:55:36.5490 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.5501 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.11.mlp.gate_proj', 'model.layers.11.mlp.up_proj']
2026-10-24T19:55:36.5548 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.5551 | GPTQ | METRIC - error 1261.17
2026-10-24T19:55:36.5554 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.5556 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:36.5559 | GPTQ | METRIC - error 1386.53
2026-10-24T19:55:36.5562 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.5568 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.11.mlp.down_proj']

2026-10-24T19:55:36.5658 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:36.5661 | GPTQ | METRIC - error 30.54
2026-10-24T19:55:36.5664 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb

(13/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 1017.35it/s]
(14/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 837.35it/s]

2026-10-24T19:55:36.7089 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.12.self_attn.q_proj']
2026-10-24T19:55:36.7118 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.7120 | GPTQ | METRIC - error 6221.46
2026-10-24T19:55:36.7125 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.7132 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.12.self_attn.k_proj', 'model.layers.12.self_attn.v_proj']
2026-10-24T19:55:36.7171 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.7174 | GPTQ | METRIC - error 2689.33
2026-10-24T19:55:36.7177 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.7179 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.7181 | GPTQ | METRIC - error 1621.26
2026-10-24T19:55:36.7184 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.7190 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.12.self_attn.o_proj']
2026-10-24T19:55:36.7229 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.7231 | GPTQ | METRIC - error 477.87
2026-10-24T19:55:36.7235 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.7241 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.12.mlp.gate_proj', 'model.layers.12.mlp.up_proj']
2026-10-24T19:55:36.7281 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.7285 | GPTQ | METRIC - error 655.17
2026-10-24T19:55:36.7289 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.7291 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.7293 | GPTQ | METRIC - error 676.02
2026-10-24T19:55:36.7296 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.7301 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.12.mlp.down_proj']

2026-10-24T19:55:36.7387 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:36.7393 | GPTQ | METRIC - error 13.69
2026-10-24T19:55:36.7399 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb

(14/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 1066.07it/s]
(15/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 840.79it/s]

2026-10-24T19:55:36.8806 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.13.self_attn.q_proj']
2026-10-24T19:55:36.8836 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.8839 | GPTQ | METRIC - error 12021.91
2026-10-24T19:55:36.8842 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.8848 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.13.self_attn.k_proj', 'model.layers.13.self_attn.v_proj']
2026-10-24T19:55:36.8885 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.8887 | GPTQ | METRIC - error 3301.38
2026-10-24T19:55:36.8890 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.8892 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.8893 | GPTQ | METRIC - error 3757.92
2026-10-24T19:55:36.8897 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.8902 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.13.self_attn.o_proj']
2026-10-24T19:55:36.8939 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.8942 | GPTQ | METRIC - error 574.76
2026-10-24T19:55:36.8945 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.8950 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.13.mlp.gate_proj', 'model.layers.13.mlp.up_proj']
2026-10-24T19:55:36.8989 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.8991 | GPTQ | METRIC - error 427.17
2026-10-24T19:55:36.8994 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.8996 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:36.8997 | GPTQ | METRIC - error 484.11
2026-10-24T19:55:36.9000 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:36.9006 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.13.mlp.down_proj']

2026-10-24T19:55:36.9094 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:36.9096 | GPTQ | METRIC - error 5.47
2026-10-24T19:55:36.9098 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb

(15/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 998.96it/s]
(16/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 844.46it/s]

2026-10-24T19:55:37.0527 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.14.self_attn.q_proj']
2026-10-24T19:55:37.0557 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:37.0560 | GPTQ | METRIC - error 9534.83
2026-10-24T19:55:37.0565 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:37.0573 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.14.self_attn.k_proj', 'model.layers.14.self_attn.v_proj']
2026-10-24T19:55:37.0613 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:37.0616 | GPTQ | METRIC - error 3090.42
2026-10-24T19:55:37.0620 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:37.0623 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:37.0624 | GPTQ | METRIC - error 2349.39
2026-10-24T19:55:37.0628 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:37.0634 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.14.self_attn.o_proj']
2026-10-24T19:55:37.0675 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:37.0677 | GPTQ | METRIC - error 585.08
2026-10-24T19:55:37.0680 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:37.0687 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.14.mlp.gate_proj', 'model.layers.14.mlp.up_proj']
2026-10-24T19:55:37.0726 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:37.0728 | GPTQ | METRIC - error 367.24
2026-10-24T19:55:37.0730 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:37.0732 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:37.0733 | GPTQ | METRIC - error 416.06
2026-10-24T19:55:37.0737 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:37.0745 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.14.mlp.down_proj']

2026-10-24T19:55:37.0830 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:37.0833 | GPTQ | METRIC - error 3.27
2026-10-24T19:55:37.0836 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb

(16/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 984.12it/s]
(17/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 840.48it/s]

2026-10-24T19:55:37.2281 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.15.self_attn.q_proj']
2026-10-24T19:55:37.2310 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:37.2313 | GPTQ | METRIC - error 11429.89
2026-10-24T19:55:37.2316 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:37.2324 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.15.self_attn.k_proj', 'model.layers.15.self_attn.v_proj']
2026-10-24T19:55:37.2365 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:37.2367 | GPTQ | METRIC - error 3340.57
2026-10-24T19:55:37.2370 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:37.2372 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:37.2375 | GPTQ | METRIC - error 2731.65
2026-10-24T19:55:37.2379 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:37.2385 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.15.self_attn.o_proj']
2026-10-24T19:55:37.2424 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:37.2426 | GPTQ | METRIC - error 1285.41
2026-10-24T19:55:37.2431 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:37.2437 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.15.mlp.gate_proj', 'model.layers.15.mlp.up_proj']
2026-10-24T19:55:37.2476 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:37.2479 | GPTQ | METRIC - error 249.92
2026-10-24T19:55:37.2482 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:37.2484 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:37.2486 | GPTQ | METRIC - error 274.94
2026-10-24T19:55:37.2489 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:37.2495 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.15.mlp.down_proj']

2026-10-24T19:55:37.2580 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:37.2582 | GPTQ | METRIC - error 2.46
2026-10-24T19:55:37.2585 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb

(17/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 988.87it/s]
(18/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 833.67it/s]

2026-10-24T19:55:37.4031 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.16.self_attn.q_proj']
2026-10-24T19:55:37.4060 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:37.4063 | GPTQ | METRIC - error 16395.54
2026-10-24T19:55:37.4066 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:37.4075 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.16.self_attn.k_proj', 'model.layers.16.self_attn.v_proj']
2026-10-24T19:55:37.4114 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:37.4116 | GPTQ | METRIC - error 4473.06
2026-10-24T19:55:37.4119 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:37.4120 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:37.4121 | GPTQ | METRIC - error 4385.84
2026-10-24T19:55:37.4124 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:37.4128 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.16.self_attn.o_proj']
2026-10-24T19:55:37.4167 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:37.4169 | GPTQ | METRIC - error 1101.88
2026-10-24T19:55:37.4172 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:37.4178 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.16.mlp.gate_proj', 'model.layers.16.mlp.up_proj']
2026-10-24T19:55:37.4216 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:37.4219 | GPTQ | METRIC - error 251.82
2026-10-24T19:55:37.4222 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:37.4224 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:37.4225 | GPTQ | METRIC - error 277.20
2026-10-24T19:55:37.4229 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:37.4234 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.16.mlp.down_proj']

2026-10-24T19:55:37.4329 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:37.4332 | GPTQ | METRIC - error 3.47
2026-10-24T19:55:37.4337 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb

(18/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 1018.97it/s]
(19/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 805.62it/s]

2026-10-24T19:55:37.5792 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.17.self_attn.q_proj']
2026-10-24T19:55:37.5821 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:37.5823 | GPTQ | METRIC - error 4699.55
2026-10-24T19:55:37.5826 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:37.5833 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.17.self_attn.k_proj', 'model.layers.17.self_attn.v_proj']
2026-10-24T19:55:37.5872 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:37.5874 | GPTQ | METRIC - error 1428.04
2026-10-24T19:55:37.5877 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:37.5879 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:37.5880 | GPTQ | METRIC - error 1529.53
2026-10-24T19:55:37.5882 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:37.5888 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.17.self_attn.o_proj']
2026-10-24T19:55:37.5926 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:37.5929 | GPTQ | METRIC - error 502.85
2026-10-24T19:55:37.5932 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:37.5938 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.17.mlp.gate_proj', 'model.layers.17.mlp.up_proj']
2026-10-24T19:55:37.5977 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:37.5979 | GPTQ | METRIC - error 459.05
2026-10-24T19:55:37.5985 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:37.5987 | GPTQ | METRIC - time 0.00s
2026-10-24T19:55:37.5988 | GPTQ | METRIC - error 469.74
2026-10-24T19:55:37.5991 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb
2026-10-24T19:55:37.5997 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.17.mlp.down_proj']

2026-10-24T19:55:37.6081 | GPTQ | METRIC - time 0.01s
2026-10-24T19:55:37.6083 | GPTQ | METRIC - error 6.60
2026-10-24T19:55:37.6087 | GPTQ | METRIC - Accelerator 0 | usage: 32.73% | total memory: 16.7 Gb

(19/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 1007.49it/s]

2026-10-24T19:55:37.6768 | norm_calibration_context | INFO - Restoring 109 norm modules to offset convention
2026-10-24T19:55:37.6793 | finalize | INFO - Compression lifecycle finalized for 1 modifiers

2026-10-24T19:59:13.6396 | reset | INFO - Compression lifecycle reset

Testing: {'actorder': 'static', 'dampening_frac': 0.01}

Loading weights: 100%|██████████| 236/236 [00:00<00:00, 4782.30it/s]

2026-10-24T19:59:14.8976 | reset | INFO - Compression lifecycle reset
2026-10-24T19:59:14.9011 | norm_calibration_context | INFO - Found 109 offset-norm modules to convert
2026-10-24T19:59:14.9042 | from_modifiers | INFO - Creating recipe from modifiers

Applying quantization config: 100%|██████████| 126/126 [00:00<00:00, 15825.67it/s]

2026-10-24T19:59:14.9174 | initialize | INFO - Compression lifecycle initialized for 1 modifiers
2026-10-24T19:59:14.9179 | IndependentPipeline | INFO - Inferred `SequentialPipeline` for `GPTQModifier`

Preparing cache: 100%|██████████| 64/64 [00:00<00:00, 5667.50it/s]
(1/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 1402.59it/s]
(1/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 656.38it/s]
(2/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 793.71it/s]

2026-10-24T19:59:15.1993 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.0.self_attn.q_proj']
2026-10-24T19:59:15.2086 | GPTQ | METRIC - time 0.01s
2026-10-24T19:59:15.2089 | GPTQ | METRIC - error 189499.84
2026-10-24T19:59:15.2093 | GPTQ | METRIC - Accelerator 0 | usage: 39.00% | total memory: 16.7 Gb
2026-10-24T19:59:15.2100 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.0.self_attn.k_proj', 'model.layers.0.self_attn.v_proj']
2026-10-24T19:59:15.2142 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.2145 | GPTQ | METRIC - error 41378.10
2026-10-24T19:59:15.2149 | GPTQ | METRIC - Accelerator 0 | usage: 39.00% | total memory: 16.7 Gb
2026-10-24T19:59:15.2151 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.2153 | GPTQ | METRIC - error 48200.02
2026-10-24T19:59:15.2156 | GPTQ | METRIC - Accelerator 0 | usage: 39.00% | total memory: 16.7 Gb
2026-10-24T19:59:15.2161 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.0.self_attn.o_proj']

2026-10-24T19:59:15.2202 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.2205 | GPTQ | METRIC - error 25452.99
2026-10-24T19:59:15.2208 | GPTQ | METRIC - Accelerator 0 | usage: 39.00% | total memory: 16.7 Gb
2026-10-24T19:59:15.2214 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.0.mlp.gate_proj', 'model.layers.0.mlp.up_proj']
2026-10-24T19:59:15.2259 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.2261 | GPTQ | METRIC - error 9883.55
2026-10-24T19:59:15.2265 | GPTQ | METRIC - Accelerator 0 | usage: 39.01% | total memory: 16.7 Gb
2026-10-24T19:59:15.2266 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.2267 | GPTQ | METRIC - error 10636.98
2026-10-24T19:59:15.2270 | GPTQ | METRIC - Accelerator 0 | usage: 39.01% | total memory: 16.7 Gb
2026-10-24T19:59:15.2275 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.0.mlp.down_proj']
2026-10-24T19:59:15.2362 | GPTQ | METRIC - time 0.01s
2026-10-24T19:59:15.2366 | GPTQ | METRIC - error 1627.72
2026-10-24T19:59:15.2369 | GPTQ | METRIC - Accelerator 0 | usage: 39.16% | total memory: 16.7 Gb

(2/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 908.19it/s]
(3/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 831.11it/s]

2026-10-24T19:59:15.3874 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.1.self_attn.q_proj']
2026-10-24T19:59:15.3904 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.3906 | GPTQ | METRIC - error 104245.48
2026-10-24T19:59:15.3909 | GPTQ | METRIC - Accelerator 0 | usage: 39.16% | total memory: 16.7 Gb
2026-10-24T19:59:15.3915 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.1.self_attn.k_proj', 'model.layers.1.self_attn.v_proj']
2026-10-24T19:59:15.3953 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.3955 | GPTQ | METRIC - error 24855.21
2026-10-24T19:59:15.3958 | GPTQ | METRIC - Accelerator 0 | usage: 39.16% | total memory: 16.7 Gb
2026-10-24T19:59:15.3959 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.3960 | GPTQ | METRIC - error 24077.04
2026-10-24T19:59:15.3963 | GPTQ | METRIC - Accelerator 0 | usage: 39.16% | total memory: 16.7 Gb
2026-10-24T19:59:15.3967 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.1.self_attn.o_proj']

2026-10-24T19:59:15.4006 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.4008 | GPTQ | METRIC - error 4324.50
2026-10-24T19:59:15.4011 | GPTQ | METRIC - Accelerator 0 | usage: 39.16% | total memory: 16.7 Gb
2026-10-24T19:59:15.4017 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.1.mlp.gate_proj', 'model.layers.1.mlp.up_proj']
2026-10-24T19:59:15.4059 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.4061 | GPTQ | METRIC - error 3223.59
2026-10-24T19:59:15.4064 | GPTQ | METRIC - Accelerator 0 | usage: 39.16% | total memory: 16.7 Gb
2026-10-24T19:59:15.4065 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.4066 | GPTQ | METRIC - error 3275.23
2026-10-24T19:59:15.4068 | GPTQ | METRIC - Accelerator 0 | usage: 39.16% | total memory: 16.7 Gb
2026-10-24T19:59:15.4073 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.1.mlp.down_proj']
2026-10-24T19:59:15.4158 | GPTQ | METRIC - time 0.01s
2026-10-24T19:59:15.4160 | GPTQ | METRIC - error 87.43
2026-10-24T19:59:15.4163 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb

(3/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 949.54it/s]
(4/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 820.16it/s]

2026-10-24T19:59:15.5649 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.2.self_attn.q_proj']
2026-10-24T19:59:15.5678 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.5680 | GPTQ | METRIC - error 2405.65
2026-10-24T19:59:15.5684 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:15.5690 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.2.self_attn.k_proj', 'model.layers.2.self_attn.v_proj']
2026-10-24T19:59:15.5731 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.5734 | GPTQ | METRIC - error 614.41
2026-10-24T19:59:15.5737 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:15.5739 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.5741 | GPTQ | METRIC - error 623.06
2026-10-24T19:59:15.5745 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:15.5753 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.2.self_attn.o_proj']
2026-10-24T19:59:15.5796 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.5806 | GPTQ | METRIC - error 412.91
2026-10-24T19:59:15.5810 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:15.5820 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.2.mlp.gate_proj', 'model.layers.2.mlp.up_proj']

2026-10-24T19:59:15.5864 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.5869 | GPTQ | METRIC - error 1950.25
2026-10-24T19:59:15.5873 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:15.5876 | GPTQ | METRIC - time 0.01s
2026-10-24T19:59:15.5877 | GPTQ | METRIC - error 1966.02
2026-10-24T19:59:15.5879 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:15.5884 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.2.mlp.down_proj']
2026-10-24T19:59:15.5968 | GPTQ | METRIC - time 0.01s
2026-10-24T19:59:15.5970 | GPTQ | METRIC - error 31.96
2026-10-24T19:59:15.5973 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb

(4/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 951.58it/s]
(5/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 843.48it/s]

2026-10-24T19:59:15.7434 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.3.self_attn.q_proj']
2026-10-24T19:59:15.7465 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.7469 | GPTQ | METRIC - error 2856.59
2026-10-24T19:59:15.7473 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:15.7480 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.3.self_attn.k_proj', 'model.layers.3.self_attn.v_proj']
2026-10-24T19:59:15.7519 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.7521 | GPTQ | METRIC - error 661.08
2026-10-24T19:59:15.7526 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:15.7528 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.7529 | GPTQ | METRIC - error 833.60
2026-10-24T19:59:15.7532 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:15.7536 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.3.self_attn.o_proj']
2026-10-24T19:59:15.7577 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.7579 | GPTQ | METRIC - error 102.04
2026-10-24T19:59:15.7583 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:15.7589 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.3.mlp.gate_proj', 'model.layers.3.mlp.up_proj']
2026-10-24T19:59:15.7632 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.7635 | GPTQ | METRIC - error 1646.91

2026-10-24T19:59:15.7638 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:15.7640 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.7641 | GPTQ | METRIC - error 1578.99
2026-10-24T19:59:15.7643 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:15.7650 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.3.mlp.down_proj']
2026-10-24T19:59:15.7735 | GPTQ | METRIC - time 0.01s
2026-10-24T19:59:15.7737 | GPTQ | METRIC - error 36.66
2026-10-24T19:59:15.7740 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb

(5/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 959.43it/s]
(6/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 811.62it/s]

2026-10-24T19:59:15.9228 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.4.self_attn.q_proj']
2026-10-24T19:59:15.9260 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.9263 | GPTQ | METRIC - error 2054.84
2026-10-24T19:59:15.9267 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:15.9274 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.4.self_attn.k_proj', 'model.layers.4.self_attn.v_proj']
2026-10-24T19:59:15.9313 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.9315 | GPTQ | METRIC - error 543.39
2026-10-24T19:59:15.9318 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:15.9320 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.9321 | GPTQ | METRIC - error 469.58
2026-10-24T19:59:15.9323 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:15.9328 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.4.self_attn.o_proj']
2026-10-24T19:59:15.9366 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.9369 | GPTQ | METRIC - error 56.21
2026-10-24T19:59:15.9372 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:15.9378 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.4.mlp.gate_proj', 'model.layers.4.mlp.up_proj']
2026-10-24T19:59:15.9420 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.9422 | GPTQ | METRIC - error 1036.93

2026-10-24T19:59:15.9425 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:15.9427 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:15.9429 | GPTQ | METRIC - error 1068.98
2026-10-24T19:59:15.9432 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:15.9438 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.4.mlp.down_proj']
2026-10-24T19:59:15.9523 | GPTQ | METRIC - time 0.01s
2026-10-24T19:59:15.9525 | GPTQ | METRIC - error 7.19
2026-10-24T19:59:15.9528 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb

(6/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 980.14it/s]
(7/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 833.37it/s]

2026-10-24T19:59:16.0980 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.5.self_attn.q_proj']
2026-10-24T19:59:16.1010 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.1013 | GPTQ | METRIC - error 1072.65
2026-10-24T19:59:16.1016 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.1024 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.5.self_attn.k_proj', 'model.layers.5.self_attn.v_proj']
2026-10-24T19:59:16.1065 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.1067 | GPTQ | METRIC - error 302.06
2026-10-24T19:59:16.1071 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.1073 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.1074 | GPTQ | METRIC - error 695.09
2026-10-24T19:59:16.1077 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.1082 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.5.self_attn.o_proj']
2026-10-24T19:59:16.1122 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.1125 | GPTQ | METRIC - error 95.87
2026-10-24T19:59:16.1129 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.1135 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.5.mlp.gate_proj', 'model.layers.5.mlp.up_proj']
2026-10-24T19:59:16.1178 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.1180 | GPTQ | METRIC - error 764.01
2026-10-24T19:59:16.1185 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.1186 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.1188 | GPTQ | METRIC - error 775.75
2026-10-24T19:59:16.1192 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.1198 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.5.mlp.down_proj']

2026-10-24T19:59:16.1284 | GPTQ | METRIC - time 0.01s
2026-10-24T19:59:16.1287 | GPTQ | METRIC - error 16.39
2026-10-24T19:59:16.1290 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb

(7/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 960.89it/s]
(8/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 818.69it/s]

2026-10-24T19:59:16.2772 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.6.self_attn.q_proj']
2026-10-24T19:59:16.2803 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.2807 | GPTQ | METRIC - error 1603.47
2026-10-24T19:59:16.2813 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.2823 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.6.self_attn.k_proj', 'model.layers.6.self_attn.v_proj']
2026-10-24T19:59:16.2864 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.2868 | GPTQ | METRIC - error 395.45
2026-10-24T19:59:16.2871 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.2872 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.2873 | GPTQ | METRIC - error 426.97
2026-10-24T19:59:16.2877 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.2882 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.6.self_attn.o_proj']
2026-10-24T19:59:16.2920 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.2922 | GPTQ | METRIC - error 60.51
2026-10-24T19:59:16.2925 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.2930 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.6.mlp.gate_proj', 'model.layers.6.mlp.up_proj']
2026-10-24T19:59:16.2970 | GPTQ | METRIC - time 0.00s

2026-10-24T19:59:16.2973 | GPTQ | METRIC - error 538.19
2026-10-24T19:59:16.2976 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.2978 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.2979 | GPTQ | METRIC - error 571.70
2026-10-24T19:59:16.2982 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.2988 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.6.mlp.down_proj']
2026-10-24T19:59:16.3075 | GPTQ | METRIC - time 0.01s
2026-10-24T19:59:16.3077 | GPTQ | METRIC - error 3.89
2026-10-24T19:59:16.3080 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb

(8/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 966.14it/s]
(9/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 815.76it/s]

2026-10-24T19:59:16.4552 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.7.self_attn.q_proj']
2026-10-24T19:59:16.4582 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.4585 | GPTQ | METRIC - error 3736.90
2026-10-24T19:59:16.4589 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.4595 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.7.self_attn.k_proj', 'model.layers.7.self_attn.v_proj']
2026-10-24T19:59:16.4635 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.4637 | GPTQ | METRIC - error 976.73
2026-10-24T19:59:16.4642 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.4644 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.4645 | GPTQ | METRIC - error 881.27
2026-10-24T19:59:16.4648 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.4653 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.7.self_attn.o_proj']
2026-10-24T19:59:16.4691 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.4694 | GPTQ | METRIC - error 266.46
2026-10-24T19:59:16.4697 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.4702 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.7.mlp.gate_proj', 'model.layers.7.mlp.up_proj']
2026-10-24T19:59:16.4745 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.4747 | GPTQ | METRIC - error 495.97
2026-10-24T19:59:16.4750 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.4751 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.4752 | GPTQ | METRIC - error 554.73
2026-10-24T19:59:16.4755 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.4760 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.7.mlp.down_proj']

2026-10-24T19:59:16.4846 | GPTQ | METRIC - time 0.01s
2026-10-24T19:59:16.4848 | GPTQ | METRIC - error 7.19
2026-10-24T19:59:16.4851 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb

(9/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 951.20it/s]
(10/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 796.52it/s]

2026-10-24T19:59:16.6354 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.8.self_attn.q_proj']
2026-10-24T19:59:16.6386 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.6389 | GPTQ | METRIC - error 3098.64
2026-10-24T19:59:16.6394 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.6401 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.8.self_attn.k_proj', 'model.layers.8.self_attn.v_proj']
2026-10-24T19:59:16.6440 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.6443 | GPTQ | METRIC - error 797.75
2026-10-24T19:59:16.6446 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.6447 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.6448 | GPTQ | METRIC - error 862.70
2026-10-24T19:59:16.6451 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.6456 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.8.self_attn.o_proj']
2026-10-24T19:59:16.6495 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.6498 | GPTQ | METRIC - error 220.69
2026-10-24T19:59:16.6501 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.6506 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.8.mlp.gate_proj', 'model.layers.8.mlp.up_proj']

2026-10-24T19:59:16.6549 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.6553 | GPTQ | METRIC - error 468.91
2026-10-24T19:59:16.6556 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.6557 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.6559 | GPTQ | METRIC - error 518.39
2026-10-24T19:59:16.6561 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.6566 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.8.mlp.down_proj']
2026-10-24T19:59:16.6651 | GPTQ | METRIC - time 0.01s
2026-10-24T19:59:16.6654 | GPTQ | METRIC - error 3.57
2026-10-24T19:59:16.6657 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb

(10/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 964.76it/s]
(11/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 805.30it/s]

2026-10-24T19:59:16.8145 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.9.self_attn.q_proj']
2026-10-24T19:59:16.8174 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.8177 | GPTQ | METRIC - error 2489.31
2026-10-24T19:59:16.8181 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.8187 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.9.self_attn.k_proj', 'model.layers.9.self_attn.v_proj']
2026-10-24T19:59:16.8228 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.8231 | GPTQ | METRIC - error 626.39
2026-10-24T19:59:16.8234 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.8236 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.8237 | GPTQ | METRIC - error 641.22
2026-10-24T19:59:16.8241 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.8246 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.9.self_attn.o_proj']
2026-10-24T19:59:16.8285 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.8288 | GPTQ | METRIC - error 106.11
2026-10-24T19:59:16.8290 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.8296 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.9.mlp.gate_proj', 'model.layers.9.mlp.up_proj']
2026-10-24T19:59:16.8336 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.8338 | GPTQ | METRIC - error 210.91
2026-10-24T19:59:16.8341 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.8342 | GPTQ | METRIC - time 0.00s

2026-10-24T19:59:16.8343 | GPTQ | METRIC - error 239.05
2026-10-24T19:59:16.8346 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.8351 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.9.mlp.down_proj']
2026-10-24T19:59:16.8436 | GPTQ | METRIC - time 0.01s
2026-10-24T19:59:16.8439 | GPTQ | METRIC - error 2.33
2026-10-24T19:59:16.8441 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb

(11/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 948.20it/s]
(12/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 798.63it/s]

2026-10-24T19:59:16.9948 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.10.self_attn.q_proj']
2026-10-24T19:59:16.9978 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:16.9981 | GPTQ | METRIC - error 3396.86
2026-10-24T19:59:16.9985 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:16.9990 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.10.self_attn.k_proj', 'model.layers.10.self_attn.v_proj']
2026-10-24T19:59:17.0030 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.0032 | GPTQ | METRIC - error 953.76
2026-10-24T19:59:17.0035 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.0036 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.0037 | GPTQ | METRIC - error 777.95
2026-10-24T19:59:17.0040 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.0045 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.10.self_attn.o_proj']
2026-10-24T19:59:17.0085 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.0089 | GPTQ | METRIC - error 271.97
2026-10-24T19:59:17.0094 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.0106 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.10.mlp.gate_proj', 'model.layers.10.mlp.up_proj']

2026-10-24T19:59:17.0176 | GPTQ | METRIC - time 0.01s
2026-10-24T19:59:17.0182 | GPTQ | METRIC - error 355.24
2026-10-24T19:59:17.0188 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.0192 | GPTQ | METRIC - time 0.01s
2026-10-24T19:59:17.0195 | GPTQ | METRIC - error 378.31
2026-10-24T19:59:17.0200 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.0207 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.10.mlp.down_proj']
2026-10-24T19:59:17.0296 | GPTQ | METRIC - time 0.01s
2026-10-24T19:59:17.0299 | GPTQ | METRIC - error 2.68
2026-10-24T19:59:17.0301 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb

(12/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 1002.74it/s]
(13/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 825.33it/s]

2026-10-24T19:59:17.1743 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.11.self_attn.q_proj']
2026-10-24T19:59:17.1773 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.1777 | GPTQ | METRIC - error 297.83
2026-10-24T19:59:17.1781 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.1789 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.11.self_attn.k_proj', 'model.layers.11.self_attn.v_proj']
2026-10-24T19:59:17.1830 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.1834 | GPTQ | METRIC - error 111.55
2026-10-24T19:59:17.1838 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.1841 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.1843 | GPTQ | METRIC - error 118.26
2026-10-24T19:59:17.1846 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.1851 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.11.self_attn.o_proj']
2026-10-24T19:59:17.1891 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.1894 | GPTQ | METRIC - error 39.39
2026-10-24T19:59:17.1896 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.1904 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.11.mlp.gate_proj', 'model.layers.11.mlp.up_proj']

2026-10-24T19:59:17.1948 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.1951 | GPTQ | METRIC - error 598.64
2026-10-24T19:59:17.1955 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.1958 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.1960 | GPTQ | METRIC - error 658.17
2026-10-24T19:59:17.1962 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.1967 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.11.mlp.down_proj']
2026-10-24T19:59:17.2052 | GPTQ | METRIC - time 0.01s
2026-10-24T19:59:17.2055 | GPTQ | METRIC - error 10.25
2026-10-24T19:59:17.2059 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb

(13/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 970.64it/s]
(14/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 818.16it/s]

2026-10-24T19:59:17.3529 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.12.self_attn.q_proj']
2026-10-24T19:59:17.3559 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.3563 | GPTQ | METRIC - error 3380.78
2026-10-24T19:59:17.3566 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.3574 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.12.self_attn.k_proj', 'model.layers.12.self_attn.v_proj']
2026-10-24T19:59:17.3614 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.3616 | GPTQ | METRIC - error 1455.59
2026-10-24T19:59:17.3620 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.3621 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.3622 | GPTQ | METRIC - error 876.90
2026-10-24T19:59:17.3625 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.3630 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.12.self_attn.o_proj']
2026-10-24T19:59:17.3670 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.3673 | GPTQ | METRIC - error 266.14
2026-10-24T19:59:17.3676 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.3682 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.12.mlp.gate_proj', 'model.layers.12.mlp.up_proj']
2026-10-24T19:59:17.3723 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.3725 | GPTQ | METRIC - error 351.78
2026-10-24T19:59:17.3728 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.3730 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.3731 | GPTQ | METRIC - error 363.11
2026-10-24T19:59:17.3733 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb

2026-10-24T19:59:17.3739 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.12.mlp.down_proj']
2026-10-24T19:59:17.3824 | GPTQ | METRIC - time 0.01s
2026-10-24T19:59:17.3826 | GPTQ | METRIC - error 5.42
2026-10-24T19:59:17.3829 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb

(14/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 971.22it/s]
(15/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 839.69it/s]

2026-10-24T19:59:17.5281 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.13.self_attn.q_proj']
2026-10-24T19:59:17.5311 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.5315 | GPTQ | METRIC - error 4922.91
2026-10-24T19:59:17.5318 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.5327 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.13.self_attn.k_proj', 'model.layers.13.self_attn.v_proj']
2026-10-24T19:59:17.5366 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.5369 | GPTQ | METRIC - error 1340.71
2026-10-24T19:59:17.5372 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.5373 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.5375 | GPTQ | METRIC - error 1527.33
2026-10-24T19:59:17.5377 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.5385 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.13.self_attn.o_proj']
2026-10-24T19:59:17.5427 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.5430 | GPTQ | METRIC - error 248.57
2026-10-24T19:59:17.5436 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.5443 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.13.mlp.gate_proj', 'model.layers.13.mlp.up_proj']
2026-10-24T19:59:17.5486 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.5489 | GPTQ | METRIC - error 254.64
2026-10-24T19:59:17.5494 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.5496 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.5499 | GPTQ | METRIC - error 287.10
2026-10-24T19:59:17.5503 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.5512 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.13.mlp.down_proj']

2026-10-24T19:59:17.5600 | GPTQ | METRIC - time 0.01s
2026-10-24T19:59:17.5604 | GPTQ | METRIC - error 1.74
2026-10-24T19:59:17.5608 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb

(15/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 962.24it/s]
(16/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 796.49it/s]

2026-10-24T19:59:17.7113 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.14.self_attn.q_proj']
2026-10-24T19:59:17.7144 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.7147 | GPTQ | METRIC - error 5153.09
2026-10-24T19:59:17.7151 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.7159 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.14.self_attn.k_proj', 'model.layers.14.self_attn.v_proj']
2026-10-24T19:59:17.7199 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.7201 | GPTQ | METRIC - error 1666.58
2026-10-24T19:59:17.7206 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.7209 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.7211 | GPTQ | METRIC - error 1275.33
2026-10-24T19:59:17.7215 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.7221 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.14.self_attn.o_proj']
2026-10-24T19:59:17.7261 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.7263 | GPTQ | METRIC - error 244.02
2026-10-24T19:59:17.7266 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.7272 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.14.mlp.gate_proj', 'model.layers.14.mlp.up_proj']

2026-10-24T19:59:17.7314 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.7316 | GPTQ | METRIC - error 222.45
2026-10-24T19:59:17.7319 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.7322 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.7323 | GPTQ | METRIC - error 251.36
2026-10-24T19:59:17.7326 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.7331 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.14.mlp.down_proj']
2026-10-24T19:59:17.7416 | GPTQ | METRIC - time 0.01s
2026-10-24T19:59:17.7418 | GPTQ | METRIC - error 1.23
2026-10-24T19:59:17.7421 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb

(16/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 938.06it/s]
(17/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 795.93it/s]

2026-10-24T19:59:17.8936 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.15.self_attn.q_proj']
2026-10-24T19:59:17.8967 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.8970 | GPTQ | METRIC - error 6666.47
2026-10-24T19:59:17.8974 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.8980 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.15.self_attn.k_proj', 'model.layers.15.self_attn.v_proj']
2026-10-24T19:59:17.9021 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.9024 | GPTQ | METRIC - error 1949.10
2026-10-24T19:59:17.9027 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.9030 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.9032 | GPTQ | METRIC - error 1594.82
2026-10-24T19:59:17.9036 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.9045 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.15.self_attn.o_proj']
2026-10-24T19:59:17.9086 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.9089 | GPTQ | METRIC - error 823.15
2026-10-24T19:59:17.9093 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.9101 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.15.mlp.gate_proj', 'model.layers.15.mlp.up_proj']

2026-10-24T19:59:17.9144 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.9147 | GPTQ | METRIC - error 157.12
2026-10-24T19:59:17.9152 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.9154 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:17.9157 | GPTQ | METRIC - error 172.65
2026-10-24T19:59:17.9161 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:17.9166 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.15.mlp.down_proj']
2026-10-24T19:59:17.9251 | GPTQ | METRIC - time 0.01s
2026-10-24T19:59:17.9255 | GPTQ | METRIC - error 0.91
2026-10-24T19:59:17.9258 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb

(17/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 958.36it/s]
(18/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 803.10it/s]

2026-10-24T19:59:18.0761 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.16.self_attn.q_proj']
2026-10-24T19:59:18.0794 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:18.0798 | GPTQ | METRIC - error 9436.80
2026-10-24T19:59:18.0801 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:18.0808 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.16.self_attn.k_proj', 'model.layers.16.self_attn.v_proj']
2026-10-24T19:59:18.0847 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:18.0849 | GPTQ | METRIC - error 2559.48
2026-10-24T19:59:18.0852 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:18.0853 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:18.0855 | GPTQ | METRIC - error 2532.06
2026-10-24T19:59:18.0858 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:18.0862 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.16.self_attn.o_proj']
2026-10-24T19:59:18.0901 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:18.0903 | GPTQ | METRIC - error 494.15
2026-10-24T19:59:18.0906 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:18.0911 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.16.mlp.gate_proj', 'model.layers.16.mlp.up_proj']

2026-10-24T19:59:18.0951 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:18.0953 | GPTQ | METRIC - error 153.09
2026-10-24T19:59:18.0955 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:18.0957 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:18.0958 | GPTQ | METRIC - error 167.89
2026-10-24T19:59:18.0960 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:18.0965 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.16.mlp.down_proj']
2026-10-24T19:59:18.1050 | GPTQ | METRIC - time 0.01s
2026-10-24T19:59:18.1053 | GPTQ | METRIC - error 1.16
2026-10-24T19:59:18.1056 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb

(18/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 959.34it/s]
(19/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 775.04it/s]

2026-10-24T19:59:18.2579 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.17.self_attn.q_proj']
2026-10-24T19:59:18.2609 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:18.2613 | GPTQ | METRIC - error 2351.42
2026-10-24T19:59:18.2617 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:18.2624 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.17.self_attn.k_proj', 'model.layers.17.self_attn.v_proj']
2026-10-24T19:59:18.2676 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:18.2680 | GPTQ | METRIC - error 711.63
2026-10-24T19:59:18.2684 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:18.2685 | GPTQ | METRIC - time 0.01s
2026-10-24T19:59:18.2687 | GPTQ | METRIC - error 761.95
2026-10-24T19:59:18.2690 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:18.2695 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.17.self_attn.o_proj']
2026-10-24T19:59:18.2736 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:18.2738 | GPTQ | METRIC - error 309.28
2026-10-24T19:59:18.2740 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:18.2746 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.17.mlp.gate_proj', 'model.layers.17.mlp.up_proj']

2026-10-24T19:59:18.2787 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:18.2789 | GPTQ | METRIC - error 210.16
2026-10-24T19:59:18.2792 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:18.2793 | GPTQ | METRIC - time 0.00s
2026-10-24T19:59:18.2795 | GPTQ | METRIC - error 214.81
2026-10-24T19:59:18.2799 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb
2026-10-24T19:59:18.2810 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.17.mlp.down_proj']
2026-10-24T19:59:18.2912 | GPTQ | METRIC - time 0.01s
2026-10-24T19:59:18.2915 | GPTQ | METRIC - error 1.81
2026-10-24T19:59:18.2919 | GPTQ | METRIC - Accelerator 0 | usage: 39.17% | total memory: 16.7 Gb

(19/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 990.15it/s]

2026-10-24T19:59:18.3613 | norm_calibration_context | INFO - Restoring 109 norm modules to offset convention
2026-10-24T19:59:18.3641 | finalize | INFO - Compression lifecycle finalized for 1 modifiers

2026-10-24T20:03:07.8784 | reset | INFO - Compression lifecycle reset

Testing: {'actorder': 'static', 'dampening_frac': 0.05}

Loading weights: 100%|██████████| 236/236 [00:00<00:00, 6085.32it/s]

2026-10-24T20:03:08.9933 | reset | INFO - Compression lifecycle reset
2026-10-24T20:03:09.0008 | norm_calibration_context | INFO - Found 109 offset-norm modules to convert
2026-10-24T20:03:09.0065 | from_modifiers | INFO - Creating recipe from modifiers

Applying quantization config: 100%|██████████| 126/126 [00:00<00:00, 10938.94it/s]

2026-10-24T20:03:09.0234 | initialize | INFO - Compression lifecycle initialized for 1 modifiers
2026-10-24T20:03:09.0238 | IndependentPipeline | INFO - Inferred `SequentialPipeline` for `GPTQModifier`

Preparing cache: 100%|██████████| 64/64 [00:00<00:00, 4733.64it/s]
(1/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 1397.94it/s]
(1/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 592.20it/s]
(2/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 791.03it/s]

2026-10-24T20:03:09.3179 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.0.self_attn.q_proj']
2026-10-24T20:03:09.3213 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:09.3216 | GPTQ | METRIC - error 249833.22
2026-10-24T20:03:09.3219 | GPTQ | METRIC - Accelerator 0 | usage: 45.44% | total memory: 16.7 Gb
2026-10-24T20:03:09.3226 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.0.self_attn.k_proj', 'model.layers.0.self_attn.v_proj']

2026-10-24T20:03:09.3268 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:09.3269 | GPTQ | METRIC - error 54693.98
2026-10-24T20:03:09.3272 | GPTQ | METRIC - Accelerator 0 | usage: 45.44% | total memory: 16.7 Gb
2026-10-24T20:03:09.3274 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:09.3276 | GPTQ | METRIC - error 63844.53
2026-10-24T20:03:09.3278 | GPTQ | METRIC - Accelerator 0 | usage: 45.44% | total memory: 16.7 Gb
2026-10-24T20:03:09.3284 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.0.self_attn.o_proj']
2026-10-24T20:03:09.3326 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:09.3328 | GPTQ | METRIC - error 37953.85
2026-10-24T20:03:09.3332 | GPTQ | METRIC - Accelerator 0 | usage: 45.44% | total memory: 16.7 Gb
2026-10-24T20:03:09.3338 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.0.mlp.gate_proj', 'model.layers.0.mlp.up_proj']
2026-10-24T20:03:09.3382 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:09.3384 | GPTQ | METRIC - error 11619.00
2026-10-24T20:03:09.3387 | GPTQ | METRIC - Accelerator 0 | usage: 45.44% | total memory: 16.7 Gb
2026-10-24T20:03:09.3389 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:09.3390 | GPTQ | METRIC - error 12514.36
2026-10-24T20:03:09.3393 | GPTQ | METRIC - Accelerator 0 | usage: 45.44% | total memory: 16.7 Gb
2026-10-24T20:03:09.3399 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.0.mlp.down_proj']
2026-10-24T20:03:09.3486 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:09.3489 | GPTQ | METRIC - error 2322.19
2026-10-24T20:03:09.3493 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb

(2/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 865.54it/s]
(3/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 801.69it/s]

2026-10-24T20:03:09.5060 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.1.self_attn.q_proj']
2026-10-24T20:03:09.5092 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:09.5095 | GPTQ | METRIC - error 117426.31
2026-10-24T20:03:09.5099 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:09.5107 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.1.self_attn.k_proj', 'model.layers.1.self_attn.v_proj']
2026-10-24T20:03:09.5147 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:09.5149 | GPTQ | METRIC - error 27910.62
2026-10-24T20:03:09.5152 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:09.5153 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:09.5155 | GPTQ | METRIC - error 27073.88
2026-10-24T20:03:09.5158 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:09.5164 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.1.self_attn.o_proj']

2026-10-24T20:03:09.5207 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:09.5210 | GPTQ | METRIC - error 5653.68
2026-10-24T20:03:09.5214 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:09.5220 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.1.mlp.gate_proj', 'model.layers.1.mlp.up_proj']
2026-10-24T20:03:09.5265 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:09.5267 | GPTQ | METRIC - error 3591.68
2026-10-24T20:03:09.5270 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:09.5271 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:09.5272 | GPTQ | METRIC - error 3655.71
2026-10-24T20:03:09.5275 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:09.5281 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.1.mlp.down_proj']
2026-10-24T20:03:09.5367 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:09.5370 | GPTQ | METRIC - error 99.35
2026-10-24T20:03:09.5375 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb

(3/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 930.97it/s]
(4/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 790.53it/s]

2026-10-24T20:03:09.6902 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.2.self_attn.q_proj']
2026-10-24T20:03:09.6932 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:09.6936 | GPTQ | METRIC - error 2906.41
2026-10-24T20:03:09.6941 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:09.6947 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.2.self_attn.k_proj', 'model.layers.2.self_attn.v_proj']
2026-10-24T20:03:09.6987 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:09.6988 | GPTQ | METRIC - error 741.48
2026-10-24T20:03:09.6992 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:09.6993 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:09.6994 | GPTQ | METRIC - error 749.42
2026-10-24T20:03:09.6997 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:09.7004 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.2.self_attn.o_proj']
2026-10-24T20:03:09.7044 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:09.7047 | GPTQ | METRIC - error 525.07

2026-10-24T20:03:09.7051 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:09.7058 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.2.mlp.gate_proj', 'model.layers.2.mlp.up_proj']
2026-10-24T20:03:09.7102 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:09.7104 | GPTQ | METRIC - error 2186.34
2026-10-24T20:03:09.7108 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:09.7110 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:09.7111 | GPTQ | METRIC - error 2204.57
2026-10-24T20:03:09.7114 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:09.7120 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.2.mlp.down_proj']
2026-10-24T20:03:09.7211 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:09.7215 | GPTQ | METRIC - error 37.22
2026-10-24T20:03:09.7219 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb

(4/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 914.61it/s]
(5/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 792.25it/s]

2026-10-24T20:03:09.8765 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.3.self_attn.q_proj']
2026-10-24T20:03:09.8797 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:09.8801 | GPTQ | METRIC - error 3376.22
2026-10-24T20:03:09.8805 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:09.8812 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.3.self_attn.k_proj', 'model.layers.3.self_attn.v_proj']
2026-10-24T20:03:09.8852 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:09.8855 | GPTQ | METRIC - error 781.66
2026-10-24T20:03:09.8857 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:09.8859 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:09.8861 | GPTQ | METRIC - error 982.94
2026-10-24T20:03:09.8865 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:09.8871 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.3.self_attn.o_proj']

2026-10-24T20:03:09.8913 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:09.8915 | GPTQ | METRIC - error 132.10
2026-10-24T20:03:09.8918 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:09.8924 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.3.mlp.gate_proj', 'model.layers.3.mlp.up_proj']
2026-10-24T20:03:09.8966 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:09.8968 | GPTQ | METRIC - error 1920.49
2026-10-24T20:03:09.8971 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:09.8973 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:09.8974 | GPTQ | METRIC - error 1842.09
2026-10-24T20:03:09.8977 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:09.8982 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.3.mlp.down_proj']
2026-10-24T20:03:09.9068 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:09.9071 | GPTQ | METRIC - error 47.92
2026-10-24T20:03:09.9074 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb

(5/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 919.11it/s]
(6/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 797.24it/s]

2026-10-24T20:03:10.0602 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.4.self_attn.q_proj']
2026-10-24T20:03:10.0632 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.0634 | GPTQ | METRIC - error 2640.63
2026-10-24T20:03:10.0638 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.0644 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.4.self_attn.k_proj', 'model.layers.4.self_attn.v_proj']
2026-10-24T20:03:10.0685 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.0687 | GPTQ | METRIC - error 698.52
2026-10-24T20:03:10.0692 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.0695 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.0697 | GPTQ | METRIC - error 601.17
2026-10-24T20:03:10.0701 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.0706 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.4.self_attn.o_proj']
2026-10-24T20:03:10.0750 | GPTQ | METRIC - time 0.00s

2026-10-24T20:03:10.0755 | GPTQ | METRIC - error 78.52
2026-10-24T20:03:10.0765 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.0779 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.4.mlp.gate_proj', 'model.layers.4.mlp.up_proj']
2026-10-24T20:03:10.0845 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:10.0850 | GPTQ | METRIC - error 1328.12
2026-10-24T20:03:10.0856 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.0860 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:10.0862 | GPTQ | METRIC - error 1371.52
2026-10-24T20:03:10.0869 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.0880 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.4.mlp.down_proj']
2026-10-24T20:03:10.0996 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:10.1000 | GPTQ | METRIC - error 8.88
2026-10-24T20:03:10.1006 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb

(6/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 922.05it/s]
(7/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 804.23it/s]

2026-10-24T20:03:10.2535 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.5.self_attn.q_proj']
2026-10-24T20:03:10.2567 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.2570 | GPTQ | METRIC - error 1395.88
2026-10-24T20:03:10.2576 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.2584 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.5.self_attn.k_proj', 'model.layers.5.self_attn.v_proj']

2026-10-24T20:03:10.2628 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.2631 | GPTQ | METRIC - error 393.15
2026-10-24T20:03:10.2634 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.2638 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.2642 | GPTQ | METRIC - error 892.75
2026-10-24T20:03:10.2646 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.2655 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.5.self_attn.o_proj']
2026-10-24T20:03:10.2696 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.2698 | GPTQ | METRIC - error 135.75
2026-10-24T20:03:10.2702 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.2709 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.5.mlp.gate_proj', 'model.layers.5.mlp.up_proj']
2026-10-24T20:03:10.2752 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.2755 | GPTQ | METRIC - error 928.77
2026-10-24T20:03:10.2759 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.2760 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.2762 | GPTQ | METRIC - error 944.11
2026-10-24T20:03:10.2765 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.2770 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.5.mlp.down_proj']
2026-10-24T20:03:10.2856 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:10.2859 | GPTQ | METRIC - error 22.98
2026-10-24T20:03:10.2862 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb

(7/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 929.67it/s]
(8/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 796.42it/s]

2026-10-24T20:03:10.4384 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.6.self_attn.q_proj']
2026-10-24T20:03:10.4415 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.4418 | GPTQ | METRIC - error 1982.13
2026-10-24T20:03:10.4422 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.4429 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.6.self_attn.k_proj', 'model.layers.6.self_attn.v_proj']
2026-10-24T20:03:10.4471 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.4474 | GPTQ | METRIC - error 489.57
2026-10-24T20:03:10.4478 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.4480 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.4482 | GPTQ | METRIC - error 530.55
2026-10-24T20:03:10.4485 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.4491 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.6.self_attn.o_proj']

2026-10-24T20:03:10.4537 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.4540 | GPTQ | METRIC - error 98.02
2026-10-24T20:03:10.4544 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.4551 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.6.mlp.gate_proj', 'model.layers.6.mlp.up_proj']
2026-10-24T20:03:10.4595 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.4597 | GPTQ | METRIC - error 658.55
2026-10-24T20:03:10.4601 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.4602 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.4606 | GPTQ | METRIC - error 697.90
2026-10-24T20:03:10.4611 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.4618 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.6.mlp.down_proj']
2026-10-24T20:03:10.4705 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:10.4708 | GPTQ | METRIC - error 5.55
2026-10-24T20:03:10.4711 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb

(8/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 948.29it/s]
(9/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 827.95it/s]

2026-10-24T20:03:10.6188 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.7.self_attn.q_proj']
2026-10-24T20:03:10.6219 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.6222 | GPTQ | METRIC - error 5026.82
2026-10-24T20:03:10.6226 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.6234 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.7.self_attn.k_proj', 'model.layers.7.self_attn.v_proj']
2026-10-24T20:03:10.6276 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.6278 | GPTQ | METRIC - error 1319.26
2026-10-24T20:03:10.6283 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.6285 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.6287 | GPTQ | METRIC - error 1191.86
2026-10-24T20:03:10.6291 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.6298 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.7.self_attn.o_proj']
2026-10-24T20:03:10.6340 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.6342 | GPTQ | METRIC - error 447.57
2026-10-24T20:03:10.6346 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.6353 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.7.mlp.gate_proj', 'model.layers.7.mlp.up_proj']

2026-10-24T20:03:10.6399 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.6401 | GPTQ | METRIC - error 619.60
2026-10-24T20:03:10.6405 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.6407 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.6409 | GPTQ | METRIC - error 693.29
2026-10-24T20:03:10.6413 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.6419 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.7.mlp.down_proj']
2026-10-24T20:03:10.6507 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:10.6510 | GPTQ | METRIC - error 11.62
2026-10-24T20:03:10.6514 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb

(9/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 936.11it/s]
(10/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 794.22it/s]

2026-10-24T20:03:10.8034 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.8.self_attn.q_proj']
2026-10-24T20:03:10.8065 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.8068 | GPTQ | METRIC - error 4770.21
2026-10-24T20:03:10.8073 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.8080 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.8.self_attn.k_proj', 'model.layers.8.self_attn.v_proj']
2026-10-24T20:03:10.8122 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.8125 | GPTQ | METRIC - error 1225.08
2026-10-24T20:03:10.8129 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.8131 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.8133 | GPTQ | METRIC - error 1329.12
2026-10-24T20:03:10.8137 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.8144 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.8.self_attn.o_proj']

2026-10-24T20:03:10.8190 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.8193 | GPTQ | METRIC - error 329.94
2026-10-24T20:03:10.8196 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.8203 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.8.mlp.gate_proj', 'model.layers.8.mlp.up_proj']
2026-10-24T20:03:10.8248 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.8251 | GPTQ | METRIC - error 616.53
2026-10-24T20:03:10.8255 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.8257 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:10.8259 | GPTQ | METRIC - error 682.43
2026-10-24T20:03:10.8263 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.8269 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.8.mlp.down_proj']
2026-10-24T20:03:10.8358 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:10.8361 | GPTQ | METRIC - error 5.44
2026-10-24T20:03:10.8365 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb

(10/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 954.36it/s]
(11/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 793.85it/s]

2026-10-24T20:03:10.9876 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.9.self_attn.q_proj']
2026-10-24T20:03:10.9913 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.9916 | GPTQ | METRIC - error 3775.99
2026-10-24T20:03:10.9920 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.9927 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.9.self_attn.k_proj', 'model.layers.9.self_attn.v_proj']
2026-10-24T20:03:10.9968 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.9971 | GPTQ | METRIC - error 949.80
2026-10-24T20:03:10.9975 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.9977 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:10.9979 | GPTQ | METRIC - error 974.39
2026-10-24T20:03:10.9983 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:10.9989 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.9.self_attn.o_proj']
2026-10-24T20:03:11.0030 | GPTQ | METRIC - time 0.00s

2026-10-24T20:03:11.0033 | GPTQ | METRIC - error 180.56
2026-10-24T20:03:11.0039 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.0046 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.9.mlp.gate_proj', 'model.layers.9.mlp.up_proj']
2026-10-24T20:03:11.0089 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.0092 | GPTQ | METRIC - error 273.84
2026-10-24T20:03:11.0095 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.0097 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.0100 | GPTQ | METRIC - error 310.62
2026-10-24T20:03:11.0103 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.0108 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.9.mlp.down_proj']
2026-10-24T20:03:11.0193 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:11.0195 | GPTQ | METRIC - error 3.85
2026-10-24T20:03:11.0198 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb

(11/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 996.53it/s]
(12/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 821.54it/s]

2026-10-24T20:03:11.1649 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.10.self_attn.q_proj']
2026-10-24T20:03:11.1682 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.1684 | GPTQ | METRIC - error 5301.32
2026-10-24T20:03:11.1689 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.1696 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.10.self_attn.k_proj', 'model.layers.10.self_attn.v_proj']
2026-10-24T20:03:11.1738 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.1741 | GPTQ | METRIC - error 1486.94
2026-10-24T20:03:11.1744 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.1746 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.1748 | GPTQ | METRIC - error 1215.41
2026-10-24T20:03:11.1752 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.1759 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.10.self_attn.o_proj']
2026-10-24T20:03:11.1801 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.1804 | GPTQ | METRIC - error 482.30
2026-10-24T20:03:11.1807 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.1814 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.10.mlp.gate_proj', 'model.layers.10.mlp.up_proj']
2026-10-24T20:03:11.1857 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.1860 | GPTQ | METRIC - error 501.31

2026-10-24T20:03:11.1868 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.1870 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:11.1872 | GPTQ | METRIC - error 533.14
2026-10-24T20:03:11.1878 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.1885 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.10.mlp.down_proj']
2026-10-24T20:03:11.1974 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:11.1977 | GPTQ | METRIC - error 4.94
2026-10-24T20:03:11.1982 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb

(12/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 842.29it/s]
(13/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 795.60it/s]

2026-10-24T20:03:11.3584 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.11.self_attn.q_proj']
2026-10-24T20:03:11.3616 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.3620 | GPTQ | METRIC - error 411.21
2026-10-24T20:03:11.3625 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.3632 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.11.self_attn.k_proj', 'model.layers.11.self_attn.v_proj']

2026-10-24T20:03:11.3675 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.3679 | GPTQ | METRIC - error 154.22
2026-10-24T20:03:11.3683 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.3685 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.3686 | GPTQ | METRIC - error 163.60
2026-10-24T20:03:11.3689 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.3695 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.11.self_attn.o_proj']
2026-10-24T20:03:11.3737 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.3739 | GPTQ | METRIC - error 59.99
2026-10-24T20:03:11.3743 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.3750 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.11.mlp.gate_proj', 'model.layers.11.mlp.up_proj']
2026-10-24T20:03:11.3792 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.3795 | GPTQ | METRIC - error 821.75
2026-10-24T20:03:11.3799 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.3800 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.3801 | GPTQ | METRIC - error 904.03
2026-10-24T20:03:11.3804 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.3809 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.11.mlp.down_proj']
2026-10-24T20:03:11.3896 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:11.3898 | GPTQ | METRIC - error 17.43
2026-10-24T20:03:11.3902 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb

(13/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 945.35it/s]
(14/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 790.32it/s]

2026-10-24T20:03:11.5417 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.12.self_attn.q_proj']
2026-10-24T20:03:11.5447 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.5449 | GPTQ | METRIC - error 4422.76
2026-10-24T20:03:11.5453 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.5459 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.12.self_attn.k_proj', 'model.layers.12.self_attn.v_proj']
2026-10-24T20:03:11.5499 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.5502 | GPTQ | METRIC - error 1901.36
2026-10-24T20:03:11.5505 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.5506 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.5508 | GPTQ | METRIC - error 1147.23
2026-10-24T20:03:11.5511 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.5516 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.12.self_attn.o_proj']
2026-10-24T20:03:11.5556 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.5559 | GPTQ | METRIC - error 354.14
2026-10-24T20:03:11.5563 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.5569 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.12.mlp.gate_proj', 'model.layers.12.mlp.up_proj']

2026-10-24T20:03:11.5611 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.5615 | GPTQ | METRIC - error 464.13
2026-10-24T20:03:11.5618 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.5622 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.5624 | GPTQ | METRIC - error 480.26
2026-10-24T20:03:11.5630 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.5637 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.12.mlp.down_proj']
2026-10-24T20:03:11.5725 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:11.5728 | GPTQ | METRIC - error 8.93
2026-10-24T20:03:11.5733 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb

(14/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 945.78it/s]
(15/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 796.16it/s]

2026-10-24T20:03:11.7246 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.13.self_attn.q_proj']
2026-10-24T20:03:11.7278 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.7281 | GPTQ | METRIC - error 8116.11
2026-10-24T20:03:11.7285 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.7292 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.13.self_attn.k_proj', 'model.layers.13.self_attn.v_proj']
2026-10-24T20:03:11.7334 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.7337 | GPTQ | METRIC - error 2222.26
2026-10-24T20:03:11.7341 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.7343 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.7345 | GPTQ | METRIC - error 2532.51
2026-10-24T20:03:11.7349 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.7355 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.13.self_attn.o_proj']
2026-10-24T20:03:11.7397 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.7399 | GPTQ | METRIC - error 347.44
2026-10-24T20:03:11.7403 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb

2026-10-24T20:03:11.7411 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.13.mlp.gate_proj', 'model.layers.13.mlp.up_proj']
2026-10-24T20:03:11.7454 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.7457 | GPTQ | METRIC - error 318.82
2026-10-24T20:03:11.7461 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.7463 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.7465 | GPTQ | METRIC - error 360.02
2026-10-24T20:03:11.7469 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.7475 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.13.mlp.down_proj']
2026-10-24T20:03:11.7564 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:11.7567 | GPTQ | METRIC - error 2.84
2026-10-24T20:03:11.7572 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb

(15/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 945.13it/s]
(16/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 790.19it/s]

2026-10-24T20:03:11.9089 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.14.self_attn.q_proj']
2026-10-24T20:03:11.9121 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.9125 | GPTQ | METRIC - error 6871.80
2026-10-24T20:03:11.9129 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.9136 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.14.self_attn.k_proj', 'model.layers.14.self_attn.v_proj']
2026-10-24T20:03:11.9178 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.9180 | GPTQ | METRIC - error 2211.91
2026-10-24T20:03:11.9185 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.9187 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.9189 | GPTQ | METRIC - error 1687.05
2026-10-24T20:03:11.9193 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.9199 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.14.self_attn.o_proj']
2026-10-24T20:03:11.9241 | GPTQ | METRIC - time 0.00s

2026-10-24T20:03:11.9244 | GPTQ | METRIC - error 349.04
2026-10-24T20:03:11.9249 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.9256 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.14.mlp.gate_proj', 'model.layers.14.mlp.up_proj']
2026-10-24T20:03:11.9299 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.9301 | GPTQ | METRIC - error 276.78
2026-10-24T20:03:11.9305 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.9307 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:11.9309 | GPTQ | METRIC - error 312.40
2026-10-24T20:03:11.9312 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:11.9319 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.14.mlp.down_proj']
2026-10-24T20:03:11.9407 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:11.9410 | GPTQ | METRIC - error 2.01
2026-10-24T20:03:11.9414 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb

(16/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 943.31it/s]
(17/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 792.64it/s]

2026-10-24T20:03:12.0931 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.15.self_attn.q_proj']
2026-10-24T20:03:12.0962 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:12.0965 | GPTQ | METRIC - error 8639.13
2026-10-24T20:03:12.0969 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:12.0976 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.15.self_attn.k_proj', 'model.layers.15.self_attn.v_proj']
2026-10-24T20:03:12.1018 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:12.1020 | GPTQ | METRIC - error 2518.42
2026-10-24T20:03:12.1024 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:12.1026 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:12.1028 | GPTQ | METRIC - error 2062.14
2026-10-24T20:03:12.1032 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:12.1038 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.15.self_attn.o_proj']
2026-10-24T20:03:12.1081 | GPTQ | METRIC - time 0.00s

2026-10-24T20:03:12.1085 | GPTQ | METRIC - error 970.15
2026-10-24T20:03:12.1089 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:12.1096 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.15.mlp.gate_proj', 'model.layers.15.mlp.up_proj']
2026-10-24T20:03:12.1139 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:12.1142 | GPTQ | METRIC - error 194.34
2026-10-24T20:03:12.1146 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:12.1149 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:12.1151 | GPTQ | METRIC - error 213.64
2026-10-24T20:03:12.1155 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:12.1162 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.15.mlp.down_proj']
2026-10-24T20:03:12.1254 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:12.1257 | GPTQ | METRIC - error 1.57
2026-10-24T20:03:12.1261 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb

(17/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 923.30it/s]
(18/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 782.78it/s]

2026-10-24T20:03:12.2802 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.16.self_attn.q_proj']
2026-10-24T20:03:12.2833 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:12.2836 | GPTQ | METRIC - error 12232.06
2026-10-24T20:03:12.2841 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:12.2848 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.16.self_attn.k_proj', 'model.layers.16.self_attn.v_proj']
2026-10-24T20:03:12.2890 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:12.2892 | GPTQ | METRIC - error 3324.07
2026-10-24T20:03:12.2896 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:12.2898 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:12.2900 | GPTQ | METRIC - error 3299.17
2026-10-24T20:03:12.2904 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:12.2910 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.16.self_attn.o_proj']

2026-10-24T20:03:12.2953 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:12.2955 | GPTQ | METRIC - error 687.65
2026-10-24T20:03:12.2960 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:12.2967 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.16.mlp.gate_proj', 'model.layers.16.mlp.up_proj']
2026-10-24T20:03:12.3009 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:12.3012 | GPTQ | METRIC - error 193.71
2026-10-24T20:03:12.3016 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:12.3018 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:12.3020 | GPTQ | METRIC - error 212.45
2026-10-24T20:03:12.3024 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:12.3031 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.16.mlp.down_proj']
2026-10-24T20:03:12.3121 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:12.3124 | GPTQ | METRIC - error 2.02
2026-10-24T20:03:12.3128 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb

(18/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 921.47it/s]
(19/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 754.61it/s]

2026-10-24T20:03:12.4701 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.17.self_attn.q_proj']
2026-10-24T20:03:12.4732 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:12.4735 | GPTQ | METRIC - error 3377.03
2026-10-24T20:03:12.4739 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:12.4746 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.17.self_attn.k_proj', 'model.layers.17.self_attn.v_proj']
2026-10-24T20:03:12.4788 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:12.4790 | GPTQ | METRIC - error 1021.28

2026-10-24T20:03:12.4795 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:12.4797 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:12.4799 | GPTQ | METRIC - error 1095.88
2026-10-24T20:03:12.4803 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:12.4810 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.17.self_attn.o_proj']
2026-10-24T20:03:12.4853 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:12.4857 | GPTQ | METRIC - error 411.07
2026-10-24T20:03:12.4861 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:12.4869 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.17.mlp.gate_proj', 'model.layers.17.mlp.up_proj']
2026-10-24T20:03:12.4912 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:12.4915 | GPTQ | METRIC - error 308.97
2026-10-24T20:03:12.4919 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:12.4921 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:12.4923 | GPTQ | METRIC - error 315.60
2026-10-24T20:03:12.4927 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb
2026-10-24T20:03:12.4933 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.17.mlp.down_proj']
2026-10-24T20:03:12.5026 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:12.5029 | GPTQ | METRIC - error 3.37
2026-10-24T20:03:12.5034 | GPTQ | METRIC - Accelerator 0 | usage: 45.60% | total memory: 16.7 Gb

(19/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 1003.37it/s]

2026-10-24T20:03:12.5723 | norm_calibration_context | INFO - Restoring 109 norm modules to offset convention
2026-10-24T20:03:12.5750 | finalize | INFO - Compression lifecycle finalized for 1 modifiers

2026-10-24T20:03:31.8022 | reset | INFO - Compression lifecycle reset

Testing: {'actorder': 'static', 'dampening_frac': 0.1}

Loading weights: 100%|██████████| 236/236 [00:00<00:00, 6103.70it/s]

2026-10-24T20:03:32.9597 | reset | INFO - Compression lifecycle reset
2026-10-24T20:03:32.9632 | norm_calibration_context | INFO - Found 109 offset-norm modules to convert
2026-10-24T20:03:32.9665 | from_modifiers | INFO - Creating recipe from modifiers

Applying quantization config: 100%|██████████| 126/126 [00:00<00:00, 12486.00it/s]

2026-10-24T20:03:32.9821 | initialize | INFO - Compression lifecycle initialized for 1 modifiers
2026-10-24T20:03:32.9826 | IndependentPipeline | INFO - Inferred `SequentialPipeline` for `GPTQModifier`

Preparing cache: 100%|██████████| 64/64 [00:00<00:00, 4718.25it/s]
(1/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 1350.22it/s]
(1/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 610.67it/s]
(2/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 764.74it/s]

2026-10-24T20:03:33.2794 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.0.self_attn.q_proj']
2026-10-24T20:03:33.2826 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:33.2828 | GPTQ | METRIC - error 319386.00
2026-10-24T20:03:33.2833 | GPTQ | METRIC - Accelerator 0 | usage: 51.88% | total memory: 16.7 Gb
2026-10-24T20:03:33.2840 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.0.self_attn.k_proj', 'model.layers.0.self_attn.v_proj']
2026-10-24T20:03:33.2881 | GPTQ | METRIC - time 0.00s

2026-10-24T20:03:33.2884 | GPTQ | METRIC - error 69724.80
2026-10-24T20:03:33.2889 | GPTQ | METRIC - Accelerator 0 | usage: 51.88% | total memory: 16.7 Gb
2026-10-24T20:03:33.2891 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:33.2893 | GPTQ | METRIC - error 81659.81
2026-10-24T20:03:33.2897 | GPTQ | METRIC - Accelerator 0 | usage: 51.88% | total memory: 16.7 Gb
2026-10-24T20:03:33.2903 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.0.self_attn.o_proj']
2026-10-24T20:03:33.2945 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:33.2948 | GPTQ | METRIC - error 50920.61
2026-10-24T20:03:33.2953 | GPTQ | METRIC - Accelerator 0 | usage: 51.88% | total memory: 16.7 Gb
2026-10-24T20:03:33.2960 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.0.mlp.gate_proj', 'model.layers.0.mlp.up_proj']
2026-10-24T20:03:33.3005 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:33.3008 | GPTQ | METRIC - error 13601.74
2026-10-24T20:03:33.3012 | GPTQ | METRIC - Accelerator 0 | usage: 51.88% | total memory: 16.7 Gb
2026-10-24T20:03:33.3014 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:33.3016 | GPTQ | METRIC - error 14646.02
2026-10-24T20:03:33.3020 | GPTQ | METRIC - Accelerator 0 | usage: 51.88% | total memory: 16.7 Gb
2026-10-24T20:03:33.3025 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.0.mlp.down_proj']
2026-10-24T20:03:33.3114 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:33.3118 | GPTQ | METRIC - error 3013.27
2026-10-24T20:03:33.3121 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb

(2/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 927.40it/s]
(3/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 777.51it/s]

2026-10-24T20:03:33.4667 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.1.self_attn.q_proj']
2026-10-24T20:03:33.4698 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:33.4700 | GPTQ | METRIC - error 132596.30
2026-10-24T20:03:33.4704 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:33.4712 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.1.self_attn.k_proj', 'model.layers.1.self_attn.v_proj']
2026-10-24T20:03:33.4753 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:33.4756 | GPTQ | METRIC - error 31748.32
2026-10-24T20:03:33.4760 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:33.4762 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:33.4764 | GPTQ | METRIC - error 30732.37
2026-10-24T20:03:33.4768 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:33.4775 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.1.self_attn.o_proj']

2026-10-24T20:03:33.4819 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:33.4824 | GPTQ | METRIC - error 7083.44
2026-10-24T20:03:33.4829 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:33.4839 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.1.mlp.gate_proj', 'model.layers.1.mlp.up_proj']
2026-10-24T20:03:33.4883 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:33.4887 | GPTQ | METRIC - error 4024.90
2026-10-24T20:03:33.4891 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:33.4894 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:33.4896 | GPTQ | METRIC - error 4096.77
2026-10-24T20:03:33.4900 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:33.4906 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.1.mlp.down_proj']
2026-10-24T20:03:33.4994 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:33.4996 | GPTQ | METRIC - error 112.63
2026-10-24T20:03:33.5001 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb

(3/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 927.12it/s]
(4/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 803.60it/s]

2026-10-24T20:03:33.6522 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.2.self_attn.q_proj']
2026-10-24T20:03:33.6553 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:33.6556 | GPTQ | METRIC - error 3494.19
2026-10-24T20:03:33.6559 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:33.6565 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.2.self_attn.k_proj', 'model.layers.2.self_attn.v_proj']
2026-10-24T20:03:33.6606 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:33.6608 | GPTQ | METRIC - error 893.47
2026-10-24T20:03:33.6611 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:33.6614 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:33.6616 | GPTQ | METRIC - error 903.47
2026-10-24T20:03:33.6619 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:33.6624 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.2.self_attn.o_proj']

2026-10-24T20:03:33.6669 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:33.6672 | GPTQ | METRIC - error 648.54
2026-10-24T20:03:33.6675 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:33.6681 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.2.mlp.gate_proj', 'model.layers.2.mlp.up_proj']
2026-10-24T20:03:33.6726 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:33.6728 | GPTQ | METRIC - error 2469.43
2026-10-24T20:03:33.6731 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:33.6732 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:33.6734 | GPTQ | METRIC - error 2489.75
2026-10-24T20:03:33.6737 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:33.6742 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.2.mlp.down_proj']
2026-10-24T20:03:33.6834 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:33.6836 | GPTQ | METRIC - error 43.03
2026-10-24T20:03:33.6839 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb

(4/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 910.35it/s]
(5/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 784.06it/s]

2026-10-24T20:03:33.8388 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.3.self_attn.q_proj']
2026-10-24T20:03:33.8419 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:33.8423 | GPTQ | METRIC - error 3988.54
2026-10-24T20:03:33.8427 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:33.8435 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.3.self_attn.k_proj', 'model.layers.3.self_attn.v_proj']
2026-10-24T20:03:33.8478 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:33.8482 | GPTQ | METRIC - error 921.73
2026-10-24T20:03:33.8486 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:33.8489 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:33.8492 | GPTQ | METRIC - error 1158.83
2026-10-24T20:03:33.8496 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:33.8504 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.3.self_attn.o_proj']

2026-10-24T20:03:33.8545 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:33.8547 | GPTQ | METRIC - error 164.45
2026-10-24T20:03:33.8551 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:33.8557 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.3.mlp.gate_proj', 'model.layers.3.mlp.up_proj']
2026-10-24T20:03:33.8601 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:33.8604 | GPTQ | METRIC - error 2247.34
2026-10-24T20:03:33.8607 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:33.8609 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:33.8612 | GPTQ | METRIC - error 2156.25
2026-10-24T20:03:33.8615 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:33.8622 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.3.mlp.down_proj']
2026-10-24T20:03:33.8710 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:33.8712 | GPTQ | METRIC - error 58.16
2026-10-24T20:03:33.8716 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb

(5/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 939.92it/s]
(6/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 771.26it/s]

2026-10-24T20:03:34.0257 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.4.self_attn.q_proj']
2026-10-24T20:03:34.0288 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.0291 | GPTQ | METRIC - error 3299.79
2026-10-24T20:03:34.0294 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.0301 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.4.self_attn.k_proj', 'model.layers.4.self_attn.v_proj']
2026-10-24T20:03:34.0341 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.0343 | GPTQ | METRIC - error 875.11
2026-10-24T20:03:34.0346 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.0347 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.0349 | GPTQ | METRIC - error 755.26
2026-10-24T20:03:34.0352 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.0356 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.4.self_attn.o_proj']

2026-10-24T20:03:34.0397 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.0398 | GPTQ | METRIC - error 102.39
2026-10-24T20:03:34.0401 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.0409 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.4.mlp.gate_proj', 'model.layers.4.mlp.up_proj']
2026-10-24T20:03:34.0453 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.0455 | GPTQ | METRIC - error 1676.70
2026-10-24T20:03:34.0459 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.0460 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.0461 | GPTQ | METRIC - error 1731.17
2026-10-24T20:03:34.0464 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.0469 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.4.mlp.down_proj']
2026-10-24T20:03:34.0562 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:34.0565 | GPTQ | METRIC - error 10.86
2026-10-24T20:03:34.0569 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb

(6/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 943.56it/s]
(7/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 790.89it/s]

2026-10-24T20:03:34.2087 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.5.self_attn.q_proj']
2026-10-24T20:03:34.2117 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.2120 | GPTQ | METRIC - error 1744.89
2026-10-24T20:03:34.2123 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.2130 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.5.self_attn.k_proj', 'model.layers.5.self_attn.v_proj']
2026-10-24T20:03:34.2170 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.2172 | GPTQ | METRIC - error 490.88
2026-10-24T20:03:34.2176 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.2177 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.2179 | GPTQ | METRIC - error 1116.08
2026-10-24T20:03:34.2182 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.2187 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.5.self_attn.o_proj']
2026-10-24T20:03:34.2228 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.2239 | GPTQ | METRIC - error 178.51
2026-10-24T20:03:34.2243 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb

2026-10-24T20:03:34.2252 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.5.mlp.gate_proj', 'model.layers.5.mlp.up_proj']
2026-10-24T20:03:34.2296 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.2299 | GPTQ | METRIC - error 1118.68
2026-10-24T20:03:34.2302 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.2306 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:34.2307 | GPTQ | METRIC - error 1136.75
2026-10-24T20:03:34.2311 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.2317 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.5.mlp.down_proj']
2026-10-24T20:03:34.2404 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:34.2406 | GPTQ | METRIC - error 29.62
2026-10-24T20:03:34.2410 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb

(7/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 919.50it/s]
(8/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 787.58it/s]

2026-10-24T20:03:34.3952 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.6.self_attn.q_proj']
2026-10-24T20:03:34.3984 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.3987 | GPTQ | METRIC - error 2397.63
2026-10-24T20:03:34.3992 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.3998 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.6.self_attn.k_proj', 'model.layers.6.self_attn.v_proj']
2026-10-24T20:03:34.4039 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.4041 | GPTQ | METRIC - error 593.23
2026-10-24T20:03:34.4045 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.4048 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.4050 | GPTQ | METRIC - error 641.80
2026-10-24T20:03:34.4054 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.4061 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.6.self_attn.o_proj']

2026-10-24T20:03:34.4106 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.4108 | GPTQ | METRIC - error 135.41
2026-10-24T20:03:34.4112 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.4118 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.6.mlp.gate_proj', 'model.layers.6.mlp.up_proj']
2026-10-24T20:03:34.4159 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.4162 | GPTQ | METRIC - error 793.36
2026-10-24T20:03:34.4166 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.4168 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.4169 | GPTQ | METRIC - error 841.20
2026-10-24T20:03:34.4173 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.4178 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.6.mlp.down_proj']
2026-10-24T20:03:34.4265 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:34.4269 | GPTQ | METRIC - error 7.17
2026-10-24T20:03:34.4275 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb

(8/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 945.69it/s]
(9/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 769.00it/s]

2026-10-24T20:03:34.5813 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.7.self_attn.q_proj']
2026-10-24T20:03:34.5843 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.5846 | GPTQ | METRIC - error 6466.10
2026-10-24T20:03:34.5849 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.5856 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.7.self_attn.k_proj', 'model.layers.7.self_attn.v_proj']
2026-10-24T20:03:34.5897 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.5899 | GPTQ | METRIC - error 1697.19
2026-10-24T20:03:34.5902 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.5904 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.5906 | GPTQ | METRIC - error 1533.52
2026-10-24T20:03:34.5909 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.5916 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.7.self_attn.o_proj']

2026-10-24T20:03:34.5962 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.5964 | GPTQ | METRIC - error 628.27
2026-10-24T20:03:34.5967 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.5973 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.7.mlp.gate_proj', 'model.layers.7.mlp.up_proj']
2026-10-24T20:03:34.6020 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.6022 | GPTQ | METRIC - error 762.41
2026-10-24T20:03:34.6026 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.6028 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:34.6031 | GPTQ | METRIC - error 853.25
2026-10-24T20:03:34.6034 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.6041 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.7.mlp.down_proj']
2026-10-24T20:03:34.6130 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:34.6133 | GPTQ | METRIC - error 16.09
2026-10-24T20:03:34.6136 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb

(9/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 897.36it/s]
(10/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 768.18it/s]

2026-10-24T20:03:34.7711 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.8.self_attn.q_proj']
2026-10-24T20:03:34.7740 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.7743 | GPTQ | METRIC - error 6511.24
2026-10-24T20:03:34.7747 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.7755 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.8.self_attn.k_proj', 'model.layers.8.self_attn.v_proj']
2026-10-24T20:03:34.7794 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.7796 | GPTQ | METRIC - error 1676.45
2026-10-24T20:03:34.7799 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.7800 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.7801 | GPTQ | METRIC - error 1815.14

2026-10-24T20:03:34.7803 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.7809 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.8.self_attn.o_proj']
2026-10-24T20:03:34.7857 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.7860 | GPTQ | METRIC - error 436.96
2026-10-24T20:03:34.7864 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.7872 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.8.mlp.gate_proj', 'model.layers.8.mlp.up_proj']
2026-10-24T20:03:34.7917 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.7919 | GPTQ | METRIC - error 778.81
2026-10-24T20:03:34.7921 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.7923 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.7924 | GPTQ | METRIC - error 860.70
2026-10-24T20:03:34.7926 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.7932 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.8.mlp.down_proj']
2026-10-24T20:03:34.8017 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:34.8018 | GPTQ | METRIC - error 7.19
2026-10-24T20:03:34.8021 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb

(10/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 929.70it/s]
(11/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 791.11it/s]

2026-10-24T20:03:34.9549 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.9.self_attn.q_proj']
2026-10-24T20:03:34.9579 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.9582 | GPTQ | METRIC - error 5165.67
2026-10-24T20:03:34.9585 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.9592 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.9.self_attn.k_proj', 'model.layers.9.self_attn.v_proj']
2026-10-24T20:03:34.9631 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.9634 | GPTQ | METRIC - error 1304.39
2026-10-24T20:03:34.9637 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.9638 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.9639 | GPTQ | METRIC - error 1334.42
2026-10-24T20:03:34.9641 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.9651 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.9.self_attn.o_proj']
2026-10-24T20:03:34.9695 | GPTQ | METRIC - time 0.00s

2026-10-24T20:03:34.9699 | GPTQ | METRIC - error 261.63
2026-10-24T20:03:34.9705 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.9715 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.9.mlp.gate_proj', 'model.layers.9.mlp.up_proj']
2026-10-24T20:03:34.9762 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:34.9767 | GPTQ | METRIC - error 347.09
2026-10-24T20:03:34.9772 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.9775 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:34.9778 | GPTQ | METRIC - error 392.62
2026-10-24T20:03:34.9781 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:34.9792 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.9.mlp.down_proj']
2026-10-24T20:03:34.9883 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:34.9886 | GPTQ | METRIC - error 5.37
2026-10-24T20:03:34.9891 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb

(11/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 928.81it/s]
(12/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 790.23it/s]

2026-10-24T20:03:35.1427 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.10.self_attn.q_proj']
2026-10-24T20:03:35.1459 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.1462 | GPTQ | METRIC - error 7283.61
2026-10-24T20:03:35.1467 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.1477 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.10.self_attn.k_proj', 'model.layers.10.self_attn.v_proj']
2026-10-24T20:03:35.1519 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.1523 | GPTQ | METRIC - error 2046.14
2026-10-24T20:03:35.1527 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.1532 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.1534 | GPTQ | METRIC - error 1677.65

2026-10-24T20:03:35.1541 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.1549 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.10.self_attn.o_proj']
2026-10-24T20:03:35.1592 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.1595 | GPTQ | METRIC - error 700.63
2026-10-24T20:03:35.1600 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.1607 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.10.mlp.gate_proj', 'model.layers.10.mlp.up_proj']
2026-10-24T20:03:35.1649 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.1651 | GPTQ | METRIC - error 658.35
2026-10-24T20:03:35.1656 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.1658 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.1660 | GPTQ | METRIC - error 700.83
2026-10-24T20:03:35.1665 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.1672 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.10.mlp.down_proj']
2026-10-24T20:03:35.1758 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:35.1760 | GPTQ | METRIC - error 7.08
2026-10-24T20:03:35.1765 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb

(12/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 913.61it/s]
(13/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 816.05it/s]

2026-10-24T20:03:35.3286 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.11.self_attn.q_proj']
2026-10-24T20:03:35.3318 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.3323 | GPTQ | METRIC - error 524.38
2026-10-24T20:03:35.3327 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.3332 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.11.self_attn.k_proj', 'model.layers.11.self_attn.v_proj']
2026-10-24T20:03:35.3371 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.3373 | GPTQ | METRIC - error 195.86
2026-10-24T20:03:35.3376 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.3377 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.3378 | GPTQ | METRIC - error 207.43
2026-10-24T20:03:35.3381 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.3385 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.11.self_attn.o_proj']

2026-10-24T20:03:35.3427 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.3428 | GPTQ | METRIC - error 78.72
2026-10-24T20:03:35.3432 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.3437 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.11.mlp.gate_proj', 'model.layers.11.mlp.up_proj']
2026-10-24T20:03:35.3477 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.3479 | GPTQ | METRIC - error 1044.43
2026-10-24T20:03:35.3481 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.3482 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.3485 | GPTQ | METRIC - error 1148.69
2026-10-24T20:03:35.3488 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.3492 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.11.mlp.down_proj']
2026-10-24T20:03:35.3578 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:35.3582 | GPTQ | METRIC - error 24.39
2026-10-24T20:03:35.3585 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb

(13/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 928.01it/s]
(14/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 789.93it/s]

2026-10-24T20:03:35.5116 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.12.self_attn.q_proj']
2026-10-24T20:03:35.5146 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.5150 | GPTQ | METRIC - error 5417.53
2026-10-24T20:03:35.5155 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.5162 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.12.self_attn.k_proj', 'model.layers.12.self_attn.v_proj']
2026-10-24T20:03:35.5203 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.5207 | GPTQ | METRIC - error 2322.51
2026-10-24T20:03:35.5211 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.5214 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.5215 | GPTQ | METRIC - error 1405.29
2026-10-24T20:03:35.5218 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.5223 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.12.self_attn.o_proj']
2026-10-24T20:03:35.5264 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.5266 | GPTQ | METRIC - error 442.05
2026-10-24T20:03:35.5269 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.5275 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.12.mlp.gate_proj', 'model.layers.12.mlp.up_proj']

2026-10-24T20:03:35.5316 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.5318 | GPTQ | METRIC - error 574.69
2026-10-24T20:03:35.5321 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.5322 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.5324 | GPTQ | METRIC - error 595.15
2026-10-24T20:03:35.5327 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.5332 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.12.mlp.down_proj']
2026-10-24T20:03:35.5417 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:35.5419 | GPTQ | METRIC - error 12.30
2026-10-24T20:03:35.5423 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb

(14/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 913.67it/s]
(15/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 824.98it/s]

2026-10-24T20:03:35.6930 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.13.self_attn.q_proj']
2026-10-24T20:03:35.6962 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.6965 | GPTQ | METRIC - error 11317.60
2026-10-24T20:03:35.6968 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.6977 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.13.self_attn.k_proj', 'model.layers.13.self_attn.v_proj']
2026-10-24T20:03:35.7018 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.7021 | GPTQ | METRIC - error 3114.19
2026-10-24T20:03:35.7026 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.7027 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.7029 | GPTQ | METRIC - error 3532.45
2026-10-24T20:03:35.7034 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.7039 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.13.self_attn.o_proj']
2026-10-24T20:03:35.7081 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.7083 | GPTQ | METRIC - error 479.01
2026-10-24T20:03:35.7086 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.7092 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.13.mlp.gate_proj', 'model.layers.13.mlp.up_proj']

2026-10-24T20:03:35.7134 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.7136 | GPTQ | METRIC - error 383.80
2026-10-24T20:03:35.7139 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.7141 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.7142 | GPTQ | METRIC - error 432.19
2026-10-24T20:03:35.7145 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.7149 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.13.mlp.down_proj']
2026-10-24T20:03:35.7237 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:35.7239 | GPTQ | METRIC - error 3.94
2026-10-24T20:03:35.7243 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb

(15/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 877.83it/s]
(16/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 769.98it/s]

2026-10-24T20:03:35.8832 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.14.self_attn.q_proj']
2026-10-24T20:03:35.8862 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.8864 | GPTQ | METRIC - error 8536.05
2026-10-24T20:03:35.8868 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.8874 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.14.self_attn.k_proj', 'model.layers.14.self_attn.v_proj']
2026-10-24T20:03:35.8914 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.8916 | GPTQ | METRIC - error 2754.77

2026-10-24T20:03:35.8920 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.8921 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.8922 | GPTQ | METRIC - error 2102.42
2026-10-24T20:03:35.8926 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.8931 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.14.self_attn.o_proj']
2026-10-24T20:03:35.8972 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.8975 | GPTQ | METRIC - error 486.84
2026-10-24T20:03:35.8978 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.8984 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.14.mlp.gate_proj', 'model.layers.14.mlp.up_proj']
2026-10-24T20:03:35.9025 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.9028 | GPTQ | METRIC - error 337.44
2026-10-24T20:03:35.9032 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.9034 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:35.9037 | GPTQ | METRIC - error 380.78
2026-10-24T20:03:35.9040 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:35.9045 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.14.mlp.down_proj']
2026-10-24T20:03:35.9132 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:35.9135 | GPTQ | METRIC - error 2.86
2026-10-24T20:03:35.9138 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb

(16/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 950.76it/s]
(17/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 781.83it/s]

2026-10-24T20:03:36.0662 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.15.self_attn.q_proj']
2026-10-24T20:03:36.0693 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:36.0696 | GPTQ | METRIC - error 10702.60
2026-10-24T20:03:36.0699 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:36.0706 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.15.self_attn.k_proj', 'model.layers.15.self_attn.v_proj']
2026-10-24T20:03:36.0746 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:36.0748 | GPTQ | METRIC - error 3129.52
2026-10-24T20:03:36.0752 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:36.0753 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:36.0755 | GPTQ | METRIC - error 2554.88
2026-10-24T20:03:36.0757 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:36.0763 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.15.self_attn.o_proj']
2026-10-24T20:03:36.0804 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:36.0806 | GPTQ | METRIC - error 1308.69
2026-10-24T20:03:36.0810 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:36.0816 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.15.mlp.gate_proj', 'model.layers.15.mlp.up_proj']

2026-10-24T20:03:36.0857 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:36.0859 | GPTQ | METRIC - error 236.17
2026-10-24T20:03:36.0863 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:36.0864 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:36.0865 | GPTQ | METRIC - error 259.62
2026-10-24T20:03:36.0869 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:36.0875 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.15.mlp.down_proj']
2026-10-24T20:03:36.0961 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:36.0963 | GPTQ | METRIC - error 2.27
2026-10-24T20:03:36.0966 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb

(17/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 925.81it/s]
(18/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 779.62it/s]

2026-10-24T20:03:36.2507 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.16.self_attn.q_proj']
2026-10-24T20:03:36.2536 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:36.2539 | GPTQ | METRIC - error 15253.34
2026-10-24T20:03:36.2542 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:36.2549 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.16.self_attn.k_proj', 'model.layers.16.self_attn.v_proj']
2026-10-24T20:03:36.2589 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:36.2592 | GPTQ | METRIC - error 4162.21
2026-10-24T20:03:36.2595 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:36.2596 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:36.2598 | GPTQ | METRIC - error 4110.54
2026-10-24T20:03:36.2601 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:36.2607 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.16.self_attn.o_proj']
2026-10-24T20:03:36.2648 | GPTQ | METRIC - time 0.00s

2026-10-24T20:03:36.2651 | GPTQ | METRIC - error 981.38
2026-10-24T20:03:36.2655 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:36.2662 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.16.mlp.gate_proj', 'model.layers.16.mlp.up_proj']
2026-10-24T20:03:36.2705 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:36.2707 | GPTQ | METRIC - error 239.10
2026-10-24T20:03:36.2710 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:36.2712 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:36.2713 | GPTQ | METRIC - error 262.88
2026-10-24T20:03:36.2716 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:36.2721 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.16.mlp.down_proj']
2026-10-24T20:03:36.2808 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:36.2810 | GPTQ | METRIC - error 2.92
2026-10-24T20:03:36.2814 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb

(18/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 972.60it/s]
(19/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 746.33it/s]

2026-10-24T20:03:36.4362 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.17.self_attn.q_proj']
2026-10-24T20:03:36.4393 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:36.4397 | GPTQ | METRIC - error 4442.41
2026-10-24T20:03:36.4401 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:36.4410 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.17.self_attn.k_proj', 'model.layers.17.self_attn.v_proj']
2026-10-24T20:03:36.4454 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:36.4457 | GPTQ | METRIC - error 1342.28
2026-10-24T20:03:36.4461 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:36.4464 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:36.4465 | GPTQ | METRIC - error 1437.72
2026-10-24T20:03:36.4469 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:36.4474 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.17.self_attn.o_proj']

2026-10-24T20:03:36.4514 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:36.4516 | GPTQ | METRIC - error 511.11
2026-10-24T20:03:36.4519 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:36.4525 | compress_module_list | INFO - Quantizing 2 module(s): ['model.layers.17.mlp.gate_proj', 'model.layers.17.mlp.up_proj']
2026-10-24T20:03:36.4566 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:36.4569 | GPTQ | METRIC - error 415.77
2026-10-24T20:03:36.4573 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:36.4575 | GPTQ | METRIC - time 0.00s
2026-10-24T20:03:36.4577 | GPTQ | METRIC - error 424.81
2026-10-24T20:03:36.4580 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb
2026-10-24T20:03:36.4585 | compress_module_list | INFO - Quantizing 1 module(s): ['model.layers.17.mlp.down_proj']
2026-10-24T20:03:36.4701 | GPTQ | METRIC - time 0.01s
2026-10-24T20:03:36.4704 | GPTQ | METRIC - error 4.96
2026-10-24T20:03:36.4708 | GPTQ | METRIC - Accelerator 0 | usage: 52.04% | total memory: 16.7 Gb

(19/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 919.97it/s]

2026-10-24T20:03:36.5454 | norm_calibration_context | INFO - Restoring 109 norm modules to offset convention
2026-10-24T20:03:36.5479 | finalize | INFO - Compression lifecycle finalized for 1 modifiers

2026-10-24T20:04:34.6453 | reset | INFO - Compression lifecycle reset

,actorder,dampening_frac,loss,size_MB,rouge1,rouge2,rougeL
0,static,0.10,4.206908,1076.311556,0.030822,0.006618,0.024143
1,static,0.01,4.214457,1076.311556,0.113499,0.030978,0.087361
2,static,0.05,4.232358,1076.311556,0.006218,0.000556,0.005545
3,NaN,0.05,4.387374,1076.311556,0.000688,0.000000,0.000688
4,NaN,0.10,4.420500,1076.311556,0.074427,0.013894,0.058678
5,NaN,0.01,4.500352,1076.311556,0.013841,0.002190,0.011321

We have decided to tune the `actorder`(changes the sequence in which model weights are quantized during the compression process) and `dampening_frac`(adds regularization to the matrix calculations) parameters to improve the GPTQ results. Setting `actorder="static"` gave lower loss for all tested values of `dampening_frac`. The lowest loss of 4.2069 was achieved with `dampening_frac=0.1`, while `dampening_frac=0.01` gave the highest ROUGE scores with a similar loss 4.2145, making it a promising choice. The reported bigger model size remained the same across all configurations.

## Activation-aware Weight Quantization (AWQ)

AWQ uses activation statistics collected from calibration data to identify important weight channels and adjust their scaling to reduce quantization error.

In [20]:
awq_model = load_baseline_model()
awq_recipe = [AWQModifier(), QuantizationModifier(targets=["Linear"], scheme="W4A16_ASYM", ignore=["lm_head"])]

oneshot(model=awq_model, tokenizer=tokenizer, dataset=calibration_dataset, recipe=awq_recipe,
        max_seq_length=MAX_SEQ_LENGTH,
        num_calibration_samples=len(calibration_dataset),
        batch_size=1,
        shuffle_calibration_samples=False)

dispatch_model(awq_model)
prompt_results_awq = model_results(baseline_model, baseline_model_loss, baseline_model_rouge, baseline_size, awq_model, "AWQ")

reset_session()
del awq_model, awq_recipe
clear_memory()

Loading weights: 100%|██████████| 236/236 [00:00<00:00, 6127.66it/s]

2026-10-24T20:04:35.8273 | reset | INFO - Compression lifecycle reset
2026-10-24T20:04:35.8316 | norm_calibration_context | INFO - Found 109 offset-norm modules to convert
2026-10-24T20:04:35.8347 | from_modifiers | INFO - Creating recipe from modifiers
2026-10-24T20:04:35.8350 | on_initialize | INFO - No AWQModifier.mappings provided, inferring from model...

Applying quantization config: 100%|██████████| 126/126 [00:00<00:00, 13793.45it/s]

2026-10-24T20:04:35.8484 | initialize | INFO - Compression lifecycle initialized for 2 modifiers
2026-10-24T20:04:35.8487 | IndependentPipeline | INFO - Inferred `SequentialPipeline` for `AWQModifier`
2026-10-24T20:04:35.8887 | _set_resolved_mappings | WARNING - 18 mappings were skipped due to incompatible shapes. Set logging to DEBUG to view full list.

Preparing cache: 100%|██████████| 64/64 [00:00<00:00, 4683.76it/s]
(1/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 1273.98it/s]
Smoothing: 0it [00:00, ?it/s]
(1/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 614.53it/s]
(2/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 790.48it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.80it/s]
(2/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 876.99it/s]
(3/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 802.07it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.71it/s]
(3/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 857.22it/s]
(4/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 801.60it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.51it/s]
(4/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 910.81it/s]
(5/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 806.82it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.74it/s]
(5/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 888.39it/s]
(6/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 791.53it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.67it/s]
(6/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 923.55it/s]
(7/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 796.69it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.75it/s]
(7/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 892.41it/s]
(8/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 773.61it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.66it/s]
(8/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 878.60it/s]
(9/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 786.33it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.76it/s]
(9/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 876.93it/s]
(10/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 776.77it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.66it/s]
(10/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 901.58it/s]
(11/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 785.56it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.70it/s]
(11/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 897.20it/s]
(12/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 792.63it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.66it/s]
(12/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 879.13it/s]
(13/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 781.03it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.72it/s]
(13/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 888.74it/s]
(14/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 814.41it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.66it/s]
(14/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 850.49it/s]
(15/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 779.92it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.64it/s]
(15/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 891.59it/s]
(16/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 776.73it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.68it/s]
(16/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 886.48it/s]
(17/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 785.13it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.69it/s]
(17/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 919.89it/s]
(18/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 789.76it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.64it/s]
(18/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 885.37it/s]
(19/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 715.72it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.72it/s]
(19/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 968.75it/s]

2026-10-24T20:04:45.2087 | IndependentPipeline | INFO - Inferred `DataFreePipeline` for `QuantizationModifier`

2026-10-24T20:04:45.2435 | norm_calibration_context | INFO - Restoring 109 norm modules to offset convention
2026-10-24T20:04:45.2471 | finalize | INFO - Compression lifecycle finalized for 2 modifiers

Baseline model size (MB): 1072.395
Quantized AWQ model size (MB): 1076.312
Baseline loss: 3.8468
AWQ loss: 4.5216

Baseline Rouge: Rouge1: 0.1168, Rouge2: 0.0290, RougeL: 0.0914
AWQ Rouge: Rouge1: 0.1068, Rouge2: 0.0283, RougeL: 0.0832

Prompt: Explain quantization of Large Language Models in 1 sentence.

Output Baseline: Quantization reduces the size of a Large Language Model (LLM) while maintaining its performance, allowing for faster inference and lower computational costs.
Output AWQ: Because of the limitations of the Large Language Models (LLMs) in the real world, they are designed to be used for specific tasks that are not directly related to the core functionality of the model.
2026-10-24T20:08:35.6557 | reset | INFO - Compression lifecycle reset

AWQ showed a slightly larger reported model size, increased loss from 3.8468 to 4.5216, and lowered all ROUGE scores. The example response followed the one-sentence instruction but failed to explain quantization. These results suggest that the basic AWQ configuration, as well as GPTQ model, needs further tuning.

In [21]:
param_grid = {"duo_scaling": [True, False], "n_grid": [20, 40]}
awq_search_results = []

for params in ParameterGrid(param_grid):
    print(f"\nTesting AWQ: {params}", flush=True)

    awq_model = load_baseline_model()

    try:
      recipe = [AWQModifier(**params),
                QuantizationModifier(
                targets=["Linear"],
                scheme="W4A16_ASYM",
                ignore=["lm_head"],)]

      oneshot(model=awq_model, tokenizer=tokenizer, dataset=calibration_dataset,
              recipe=recipe, max_seq_length=MAX_SEQ_LENGTH,
              num_calibration_samples=len(calibration_dataset),
              batch_size=1,
              shuffle_calibration_samples=False)

      dispatch_model(awq_model)
      loss = evaluate_model(awq_model, tokenizer)["loss"]
      rouge_scores = evaluate_rouge(awq_model)

      awq_search_results.append({**params, "loss": loss, "size_MB": model_size_mb(awq_model), **rouge_scores})

    finally:
        reset_session()
        del awq_model, recipe
        clear_memory()

awq_search_df = (pd.DataFrame(awq_search_results).sort_values("loss").reset_index(drop=True))
display(awq_search_df)

Testing AWQ: {'duo_scaling': True, 'n_grid': 20}

Loading weights: 100%|██████████| 236/236 [00:00<00:00, 6692.10it/s]

2026-10-24T20:08:36.7689 | reset | INFO - Compression lifecycle reset
2026-10-24T20:08:36.7716 | norm_calibration_context | INFO - Found 109 offset-norm modules to convert
2026-10-24T20:08:36.7744 | from_modifiers | INFO - Creating recipe from modifiers
2026-10-24T20:08:36.7749 | on_initialize | INFO - No AWQModifier.mappings provided, inferring from model...

Applying quantization config: 100%|██████████| 126/126 [00:00<00:00, 10943.93it/s]

2026-10-24T20:08:36.7923 | initialize | INFO - Compression lifecycle initialized for 2 modifiers
2026-10-24T20:08:36.7926 | IndependentPipeline | INFO - Inferred `SequentialPipeline` for `AWQModifier`
2026-10-24T20:08:36.8299 | _set_resolved_mappings | WARNING - 18 mappings were skipped due to incompatible shapes. Set logging to DEBUG to view full list.

Preparing cache: 100%|██████████| 64/64 [00:00<00:00, 4542.36it/s]
(1/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 1356.11it/s]
Smoothing: 0it [00:00, ?it/s]
(1/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 606.18it/s]
(2/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 776.48it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.81it/s]
(2/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 824.65it/s]
(3/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 793.60it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.91it/s]
(3/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 906.41it/s]
(4/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 807.96it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.85it/s]
(4/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 918.76it/s]
(5/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 819.72it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.85it/s]
(5/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 917.95it/s]
(6/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 820.35it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.76it/s]
(6/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 910.62it/s]
(7/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 780.83it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.78it/s]
(7/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 888.66it/s]
(8/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 781.80it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.76it/s]
(8/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 892.88it/s]
(9/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 791.42it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.95it/s]
(9/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 896.44it/s]
(10/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 784.53it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.86it/s]
(10/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 903.08it/s]
(11/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 756.32it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.66it/s]
(11/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 901.66it/s]
(12/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 838.78it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.86it/s]
(12/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 911.67it/s]
(13/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 800.10it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.66it/s]
(13/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 888.45it/s]
(14/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 787.98it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.74it/s]
(14/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 886.35it/s]
(15/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 783.71it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.61it/s]
(15/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 897.52it/s]
(16/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 784.35it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.21it/s]
(16/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 902.71it/s]
(17/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 803.36it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.80it/s]
(17/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 897.79it/s]
(18/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 800.99it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.76it/s]
(18/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 911.25it/s]
(19/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 742.18it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.75it/s]
(19/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 951.67it/s]

2026-10-24T20:08:46.0548 | IndependentPipeline | INFO - Inferred `DataFreePipeline` for `QuantizationModifier`

2026-10-24T20:08:46.0861 | norm_calibration_context | INFO - Restoring 109 norm modules to offset convention
2026-10-24T20:08:46.0888 | finalize | INFO - Compression lifecycle finalized for 2 modifiers
2026-10-24T20:12:32.2542 | reset | INFO - Compression lifecycle reset

Testing AWQ: {'duo_scaling': True, 'n_grid': 40}

Loading weights: 100%|██████████| 236/236 [00:00<00:00, 5651.70it/s]

2026-10-24T20:12:33.4258 | reset | INFO - Compression lifecycle reset
2026-10-24T20:12:33.4295 | norm_calibration_context | INFO - Found 109 offset-norm modules to convert
2026-10-24T20:12:33.4327 | from_modifiers | INFO - Creating recipe from modifiers
2026-10-24T20:12:33.4331 | on_initialize | INFO - No AWQModifier.mappings provided, inferring from model...

Applying quantization config: 100%|██████████| 126/126 [00:00<00:00, 10870.32it/s]

2026-10-24T20:12:33.4492 | initialize | INFO - Compression lifecycle initialized for 2 modifiers
2026-10-24T20:12:33.4497 | IndependentPipeline | INFO - Inferred `SequentialPipeline` for `AWQModifier`
2026-10-24T20:12:33.4824 | _set_resolved_mappings | WARNING - 18 mappings were skipped due to incompatible shapes. Set logging to DEBUG to view full list.

Preparing cache: 100%|██████████| 64/64 [00:00<00:00, 5260.76it/s]
(1/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 1435.74it/s]
Smoothing: 0it [00:00, ?it/s]
(1/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 652.10it/s]
(2/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 802.20it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  3.04it/s]
(2/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 928.47it/s]
(3/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 820.15it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  3.05it/s]
(3/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 919.12it/s]
(4/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 822.62it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  3.01it/s]
(4/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 941.78it/s]
(5/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 815.80it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  3.04it/s]
(5/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 927.93it/s]
(6/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 821.17it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  3.04it/s]
(6/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 924.09it/s]
(7/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 804.66it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  3.00it/s]
(7/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 922.74it/s]
(8/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 816.32it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  3.09it/s]
(8/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 903.14it/s]
(9/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 797.73it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  3.03it/s]
(9/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 929.37it/s]
(10/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 801.64it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  2.94it/s]
(10/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 913.06it/s]
(11/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 791.96it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  2.97it/s]
(11/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 904.86it/s]
(12/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 800.45it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  2.96it/s]
(12/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 919.11it/s]
(13/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 873.34it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  3.03it/s]
(13/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 981.19it/s]
(14/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 858.75it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  3.06it/s]
(14/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 909.94it/s]
(15/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 808.28it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  3.05it/s]
(15/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 966.23it/s]
(16/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 843.39it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  2.95it/s]
(16/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 919.29it/s]
(17/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 811.42it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  3.07it/s]
(17/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 919.26it/s]
(18/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 842.28it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  3.04it/s]
(18/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 922.35it/s]
(19/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 762.18it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  3.03it/s]
(19/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 956.94it/s]

2026-10-24T20:12:48.2631 | IndependentPipeline | INFO - Inferred `DataFreePipeline` for `QuantizationModifier`

2026-10-24T20:12:48.2927 | norm_calibration_context | INFO - Restoring 109 norm modules to offset convention
2026-10-24T20:12:48.2951 | finalize | INFO - Compression lifecycle finalized for 2 modifiers
2026-10-24T20:14:41.3671 | reset | INFO - Compression lifecycle reset

Testing AWQ: {'duo_scaling': False, 'n_grid': 20}

Loading weights: 100%|██████████| 236/236 [00:00<00:00, 5218.09it/s]

2026-10-24T20:14:42.3431 | reset | INFO - Compression lifecycle reset
2026-10-24T20:14:42.3458 | norm_calibration_context | INFO - Found 109 offset-norm modules to convert
2026-10-24T20:14:42.3490 | from_modifiers | INFO - Creating recipe from modifiers
2026-10-24T20:14:42.3492 | on_initialize | INFO - No AWQModifier.mappings provided, inferring from model...

Applying quantization config: 100%|██████████| 126/126 [00:00<00:00, 13266.78it/s]

2026-10-24T20:14:42.3628 | initialize | INFO - Compression lifecycle initialized for 2 modifiers
2026-10-24T20:14:42.3631 | IndependentPipeline | INFO - Inferred `SequentialPipeline` for `AWQModifier`
2026-10-24T20:14:42.4009 | _set_resolved_mappings | WARNING - 18 mappings were skipped due to incompatible shapes. Set logging to DEBUG to view full list.

Preparing cache: 100%|██████████| 64/64 [00:00<00:00, 4848.47it/s]
(1/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 1307.04it/s]
Smoothing: 0it [00:00, ?it/s]
(1/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 596.20it/s]
(2/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 758.99it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.62it/s]
(2/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 880.95it/s]
(3/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 782.44it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.55it/s]
(3/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 867.78it/s]
(4/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 696.50it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.67it/s]
(4/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 831.18it/s]
(5/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 786.87it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.72it/s]
(5/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 874.66it/s]
(6/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 745.25it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.65it/s]
(6/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 844.87it/s]
(7/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 757.46it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.74it/s]
(7/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 870.63it/s]
(8/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 783.96it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.44it/s]
(8/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 876.52it/s]
(9/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 725.93it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.42it/s]
(9/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 847.71it/s]
(10/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 774.69it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.56it/s]
(10/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 834.38it/s]
(11/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 789.52it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.74it/s]
(11/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 910.09it/s]
(12/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 802.53it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.53it/s]
(12/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 901.35it/s]
(13/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 750.66it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.76it/s]
(13/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 877.28it/s]
(14/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 808.65it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.45it/s]
(14/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 845.86it/s]
(15/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 817.95it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.18it/s]
(15/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 865.16it/s]
(16/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 795.37it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.19it/s]
(16/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 914.40it/s]
(17/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 787.95it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.72it/s]
(17/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 896.24it/s]
(18/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 781.81it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.60it/s]
(18/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 874.10it/s]
(19/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 716.13it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  5.73it/s]
(19/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 955.63it/s]

2026-10-24T20:14:51.9231 | IndependentPipeline | INFO - Inferred `DataFreePipeline` for `QuantizationModifier`

2026-10-24T20:14:51.9572 | norm_calibration_context | INFO - Restoring 109 norm modules to offset convention
2026-10-24T20:14:51.9603 | finalize | INFO - Compression lifecycle finalized for 2 modifiers
2026-10-24T20:17:09.8838 | reset | INFO - Compression lifecycle reset

Testing AWQ: {'duo_scaling': False, 'n_grid': 40}

Loading weights: 100%|██████████| 236/236 [00:00<00:00, 4976.93it/s]

2026-10-24T20:17:10.9005 | reset | INFO - Compression lifecycle reset
2026-10-24T20:17:10.9029 | norm_calibration_context | INFO - Found 109 offset-norm modules to convert
2026-10-24T20:17:10.9073 | from_modifiers | INFO - Creating recipe from modifiers
2026-10-24T20:17:10.9078 | on_initialize | INFO - No AWQModifier.mappings provided, inferring from model...

Applying quantization config: 100%|██████████| 126/126 [00:00<00:00, 13629.81it/s]

2026-10-24T20:17:10.9228 | initialize | INFO - Compression lifecycle initialized for 2 modifiers
2026-10-24T20:17:10.9232 | IndependentPipeline | INFO - Inferred `SequentialPipeline` for `AWQModifier`
2026-10-24T20:17:10.9678 | _set_resolved_mappings | WARNING - 18 mappings were skipped due to incompatible shapes. Set logging to DEBUG to view full list.

Preparing cache: 100%|██████████| 64/64 [00:00<00:00, 5681.77it/s]
(1/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 1062.49it/s]
Smoothing: 0it [00:00, ?it/s]
(1/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 592.19it/s]
(2/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 752.31it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  2.86it/s]
(2/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 887.19it/s]
(3/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 795.08it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  2.93it/s]
(3/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 930.80it/s]
(4/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 801.04it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  2.97it/s]
(4/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 864.55it/s]
(5/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 779.75it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  2.96it/s]
(5/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 903.96it/s]
(6/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 820.89it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  2.90it/s]
(6/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 925.93it/s]
(7/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 807.13it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  2.80it/s]
(7/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 891.44it/s]
(8/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 791.17it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  2.96it/s]
(8/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 906.86it/s]
(9/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 798.06it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  2.89it/s]
(9/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 877.37it/s]
(10/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 805.50it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  2.90it/s]
(10/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 910.92it/s]
(11/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 781.31it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  2.95it/s]
(11/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 925.52it/s]
(12/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 786.07it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  2.90it/s]
(12/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 854.70it/s]
(13/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 799.71it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  2.90it/s]
(13/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 852.23it/s]
(14/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 754.36it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  2.91it/s]
(14/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 843.02it/s]
(15/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 756.45it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  2.84it/s]
(15/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 819.26it/s]
(16/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 745.57it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  2.90it/s]
(16/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 853.90it/s]
(17/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 767.16it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  2.93it/s]
(17/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 865.81it/s]
(18/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 768.70it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  2.93it/s]
(18/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 842.39it/s]
(19/19): Calibrating: 100%|██████████| 64/64 [00:00<00:00, 691.07it/s]
Smoothing: 100%|██████████| 2/2 [00:00<00:00,  2.86it/s]
(19/19): Propagating: 100%|██████████| 64/64 [00:00<00:00, 885.02it/s]

2026-10-24T20:17:26.4016 | IndependentPipeline | INFO - Inferred `DataFreePipeline` for `QuantizationModifier`

2026-10-24T20:17:26.4347 | norm_calibration_context | INFO - Restoring 109 norm modules to offset convention
2026-10-24T20:17:26.4378 | finalize | INFO - Compression lifecycle finalized for 2 modifiers
2026-10-24T20:17:44.7600 | reset | INFO - Compression lifecycle reset

   duo_scaling  n_grid      loss      size_MB    rouge1    rouge2    rougeL
0         True      40  4.452035  1076.311556  0.056333  0.016977  0.043951
1        False      20  4.491760  1076.311556  0.060404  0.017165  0.045897
2        False      40  4.497848  1076.311556  0.002939  0.000000  0.001821
3         True      20  4.521560  1076.311556  0.106830  0.028279  0.083216

We have decided to tune the `duo_scaling`(controls whether scaling uses both weight and activation statistics or only activation statistics) and `n_grid`(sets the number of scaling candidates tested to find the one with the lowest quantization error) parameters to improve the AWQ results. Setting `duo_scaling=True` and `n_grid=40` gave the lowest loss of 4.4520, while the original configuration with `duo_scaling=True` and `n_grid=20` kept the highest ROUGE scores. Tuning slightly improved loss but reduced ROUGE scores, so there was no clear overall improvement. The reported model size remained the same across all configurations.

## Half-Quadratic Quantization (HQQ)

HQQ is a post-training weight quantization method that uses half-quadratic optimization to reduce the error between original and quantized weights.

In [22]:
hqq_model = load_baseline_model()
quant_config = BaseQuantizeConfig(nbits=8, group_size=64)
AutoHQQHFModel.quantize_model(hqq_model, quant_config=quant_config, compute_dtype=DTYPE, device="cuda:0",)
prompt_results_hqq = model_results(baseline_model, baseline_model_loss, baseline_model_rouge, baseline_size, hqq_model, "HQQ")

save_dir = "../models/gemma-hqq-xlsum"
AutoHQQHFModel.save_quantized(hqq_model, save_dir)
tokenizer.save_pretrained(save_dir)

del hqq_model
clear_memory()

Loading weights: 100%|██████████| 236/236 [00:00<00:00, 4976.63it/s]
100%|██████████| 129/129 [00:00<00:00, 84264.95it/s]
100%|██████████| 127/127 [00:00<00:00, 905.36it/s]

Baseline model size (MB): 1072.395
Quantized HQQ model size (MB): 771.585
Baseline loss: 3.8468
HQQ loss: 3.8612

Baseline Rouge: Rouge1: 0.1168, Rouge2: 0.0290, RougeL: 0.0914
HQQ Rouge: Rouge1: 0.1136, Rouge2: 0.0277, RougeL: 0.0884

Prompt: Explain quantization of Large Language Models in 1 sentence.

Output Baseline: Quantization reduces the size of a Large Language Model (LLM) while maintaining its performance, allowing for faster inference and lower computational costs.
Output HQQ: Quantization reduces the size of a Large Language Model (LLM) while maintaining its performance, allowing for faster inference and lower computational costs.

HQQ reduced the model size by 28%, with only a small increase in loss from 3.8468 to 3.8612 and slight decreases in all ROUGE scores. The example response was identical to the baseline, preserving both accuracy and the one-sentence instruction. These results show a good balance between size reduction and maintaining model quality.

## Results

| Experiment | Configuration | Model size (MB) | Loss | ROUGE-1 | ROUGE-2 | ROUGE-L |
|---|---|---:|---:|---:|---:|---:|
| Baseline | Original model, FP32 | 1072.395 | 3.8468 | 0.1168 | 0.0290 | 0.0914 |
| Linear Symmetric | INT8, symmetric | 771.585 | 4.0384 | 0.1114 | 0.0267 | 0.0848 |
| Linear Asymmetric | INT8, asymmetric | 771.585 | 3.9352 | 0.1049 | 0.0227 | 0.0810 |
| NF4 | 4-bit NormalFloat | 721.449 | 4.3888 | 0.1120 | 0.0252 | 0.0847 |
| GPTQ | Basic configuration | 1076.312 | 4.4205 | 0.0744 | 0.0139 | 0.0587 |
| GPTQ — lowest loss | `actorder="static"`, `dampening_frac=0.1` | 1076.312 | 4.2069 | 0.0308 | 0.0066 | 0.0241 |
| GPTQ — highest ROUGE | `actorder="static"`, `dampening_frac=0.01` | 1076.312 | 4.2145 | 0.1135 | 0.0310 | 0.0874 |
| AWQ — highest ROUGE | `duo_scaling=True`, `n_grid=20` | 1076.312 | 4.5216 | 0.1068 | 0.0283 | 0.0832 |
| AWQ — lowest loss | `duo_scaling=True`, `n_grid=40` | 1076.312 | 4.4520 | 0.0563 | 0.0170 | 0.0440 |
| HQQ | Tested configuration | 771.585 | 3.8612 | 0.1136 | 0.0277 | 0.0884 |

The experiments show that, for Gemma 3-270M evaluated on XL-Sum, Half-Quadratic Quantization (HQQ) provided the best balance between model size and quality among the tested configurations. It reduced the reported model size by 28% while keeping loss and ROUGE scores close to the baseline. GPTQ and AWQ generally performed worse in this setup, which may be related to several factors, including the calibration dataset, its size, the maximum token sequence length, and the quantization parameters. With suitable settings, quantization can reduce model size while keeping quality close to the original, as shown by the simple linear quantization approaches implemented in these experiments.